const { Paragraph, TextRun, AlignmentType } = require('docx');
const { p, pEmpty, h2, h3, bullet, pageBreak, warningBox, C } = require('./helpers');

function cap0() {
  return [
    // Título principal
    new Paragraph({
      children: [new TextRun({ text: "El Guardián de los Sentires", font: "Arial", size: 56, bold: true, color: C.purpleDeep })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 400, after: 120 },
    }),
    new Paragraph({
      children: [new TextRun({ text: "Campaña de D&D 5e", font: "Arial", size: 28, bold: false, color: C.purpleMid, italics: true })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 0, after: 80 },
    }),
    new Paragraph({
      children: [new TextRun({ text: "Continuación de La Mina Perdida de Phandelver", font: "Arial", size: 24, bold: false, color: C.grayMid, italics: true })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 0, after: 80 },
    }),
    new Paragraph({
      children: [new TextRun({ text: "Documento de Referencia del Dungeon Master", font: "Arial", size: 24, bold: true, color: C.grayDark })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 0, after: 200 },
    }),
    warningBox("Documento vivo — se expande con cada sesión"),
    pEmpty(200),
    pageBreak(),

    // Tabla de contenidos
    h2("Tabla de Contenidos"),
    pEmpty(60),
    bullet("1. Visión General de la Campaña"),
    bullet("1.1 Premisa Central", false, C.grayMid),
    bullet("1.2 La Noche en que Cayeron las Estrellas (Escena Ya Jugada)", false, C.grayMid),
    bullet("1.3 Tono y Estilo", false, C.grayMid),
    bullet("1.4 Los Personajes Jugadores", false, C.grayMid),
    bullet("1.5 Estructura de Tres Actos", false, C.grayMid),
    bullet("1.6 Progresión de Nivel — Hitos Narrativos", false, C.grayMid),
    bullet("1.7 Flujo de la Campaña — Orden de las Zonas", false, C.grayMid),
    bullet("1.8 Neverwinter — Por Qué el Grupo Va Ahí", false, C.grayMid),
    pEmpty(60),
    bullet("2. Personajes Clave (NPCs Principales)"),
    bullet("2.1 Chromatus — El Guardián de los Sentires", false, C.grayMid),
    bullet("2.2 Unidad 7-Logos — El Archivero", false, C.grayMid),
    bullet("2.3 El Coleccionista de Sombras", false, C.grayMid),
    bullet("2.4 Barnaby el 'Cuerdo'", false, C.grayMid),
    bullet("2.5 Cómo se Descubre el Nombre 'Mnemós'", false, C.grayMid),
    bullet("2.6 Lore Profundo — Chromatus, los Guardianes y los Tejedores", false, C.grayMid),
    pEmpty(60),
    bullet("3. Mecánicas de Viaje — El Sextante de Cromaticidad"),
    bullet("3.1 Las Tres Tiradas de Navegación", false, C.grayMid),
    bullet("3.2 Tabla de Resultados", false, C.grayMid),
    bullet("3.3 Regla de Sincronía", false, C.grayMid),
    bullet("3.4 Las Sombras de Duda — Enemigo de Viaje", false, C.grayMid),
    pEmpty(60),
    bullet("4. Zona 1 — Cuerda-Floja (Escama Amarilla / Alegría)"),
    bullet("5. Zona 2 — El Pantano de los Muertos (Escama Azul / Tristeza)"),
    bullet("6. Zona 3 — Monte Hotenow (Escama Roja / Ira)"),
    bullet("7. Zona 4 — El Bosque de Neverwinter (Escama Verde / Calma)"),
    bullet("8. Zona 5 — El Plano del Archivo / El Clímax (Escama Negra / Miedo)"),
    pEmpty(60),
    bullet("9. Misiones Secundarias Globales"),
    bullet("9.1 El Taller del Recuerdo (Neverwinter)", false, C.grayMid),
    bullet("9.2 Los Sin-Color — Combate y Detalle Completo", false, C.grayMid),
    bullet("9.3 El Diario de Logos — Arco Completo", false, C.grayMid),
    bullet("9.4 La Colección Antigua — Lore Profundo", false, C.grayMid),
    pEmpty(60),
    bullet("10. Referencia Rápida para el DM"),
    bullet("10.1-10.11 Bonificaciones, Progresión, Pistas, Frases de Logos, Cronología, Diseño, Aliados, Relojes Narrativos, Notas, Descarriles, Momentos de Fogata", false, C.grayMid),
    pEmpty(60),
    bullet("11. Encuentros, Dungeons y Bestiario"),
    bullet("11.0 Calibración de CR", false, C.grayMid),
    bullet("11.1 Bestiario Temático", false, C.grayMid),
    bullet("11.2 Encuentros de Camino", false, C.grayMid),
    bullet("11.3 Dungeon — Las Criptas Anegadas (Zona 2)", false, C.grayMid),
    bullet("11.4 Dungeon Opcional — Las Galerías Profundas (Zona 3)", false, C.grayMid),
    bullet("11.5 Dungeon — Las Raíces Hondas (Zona 4)", false, C.grayMid),
    bullet("11.6 Acto III — Conflictos del Plano del Archivo", false, C.grayMid),
    bullet("11.7 Índice de Encuentros de Combate", false, C.grayMid),
    pEmpty(60),
    bullet("12. Apéndice Secreto — El Titiritero (Solo para el DM)"),
    bullet("12.1-12.10 Ozyr Thane / Lord Veil, La Siembra, El Telar, Pistas, Red de Influencia, Las 6 Pistas, Por Qué Todo le Sirve, Misterios, Iarno el Experimento Recurrente, Semilla para Campaña Futura", false, C.grayMid),
    pEmpty(60),
    bullet("13. NPCs Llevables"),
    bullet("13.1 Tova la Aprendiz | 13.2 Sylveth | 13.3 Goro el Rastreador | 13.4 Notas de Mesa", false, C.grayMid),
    pEmpty(60),
    bullet("14. Arcos Personales de los Personajes Jugadores"),
    bullet("14.1 El Arco de Hola — La Casa, el Hermanastro, el Padre", false, C.grayMid),
    bullet("14.2 El Arco de Angelus — El Plano Gris y el Abuelo Sobreviviente", false, C.grayMid),
    bullet("14.3 El Arco de Greyskull — Sangre Ancestral de Gigantes", false, C.grayMid),
    bullet("14.4 El Momento de las Tres Tentaciones (al reunir la 3ª Escama)", false, C.grayMid),
    pEmpty(140),
    pageBreak(),
  ];
}
module.exports = { cap0 };
