const { p, pEmpty, h1, h2, h3, bullet, numBullet, infoTable, noteBox, secretBox, loreBox, voiceBox, warningBox, cdBox, xpBox, pageBreak, C } = require('./helpers');

function cap10() {
  return [
    h1("10. Referencia R\u00e1pida para el DM"),

    h2("10.1 Bonificaciones Acumuladas por Escama"),
    infoTable([
      ["Escama","Emoci\u00f3n","Bonificaci\u00f3n \u2014 Permanente para el grupo"],
      ["Amarilla","Alegr\u00eda","+2 a la iniciativa"],
      ["Azul","Tristeza","Respirar bajo el agua indefinidamente"],
      ["Roja","Ira","+1d4 da\u00f1o de fuego a todos los ataques con arma"],
      ["Verde","Calma","Ventaja en todas las tiradas de Sigilo"],
      ["Negra","Miedo","Ver cada Final \u2014 var\u00eda seg\u00fan resoluci\u00f3n elegida (secci\u00f3n 8.11)"],
    ], 1800, 7560),
    pEmpty(140),

    h2("10.2 Progresi\u00f3n de Nivel \u2014 Resumen"),
    infoTable([
      ["Hito","Nivel resultante"],
      ["Inicio (fin de Phandelver)","5"],
      ["Escama Amarilla restaurada","6"],
      ["Escama Azul restaurada","7"],
      ["Escama Roja restaurada","9"],
      ["Escama Verde restaurada","11"],
      ["Acceso al Plano del Archivo + desaf\u00edo de los Miedos","12"],
      ["Resoluci\u00f3n del cl\u00edmax","13"],
    ]),
    pEmpty(140),

    h2("10.3 Mapa de Pistas y Continuidad del Nombre 'Mnem\u00f3s'"),
    warningBox("REGLA DE ORO: el nombre 'Mnem\u00f3s' NO debe usarse en la mesa antes de Monte Hotenow (secci\u00f3n 6.6). Antes de eso, todos los NPCs y Logos se refieren a \u00e9l como 'el Coleccionista', 'el Coleccionista de Sombras', 'el Ge\u00f3grafo Azul', o 'el anciano del libro'. Logos conoce el nombre desde Hotenow pero NO sabe que es su creador hasta el Plano del Archivo (secci\u00f3n 8.6)."),
    pEmpty(100),
    infoTable([
      ["D\u00f3nde","Pista","Nombre usado"],
      ["Phandalin (inicio)","Libro de historia con p\u00e1ginas arrancadas \u2014 un archivista an\u00f3nimo document\u00f3 desastres","Sin nombre"],
      ["Cuerda-Floja","Barnaby le dio un mapa de 'lugares felices' creyendo que era ge\u00f3grafo","'El Ge\u00f3grafo Azul'"],
      ["Nira (Cuerda-Floja)","El hombre del libro azul midi\u00f3 el pueblo durante d\u00edas antes de llevarse algo invisible","Sin nombre"],
      ["Pantano \u2014 Opci\u00f3n A","El esp\u00edritu (Wren y la Vieja Ra\u00edz) vio llorar al Coleccionista. Luego borr\u00f3 ese llanto","'El Coleccionista'"],
      ["Pergaminos de Goro","Lleg\u00f3 tres veces antes de extraer. La tercera tra\u00eda un frasco negro que absorb\u00eda la luz","'El Coleccionista'"],
      ["Monte Hotenow","Inscripci\u00f3n del yunque: 'El dolor es un archivo corrupto. Debo limpiarlo todo. \u2014 Mnem\u00f3s'","PRIMERA APARICI\u00d3N DEL NOMBRE"],
      ["Bosque de Neverwinter","Lista de nombres queridos \u2014 todos tachados. El \u00faltimo sin tachar: Chromatus","'El Coleccionista' (Logos no conecta autom\u00e1ticamente con Mnem\u00f3s)"],
      ["MS Taller del Recuerdo","Vex informa movimientos del grupo \u2014 el Coleccionista los ha seguido desde el inicio","'El Coleccionista' (Vex tampoco sabe su nombre real)"],
      ["Plano del Archivo, Sala 5","Logos reconoce el lugar y confirma: Mnem\u00f3s es su creador","CONFIRMACI\u00d3N TOTAL"],
    ]),
    pEmpty(140),

    h2("10.4 Frases Clave de Logos por Etapa"),
    infoTable([
      ["Momento","Frase"],
      ["Presentaci\u00f3n","'Mi funci\u00f3n es observar vuestro intento de reparaci\u00f3n. Procedan, unidades biol\u00f3gicas.'"],
      ["\u00c9xito de navegaci\u00f3n","'Frecuencia detectada. El rastro es n\u00edtido. Ruta optimizada al 94%.'"],
      ["Fallo de navegaci\u00f3n","'Interferencia detectada. Hay ruido en la se\u00f1al. Ajusten sus variables.'"],
      ["Ante el esp\u00edritu del Pantano","'La decisi\u00f3n \u00f3ptima ser\u00eda la extracci\u00f3n. Noto resistencia en el grupo. Registrando anomal\u00eda.'"],
      ["Opci\u00f3n A del Pantano elegida","'M\u00e9todo: resoluci\u00f3n narrativa. Eficiencia: 23%. Resultado emocional: no categorizable. Reclasificando.'"],
      ["Opci\u00f3n B del Pantano elegida","'M\u00e9todo: extracci\u00f3n forzada. Nota: el sujeto ya no existe. Registrando como p\u00e9rdida de datos permanente.'"],
      ["Traduciendo el yunque en Hotenow","'Nombre propio detectado: Mnem\u00f3s. Sin coincidencias en mi base de datos. Almacenando para referencia futura.'"],
      ["Ante el \u00e1rbol del Bosque","'No encuentro datos. Esta decisi\u00f3n no es l\u00f3gica. Interesante.'"],
      ["Al ver la lista del \u00e1rbol","'Revisando mi clasificaci\u00f3n del sujeto. Era m\u00e1s compleja de lo que registr\u00e9.'"],
      ["Al entrar al Archivo","'He estado aqu\u00ed antes. No f\u00edsicamente. Pero... conozco este lugar. No entiendo por qu\u00e9 dije eso.'"],
      ["Al ver a Mnem\u00f3s en Sala 5","'Reconocimiento de instalaci\u00f3n: 100%. Fabricante identificado: Mnem\u00f3s. El sujeto frente a nosotros es mi creador.'"],
      ["En el Cl\u00edmax (uni\u00f3n de escamas)","'Los datos no explican por qu\u00e9 quiero que esto funcione. Error de sistema. O... no es un error.'"],
    ]),
    pEmpty(140),

    h2("10.5 Cronolog\u00eda de Sesiones"),
    infoTable([
      ["Sesiones","Contenido","Nivel"],
      ["1\u20133","Acto I: Phandalin, gancho, Chromatus, Logos, primera navegaci\u00f3n","5"],
      ["4\u20136","Escama Amarilla: Cuerda-Floja, Barnaby, ritual, primera pista del Coleccionista","5\u21926"],
      ["7\u201310","Escama Azul: Pantano de los Muertos, la Vieja Ra\u00edz, decisi\u00f3n moral del esp\u00edritu","6\u21927"],
      ["11\u201312","Misi\u00f3n secundaria: Taller del Recuerdo en Neverwinter. Descubrir a Vex","7"],
      ["13\u201316","Escama Roja: Monte Hotenow, Korrund, decisi\u00f3n del recuerdo del Gigante. Se revela 'Mnem\u00f3s'","7\u21929"],
      ["17\u201318","Misi\u00f3n secundaria: Los Sin-Color. Decisi\u00f3n de c\u00f3mo manejarlos","9"],
      ["19\u201322","Escama Verde: Bosque de Neverwinter, Sylveth, la Madre Ra\u00edz, el mecanismo, Plano de las Hadas","9\u219211"],
      ["23\u201324","Investigaci\u00f3n: deducir c\u00f3mo abrir el portal del Archivo (secci\u00f3n 8.1)","11"],
      ["25\u201327","Acto III: El Archivo, las 5 salas, los miedos, la conversaci\u00f3n con Mnem\u00f3s","11\u219212"],
      ["28\u201330+","Resoluci\u00f3n seg\u00fan final elegido. Ep\u00edlogos de cada NPC","12\u219213"],
    ], 1600, 5760, 2000),
    pEmpty(140),

    h2("10.6 Notas de Diseño — Lo Invisible"),
    secretBox("Esta campaña trabaja la expresión emocional de forma lateral. El diseño garantiza que el tema nunca se declare. En su lugar: personajes que necesitan ser escuchados para que el mundo avance; momentos donde nombrar algo tiene efecto mecánico real; un villano cuya lógica es comprensible; y Logos, que aprende a sentir siendo observador. Si el jugador más chico (Angelus, 11) conecta con alguno de esos hilos, genial. Si no, igual tiene una campaña excelente con mucha acción y loot."),
    pEmpty(80),
    infoTable([
      ["Jugador","Cómo adaptar en cada zona"],
      ["Angelus (11)","Dale agencia constante y victorias claras: su rol en resolver situaciones concretas (puzzles, momentos de acción) lo mantiene enganchado. Los dilemas morales abstractos pueden quedarle grandes — preséntaselos en términos sencillos y personales"],
      ["Hola (14)","Los dilemas morales sin respuesta correcta son para él. No los suavices: a esta edad disfruta del peso de decidir y de que no haya una opción 'obviamente buena'"],
      ["Greyskull","Es el ancla emocional de la mesa. Su arco de fuerza-con-fe es el más claro"],
      ["Pícaro (DM)","Tu personaje puede ser el que menos habla de sus emociones y más cambia en silencio — paralelo a Logos"],
    ]),
    pEmpty(140),

    h2("10.7 Nota sobre Aliados de Alto Poder"),
    warningBox("Recordatorio de balance: el golem de Hola y la quimera montura de Greyskull est\u00e1n incluidos en el c\u00e1lculo de dificultad de todos los combates de este documento. Si en una sesi\u00f3n espec\u00edfica estos aliados no pueden participar (espacio reducido, separados del grupo, etc.), ajustar el encuentro bajando el CR en 1-2 puntos o a\u00f1adiendo una ronda de ventaja inicial a la party para compensar."),
    pEmpty(140),

    h2("10.8 Relojes Narrativos — Resumen de Consecuencias por Demora"),
    p("Tabla de referencia rápida de todos los relojes narrativos de la campaña. Ventana ajustada: 2-3 ZONAS COMPLETAS de demora para activarse — no sesiones, no días de exploración dentro de la misma zona. Ningún reloj se anuncia a la mesa — la consecuencia, si ocurre, debe sentirse genuina y no telegrafiada."),
    pEmpty(80),
    warningBox("LO QUE NUNCA CUENTA COMO DEMORA: explorar a fondo la zona donde está el reloj, hablar con NPCs de esa zona, completar misiones secundarias ahí mismo, o tomar descansos narrativos normales. El reloj solo avanza si el grupo ignora o abandona la situación durante el tiempo equivalente a VARIAS zonas completas sin volver."),
    pEmpty(80),
    infoTable([
      ["NPC / Caso","Detalle completo en","Consecuencia si tardan demasiado"],
      ["Dwin Arbolero (Bosque)","Sección 7.5","Muere — lo encuentran caído, sin mapa ni gancho de gremio de forrajeo. La MS-4C desaparece con él"],
      ["Korrund (Hotenow)","Sección 6.5","La ira se vuelve irreversible — solo quedan Opción B o el combate. El Boon de Korrund en el clímax no está disponible"],
      ["Garrick (Neverwinter, vía Donto)","Sección 4.7, MS-1B","Pierde su posada y se va de la ciudad — consecuencia suave, sin impacto en la trama principal, pero cierra una puerta de información menor"],
      ["Old Pell (Taller del Recuerdo)","Sección 9.1","Intenta robar su propio anillo, termina detenido o herido — el Taller del Recuerdo pierde un NPC útil y la misión de Dax se complica"],
    ], 2400, 2800, 2000, 4160),
    pEmpty(80),
    secretBox("Si tu mesa quiere más de estos relojes, el patrón es replicable para cualquier NPC con una situación en curso — la clave es que la consecuencia afecte algo que el grupo ya valora (un aliado, un acceso, una fuente de información) sin castigar la exploración legítima."),
    pEmpty(140),

    h2("10.9 Espacio para Notas del DM"),
    noteBox("SESIÓN ACTUAL", "[ Número de sesión, escama activa, nivel del grupo, estado de Logos, decisiones tomadas que afectan el clímax ]", "FAFAFA", C.grayMid),
    pEmpty(80),
    noteBox("DECISIONES MORALES TOMADAS", "[ Opción A/B/C en cada zona, consecuencias pendientes ]", "FAFAFA", C.grayMid),
    pEmpty(80),
    noteBox("ESTADO DE LOGOS", "[ Preguntas que ya hizo, cómo lo trató el grupo, qué hará en el clímax ]", "FAFAFA", C.grayMid),
    pEmpty(140),

    h2("10.10 Cuando la Party se Descarrila Totalmente"),
    p("Esta sección es distinta de los relojes narrativos (10.8), que cubren demoras DENTRO del camino esperado. Esto es para cuando el grupo se sale del mapa por completo: ignoran a Logos, se van en otra dirección, deciden quedarse indefinidamente en un lugar sin avanzar, o hacen algo que este documento nunca contempló. Con dos jugadores chicos en la mesa, esto va a pasar — es normal y está bien. Acá tenés herramientas genéricas, no parches puntuales, para cualquier desvío real."),
    pEmpty(80),

    h3("Primero: diagnosticá qué tipo de descarrile es"),
    infoTable([
      ["Tipo de descarrile","Qué se ve en la mesa","Herramienta a usar"],
      ["Curiosidad genuina","Quieren explorar algo que no estaba planeado, con energía e interés real","Improvisación con anclas (ver 10.10.1) — es la mejor señal posible, no hay que corregirla, hay que sostenerla"],
      ["Distracción momentánea","Se desvían un rato, pero sin compromiso real (charlan de otra cosa, prueban algo random sin convicción)","Un gancho gentil (ver 10.10.2) — un NPC, un sonido, algo que los reoriente sin forzar"],
      ["Estancamiento","Llevan mucho tiempo en un lugar sin decidir qué hacer, dando vueltas en círculo","Inyectar presión leve (ver 10.10.3) — algo que mueva el reloj sin que se sienta forzado"],
      ["Rechazo activo del gancho principal","Deciden explícitamente NO seguir a Logos, NO ir a las zonas, o plantean querer una campaña diferente","Pivotear la campaña con lo que tenés (ver 10.10.4) — la opción más rara, pero la más importante de tener clara"],
    ], 2400, 3200, 2400, 2400),
    pEmpty(140),

    h3("10.10.1 — Improvisación con Anclas"),
    p("Cuando el grupo se va por curiosidad real hacia algo que no planeaste, no improvises desde cero — improvisa ANCLADO en lo que ya existe. Esto te ahorra trabajo y mantiene la coherencia."),
    pEmpty(80),
    bullet("Reusá un NPC existente con una cara nueva: si entran a un pueblo random no planeado, el tabernero puede ser 'igual' a Donto en estructura (alguien con un problema chico que resolver) sin que lo notes vos mismo en el momento — el molde ya está probado"),
    bullet("Reusá una mecánica ya construida: ¿exploran una cueva que no estaba en el mapa? Usá el esqueleto de cualquier dungeon del Cap. 11 (3-4 salas, un puzzle, un mini-jefe, loot) y cambiale la piel temática sobre la marcha"),
    bullet("Conectá lo nuevo con el Titiritero (Cap. 12) en secreto: si necesitás que algo random tenga peso narrativo sin inventar de cero, cualquier rumor de poder político en la región puede ser, sin que la mesa lo sepa, una hebra más de la red de Ozyr — vos ya tenés el trasfondo armado en 12.5"),
    bullet("Las Sombras de Duda (sección 3.4) son tu monstruo de bolsillo universal — funcionan temáticamente en CUALQUIER lugar de la campaña, así que sirven para rellenar un encuentro de combate improvisado sin romper el tono"),
    pEmpty(140),

    h3("10.10.2 — El Gancho Gentil"),
    p("Para distracciones momentáneas, no hace falta una intervención grande. Las herramientas más simples:"),
    pEmpty(80),
    bullet("Logos pregunta algo (cualquier frase de la tabla 10.4 sirve, o improvisá en su tono) — su sola presencia recuerda que hay una misión en curso, sin sonar a regaño"),
    bullet("Un sonido o imagen ambiental que apunta sutilmente a la próxima zona — un pájaro que vuela hacia el norte, un viajero que menciona de pasada algo relacionado"),
    bullet("Si tus hijos están claramente más interesados en otra cosa por un rato, dejalos — un descanso narrativo de 10-15 minutos de mesa no rompe nada. El gancho gentil es para cuando QUERÉS reencauzar, no una obligación constante"),
    pEmpty(140),

    h3("10.10.3 — Presión Leve para el Estancamiento"),
    p("Si llevan mucho tiempo sin decidir qué hacer (no por explorar a fondo, sino por quedarse trabados), normalmente es porque no tienen claro cuál es el próximo paso, no porque no quieran avanzar. Antes de forzar nada, preguntate si el problema es de información: ¿Logos les recordó la última pista? Si sí, y siguen sin decidirse:"),
    pEmpty(80),
    bullet("Un NPC menor aparece con una pregunta o pedido simple que reabre el ritmo (no tiene que ser dramático — Tova preguntando algo, un mensajero con una carta)"),
    bullet("Uno de los relojes narrativos de 10.8 puede dar el empujón si corresponde temáticamente — recordá que esos relojes existen también para esto, no solo para penalizar"),
    bullet("Como último recurso, podés ser directo FUERA del personaje: 'che, ¿qué quieren hacer ahora?' — con hijos de 11 y 14, a veces la herramienta más efectiva es simplemente preguntar, sin que eso rompa la inmersión de forma grave"),
    pEmpty(140),

    h3("10.10.4 — Pivotear la Campaña (el escenario grande)"),
    p("Si el grupo decide de forma sostenida que no quiere seguir el gancho de Chromatus/Logos —raro con hijos que disfrutan el roleplay, pero posible— no lo fuerces. Tenés tres salidas, todas válidas:"),
    pEmpty(80),
    bullet("DEJAR QUE CHROMATUS ESPERE: la premisa no tiene reloj propio. El dragón sigue ahí, paciente, mientras el grupo hace otra cosa. Pueden volver en cualquier momento sin que se haya 'perdido' nada — esto es honestamente el diseño más fácil de sostener, porque no requiere que vos improvises una campaña nueva"),
    bullet("USAR EL TITIRITERO COMO PLAN B: si el grupo se desvía hacia la política de Neverwinter, el comercio, o cualquier intriga urbana, tenés TODO un capítulo (12) de trasfondo listo para improvisar una mini-trama paralela sin que sepan que están tocando algo más grande — esto puede mantenerlos entretenidos sesiones enteras sin que vos tengas que inventar nada desde cero"),
    bullet("ACEPTAR EL CAMBIO DE RUMBO: si genuinamente quieren jugar otra cosa por un tiempo (una mini-aventura de pueblo, un torneo, lo que sea), está perfectamente bien pausar 'El Guardián de los Sentires' por unas sesiones. No es un fracaso de la campaña — es una mesa familiar jugando como quiere jugar. Podés retomar el gancho principal cuando estén listos, usando el mismo recordatorio gentil de 10.10.2"),
    pEmpty(80),
    secretBox("La regla de fondo en todos los casos: tus hijos disfrutando la sesión siempre es más importante que seguir el documento. El documento es una herramienta al servicio de la mesa, no al revés."),
    pEmpty(140),

    h2("10.11 Momentos de Fogata — Pausas Cortas entre Zonas"),
    p("Cuatro preguntas breves, una después de cada escama elemental, pensadas para mesas donde el roleplay extenso todavía no es cómodo. No son ejercicios de actuación — responder en una sola frase está perfectamente bien, y nadie está obligado a profundizar. La meta es la pausa y la conexión entre sesiones, no la performance."),
    pEmpty(80),
    infoTable([
      ["Momento","Cuándo usarla","Pregunta"],
      ["1 — Después de Cuerda-Floja (Amarilla)","Al cerrar la zona, antes de viajar a la siguiente","¿Cuál es el recuerdo más feliz que tienen de antes de empezar todo esto?"],
      ["2 — Después del Pantano (Azul)","Al cerrar la zona, antes de viajar a la siguiente","Si pudieran decirle una cosa a alguien que ya no está, ¿qué dirían?"],
      ["3 — Después de Hotenow (Roja)","Al cerrar la zona, antes de viajar a la siguiente","¿Cuál fue el momento más satisfactorio de toda la aventura hasta ahora?"],
      ["4 — Después del Bosque (Verde)","Al cerrar la zona, antes de viajar a la siguiente","¿Qué harían con un día completamente tranquilo, sin nada que salvar?"],
    ], 2400, 2800, 2000, 4560),
    pEmpty(80),
    noteBox("CÓMO USARLAS BIEN","Podés dejar que respondan como ellos mismos o como sus PJs — lo que sea más cómodo para la mesa. No hay respuesta incorrecta. Si alguien no quiere responder, no pasa nada — el valor está en el ofrecimiento, no en la obligación.","FFF8E7",C.goldDeep),
    pageBreak(),
  ];
}
module.exports = { cap10 };