const { p, pEmpty, h1, h2, h3, bullet, numBullet, infoTable, noteBox, secretBox, loreBox, voiceBox, warningBox, cdBox, xpBox, pageBreak, npcBlock, C } = require('./helpers');

function cap12() {
  return [
    h1("12. AP\u00c9NDICE SECRETO \u2014 El Titiritero (Solo para el DM)"),
    warningBox("ESTE CAP\u00cdTULO NO ES PARA LA MESA. Es la verdad completa detr\u00e1s de la verdad de Mnem\u00f3s \u2014 una capa que la party NUNCA deber\u00eda terminar de armar en esta campa\u00f1a. Est\u00e1 pensado para que VOS, como DM, sepas exactamente qu\u00e9 hay detr\u00e1s de cada pista suelta, y para que tengas material listo para una campa\u00f1a futura si tu mesa quiere seguir jugando en este mundo. Ninguna secci\u00f3n de este cap\u00edtulo se lee en voz alta ni se resume a los jugadores, ni siquiera al final de la campa\u00f1a. Si alg\u00fan jugador conecta los puntos por su cuenta, dejalo \u2014 pero no lo confirmes nunca de forma expl\u00edcita en esta campa\u00f1a."),
    pEmpty(140),

    h2("12.1 Qui\u00e9n es \u2014 La Verdad Completa"),
    infoTable([
      ["Campo","Detalle"],
      ["Nombre p\u00fablico (Neverwinter, hoy)","Lord Cassian Veil, Magistrado del Consejo de Neverwinter. Figura respetada, de mediana edad aparente (~50), conocido por su elocuencia y su 'amor genuino' por el orden de la ciudad"],
      ["Nombre verdadero (300+ a\u00f1os atr\u00e1s)","Ozyr Thane, erudito y consejero menor de una corte ya olvidada, en la \u00e9poca previa a la fundaci\u00f3n de varias ciudades actuales de la Costa de la Espada"],
      ["Naturaleza","Lich. Muri\u00f3 (ritualmente, por elecci\u00f3n) hace poco m\u00e1s de tres siglos para escapar de la mortalidad y seguir 'tejiendo' sin la presi\u00f3n del tiempo. Su filacteria est\u00e1 oculta en su pocket dimension (secci\u00f3n 12.3)"],
      ["Motivaci\u00f3n real","No busca eliminar el sufrimiento (a diferencia de Mnem\u00f3s). Busca CONTROL \u2014 un mundo donde las emociones de las masas sean previsibles, manejables, y por lo tanto gobernables. El sufrimiento, la euforia, el miedo: todos son palancas pol\u00edticas si se saben operar. Lo que Mnem\u00f3s ve como una enfermedad a curar, Ozyr lo ve como una maquinaria a operar"],
      ["Por qu\u00e9 Neverwinter","Es una ciudad con suficiente poder, comercio y poblaci\u00f3n para que controlarla valga el esfuerzo, y suficiente caos pol\u00edtico natural para que un magistrado paciente pueda acumular influencia sin levantar sospechas durante generaciones (cambiando de identidad p\u00fablica cada 60-80 a\u00f1os, siempre como 'pariente lejano' o 'sucesor' de s\u00ed mismo)"],
    ]),
    pEmpty(140),

    h2("12.2 La Siembra \u2014 C\u00f3mo Cre\u00f3 (sin saberlo) a Mnem\u00f3s"),
    p("Hace poco m\u00e1s de trescientos a\u00f1os, Ozyr Thane \u2014ya entonces alguien que entend\u00eda el valor pol\u00edtico del control emocional\u2014 conoci\u00f3 a un joven archivista de una corte vecina: un hombre brillante, ya entonces obsesionado con catalogar el sufrimiento humano, que pasaba sus noches leyendo cr\u00f3nicas de guerras y duelos sin encontrar nunca una raz\u00f3n que las justificara. Ese hombre, mucho despu\u00e9s, se convertir\u00eda en Mnem\u00f3s."),
    pEmpty(80),
    voiceBox("\"Ozyr no le dio una orden. Le dio una pregunta, en una conversaci\u00f3n que ninguno de los dos recordar\u00eda como decisiva. 'Document\u00e1s el dolor como si fuera inevitable,' le dijo. 'Pero, \u00bfno es solo una falla de dise\u00f1o? Si pudieras encontrar el origen \u2014 el mecanismo exacto que produce el sufrimiento \u2014 \u00bfno ser\u00eda tu deber corregirlo, en lugar de solo registrarlo?' Mnem\u00f3s (entonces sin ese nombre) no respondi\u00f3 esa noche. Pas\u00f3 los siguientes ciento cincuenta a\u00f1os encontrando la respuesta por su cuenta.\""),
    pEmpty(80),
    secretBox("LA CLAVE DE SU PACIENCIA: Ozyr no necesitaba que el plan de Mnem\u00f3s funcionara. Cualquier resultado le serv\u00eda. Si Mnem\u00f3s lograba vaciar a un Guardi\u00e1n, Ozyr obten\u00eda un mundo con una regi\u00f3n emocionalmente moldeable \u2014 terreno f\u00e9rtil para su propio control. Si Mnem\u00f3s fallaba o era detenido (como ahora, por la party), Ozyr no pierde nada: simplemente observa qu\u00e9 hace una regi\u00f3n DESPU\u00c9S de que su Guardi\u00e1n fue casi vaciado y luego restaurado \u2014 gente agradecida, exhausta, hambrienta de estabilidad. Esa gente tambi\u00e9n es f\u00e1cil de gobernar, solo que de otra manera. Para Ozyr, Mnem\u00f3s siempre fue un experimento de largo plazo con dos resultados aceptables, nunca un plan con un solo final necesario."),
    pEmpty(80),
    p("Ozyr y Mnem\u00f3s no se han hablado en m\u00e1s de dos siglos. Mnem\u00f3s no sabe que Ozyr sigue existiendo, y mucho menos que sigue vivo (o no-muerto) en Neverwinter mismo, a d\u00edas de viaje del Plano del Archivo. Si en una futura campa\u00f1a el grupo le menciona a Mnem\u00f3s el nombre 'Ozyr Thane', la reacci\u00f3n de Mnem\u00f3s (si sobrevivi\u00f3 al Final B o C) ser\u00eda de genuina sorpresa \u2014 y despu\u00e9s, algo parecido a la ira que nunca permiti\u00f3 sentir."),
    pEmpty(140),

    h2("12.3 El Telar \u2014 Su Sede Oculta (Pocket Dimension)"),
    p("Un espacio fuera del tiempo, an\u00e1logo en construcci\u00f3n al Plano del Archivo de Mnem\u00f3s (mismo tipo de magia de 'umbral antiguo'), pero con un prop\u00f3sito y una est\u00e9tica opuestos."),
    pEmpty(80),
    infoTable([
      ["Campo","Detalle"],
      ["Nombre","El Telar"],
      ["C\u00f3mo se accede","A trav\u00e9s de un espejo sin reflejo guardado en la c\u00e1mara privada de Lord Veil, en su mansi\u00f3n del Distrito Alto de Neverwinter. Requiere una palabra de mando que solo \u00e9l conoce y un sacrificio simb\u00f3lico (una gota de sangre de alguien con poder pol\u00edtico real \u2014 ir\u00f3nicamente, esto significa que solo alguien influyente podr\u00eda, en teor\u00eda, activarlo sin \u00e9l, lo cual es justo el tipo de contingencia que a Ozyr le entretiene dejar abierta)"],
      ["Descripci\u00f3n","Una sala circular, sin paredes visibles, donde miles de hilos de luz tenue se extienden en todas direcciones hacia la oscuridad \u2014 cada hilo conectado a una persona, instituci\u00f3n o evento de la Costa de la Espada que Ozyr observa o influye. Caminar entre los hilos sin tocarlos requiere cuidado; tocarlos accidentalmente revela visiones fragmentadas de la vida de esa persona"],
      ["Qu\u00e9 hay en el centro","Una mesa de mapas vivos: un modelo en miniatura de Neverwinter (y, m\u00e1s atr\u00e1s, de toda la Costa de la Espada) que se actualiza solo, mostrando movimientos de poder, comercio y opini\u00f3n p\u00fablica en tiempo real, como si fuera un tablero de juego de estrategia"],
      ["D\u00f3nde est\u00e1 la filacteria","Oculta en un libro en blanco sobre la mesa de mapas \u2014 un volumen que parece vac\u00edo a quien lo abre, salvo que su naturaleza real se revela con Detectar Magia o un conjuro de identificaci\u00f3n de nivel alto. Destruirlo (sin saber exactamente qu\u00e9 es) probablemente matar\u00eda a Ozyr de forma permanente \u2014 material excelente para el cl\u00edmax de una campa\u00f1a futura, NO de esta"],
    ]),
    pEmpty(140),

    h2("12.4 Documentos Ocultos \u2014 Pistas F\u00edsicas en el Mundo"),
    p("Estos son los \u00fanicos rastros documentales de Ozyr Thane que existen en el mundo material. Ninguno menciona a Lord Veil. Son para que el DM los use como hallazgos opcionales, de muy baja probabilidad de encontrarse sin buscarlos a prop\u00f3sito (no deber\u00edan aparecer por accidente)."),
    pEmpty(80),
    infoTable([
      ["Documento","D\u00f3nde est\u00e1","Qu\u00e9 dice"],
      ["Cr\u00f3nica de la Corte Desvanecida","Archivo privado de la Biblioteca Real de Neverwinter, secci\u00f3n de historia antigua (acceso restringido, requiere permiso del Magistrado a cargo \u2014 ir\u00f3nicamente, Lord Veil mismo, quien lo concede sin sospecha porque 'nadie nunca lo pide')","Menciona a un consejero llamado Ozyr Thane, c\u00e9lebre por su elocuencia, que 'desapareci\u00f3 de los registros' hace 312 a\u00f1os, presuntamente muerto de causas naturales. No hay tumba ni cuerpo documentado"],
      ["El Tratado del Orden Sereno","Un libro raro, casi ilegible, en la colecci\u00f3n privada de un anticuario de Neverwinter (puede ser el mismo Dax del Taller del Recuerdo, secci\u00f3n 9.1, sin que \u00e9l sepa su valor real)","Atribuido a 'O.T.', un ensayo filos\u00f3fico sobre c\u00f3mo 'las emociones colectivas de un pueblo son el verdadero trono \u2014 quien las dirige, gobierna sin necesidad de corona'. Fascinante y perturbador si se lee con atenci\u00f3n, pero sin nombre completo"],
      ["Carta sin remitente","Entre los pergaminos de Goro en el Pantano (secci\u00f3n 5, MS-2B) hay UNA p\u00e1gina que no pertenece al resto \u2014 qued\u00f3 ah\u00ed por azar, de un viajero anterior","Fragmento de una carta personal, sin firma, que dice: 'el archivista de quien habl\u00e1s bien podr\u00eda ser el chico de la corte vieja, el que sol\u00eda hacerme tantas preguntas sobre el dolor. Si es \u00e9l, dale mis saludos \u2014 o no. Hace mucho que dej\u00e9 de pensar en si eso importa.' (Esta es la \u00fanica pista que casi-conecta a Ozyr con Mnem\u00f3s directamente; es deliberadamente ambigua y f\u00e1cil de pasar por alto)"],
    ], 2400, 2800, 4160),
    pEmpty(140),

    h2("12.5 Sus Manos en Todo \u2014 Red de Influencia en Neverwinter"),
    p("Como pediste: un buen titiritero tiene presencia en cada nivel posible de influencia o ganancia, grande o peque\u00f1a. Esta tabla es para tu referencia \u2014 usala para improvisar reacciones de NPCs o para sembrar m\u00e1s pistas si tu mesa quiere profundizar."),
    pEmpty(80),
    infoTable([
      ["Nivel de la ciudad","C\u00f3mo Ozyr tiene una mano ah\u00ed","Visible para la party como"],
      ["El Consejo de la Ciudad","Es uno de sus magistrados, con voto real en pol\u00edtica \u2014 control directo y legal","Lord Veil, magistrado: alguien con quien podr\u00edan cruzarse pidiendo favores burocr\u00e1ticos"],
      ["Los Sin-Color (la secta)","Financia el movimiento a trav\u00e9s de intermediarios. Tera cree que responde a un 'benefactor an\u00f3nimo preocupado por el bienestar de la ciudad' \u2014 nunca lo conoci\u00f3 en persona","Donaciones misteriosas, suministros que aparecen sin explicaci\u00f3n, un mensajero que nunca da nombre"],
      ["El Gremio de Mercaderes","Posee, a trav\u00e9s de testaferros, participaci\u00f3n mayoritaria en 3 de los 5 gremios principales \u2014 control econ\u00f3mico silencioso","Precios curiosamente estables en tiempos de crisis; cualquier intento de especulaci\u00f3n 'misteriosamente' fracasa"],
      ["La Guardia de la Ciudad","Un capit\u00e1n de la guardia (no corrupto, simplemente leal y bien pagado) reporta movimientos inusuales directamente a Lord Veil 'por seguridad de la ciudad' \u2014 vigilancia legal y discreta","Si la party hace algo notorio en Neverwinter, es razonable que en 1-2 sesiones un guardia 'casualmente' les pregunte sobre ello"],
      ["El Templo principal de la ciudad","Financia generosamente las reparaciones y la caridad del templo \u2014 gratitud genuina del clero hacia \u00e9l, sin que sepan m\u00e1s","Un sacerdote menciona con cari\u00f1o 'la generosidad de Lord Veil' si la party busca ayuda religiosa en la ciudad"],
      ["El bajo mundo / informaci\u00f3n","Mantiene una red de informantes de bajo perfil (mendigos, taberneros, mensajeros) pagados en monedas, no en lealtad \u2014 la red m\u00e1s dif\u00edcil de rastrear porque nadie en ella sabe para qui\u00e9n trabaja realmente, solo reciben \u00f3rdenes de un intermediario an\u00f3nimo","Si la party investiga demasiado en Neverwinter, podr\u00eda notar (Percepci\u00f3n CD 18, casi imposible de lograr sin buscarlo a prop\u00f3sito) que alguien parece saber de sus movimientos antes de que los cuenten en voz alta"],
      ["Vex (el escriba de 9.1)","NO trabaja para Ozyr \u2014 esto es deliberado. Vex es un agente de Mnem\u00f3s, no del Titiritero. Mantenelos separados: la party podr\u00eda asumir que toda manipulaci\u00f3n en Neverwinter viene de la misma fuente, y es importante que NO sea as\u00ed. Son dos jugadores distintos en el mismo tablero, sin saber del otro"],
    ], 2200, 3700, 3460),
    pEmpty(140),

    h2("12.6 Las 5-6 Pistas en la Campaña Principal — Mapa de Ubicaciones"),
    p("Esto resume dónde están sembradas las pistas visibles para la party (desarrolladas en detalle dentro de los capítulos correspondientes). Ninguna pista, vista de forma aislada, debería permitir a la party identificar a Lord Veil como sospechoso de nada — el objetivo es que terminen la campaña con la sensación de '¿hay algo más?' sin una respuesta clara."),
    pEmpty(80),
    warningBox("ESCALADO DE CD — A pedido explícito: cuanto más significativa o cercana a la verdad es una pista, más difícil debe ser notarla u obtenerla. Las pistas 1 y 2 son casi ambientales (CD baja, fáciles de captar de pasada). La pista 4 es la única que casi conecta a Ozyr con Mnemós directamente, así que tiene la CD más alta de las 'normales'. La pista 6 es deliberadamente la más dura de todas — está pensada para que la mayoría de las mesas NUNCA la consigan sin buscarla a propósito."),
    pEmpty(80),
    infoTable([
      ["#","Ubicación en el documento","CD para notarla / obtenerla","Qué ve la party (sin saber su importancia real)"],
      ["1","Cap. 1, llegada a Neverwinter (descripción de la ciudad)","Ninguna — es ambiental, se la das narrando la ciudad","Un discurso callejero de un orador menor, citando (sin saberlo) ideas del Tratado del Orden Sereno casi palabra por palabra — 'la verdadera paz es el orden, y el orden empieza por saber qué sentir'"],
      ["2","Sección 9.1, Taller del Recuerdo","Percepción CD 10 (charla casual con Dax, casi gratis)","Dax el anticuario menciona de paso que tiene 'un libro viejo e ilegible que nadie quiere comprar' (el Tratado) — completamente opcional, la party puede ignorarlo"],
      ["3","Sección 9.2, Los Sin-Color","Persuasión CD 17 con Tera (más alta que lo normal — ni ella entiende del todo lo que sabe)","Tera menciona que el movimiento recibe ayuda de 'alguien con mucho poder que prefiere no dar la cara'"],
      ["4","Monte Hotenow, MS-2B (pergaminos de Goro)","Investigación CD 16 para notar que esa página no pertenece al resto del lote de Goro","La carta sin remitente (sección 12.4) — la pista más cercana a una conexión directa, y la más fácil de pasar por alto entre tanto otro papel"],
      ["5","Neverwinter, cualquier visita posterior a la mitad de la campaña","Ninguna — Logos o un guardia lo comentan de forma espontánea, no requiere búsqueda","Un guardia de la ciudad comenta, con total naturalidad, que 'el Magistrado Veil pidió que le avisen' sobre forasteros notables — sin amenaza, sin sospecha, solo burocracia. Suena inocente. Lo es, en la superficie"],
      ["6 (opcional, la más dura)","Biblioteca Real de Neverwinter, si buscan historia antigua para CUALQUIER otro motivo","Investigación CD 19 en el archivo restringido, Y deben haber pedido permiso de acceso primero (Persuasión CD 15 con el funcionario de turno, que en algún momento podría ser Lord Veil mismo sin que lo sepan)","Pueden toparse con la Crónica de la Corte Desvanecida (sección 12.4) por casualidad. Logos, si le preguntan por el nombre Ozyr Thane, responde con honestidad y sin alarma: 'Sin coincidencias en mi base de datos.'"],
    ], 700, 2800, 2000, 3960),
    pEmpty(80),
    secretBox("REGLA DE ORO DE ESTA CAPA: ninguna pista debe sentirse como una pista de villano. Cada una, vista sola, es folklore, burocracia o cotilleo de ciudad. El efecto deseado es acumulativo y subconsciente — si releen sus notas de campaña dentro de un año, ahí quizás vean el patrón. Durante el juego, no."),
    pEmpty(140),

    h2("12.7 C\u00f3mo las Acciones de la Party SIEMPRE le Sirven a Ozyr"),
    p("Como pediste: ninguna decisi\u00f3n de la party deber\u00eda poder arruinar el plan de largo plazo de Ozyr, porque su plan no depende de un resultado espec\u00edfico de la campa\u00f1a. Esta tabla cubre los escenarios principales."),
    pEmpty(80),
    infoTable([
      ["Lo que hace la party","Por qu\u00e9 a Ozyr no le importa \u2014 o incluso le sirve"],
      ["Restauran a Chromatus completamente (cualquier final)","Una ciudad/región agradecida, exhausta y emocionalmente abierta tras la crisis es terreno fértil para un líder que ofrece estabilidad. Ozyr gana una nueva narrativa: 'miren cómo, incluso en la ciudad más golpeada, el orden ayudó a sanar' — y se atribuye parte del crédito en discursos futuros, sin haber movido un dedo"],
      ["Destruyen a Mnem\u00f3s (Final A)","Pierde a su 'experimento' m\u00e1s antiguo, pero no pierde nada propio \u2014 nunca dependi\u00f3 de Mnem\u00f3s para sus planes inmediatos en Neverwinter. Si acaso, gana morbo y atenci\u00f3n p\u00fablica que puede aprovechar narrativamente ('una crisis as\u00ed nunca debe repetirse, por eso necesitamos m\u00e1s control')"],
      ["Convencen a Mnem\u00f3s (Final B/C)","Igual de indiferente. Mnem\u00f3s con o sin redenci\u00f3n no afecta el Telar ni la red en Neverwinter. En el peor caso para Ozyr, Mnem\u00f3s (si sobrevive) podr\u00eda alg\u00fan d\u00eda recordar la conversaci\u00f3n de hace 300 a\u00f1os \u2014 semilla pura para una secuela, no una amenaza actual"],
      ["Resuelven el caso de Los Sin-Color (cualquier opci\u00f3n de 9.2)","Si los disuelven o convencen: Ozyr pierde una herramienta menor, pero tiene otras (secci\u00f3n 12.5) y ya extrajo el valor pol\u00edtico que necesitaba de la crisis inicial. Si los combaten: lo mismo, m\u00e1s reputaci\u00f3n para la party que a \u00e9l no le afecta en nada"],
      ["Investigan a fondo el poder pol\u00edtico de Neverwinter","Mientras no entren al Telar ni encuentren la filacteria, cualquier cosa que descubran (la Cr\u00f3nica, el Tratado, la carta) es ambigua e inconclusa por dise\u00f1o \u2014 nada de lo que sucede en ESTA campa\u00f1a forzar\u00eda una confrontaci\u00f3n directa con \u00e9l"],
      ["Terminan la campa\u00f1a sin haber notado nada de esto","Resultado perfectamente v\u00e1lido y quiz\u00e1s el m\u00e1s realista \u2014 la mayor\u00eda de las pistas son opcionales y de baja probabilidad. El gancho queda intacto para una secuela"],
    ], 3400, 5960),
    pEmpty(140),

    h2("12.8 Misterios sin Resolver — Lore de Fondo del Mundo"),
    p("Esta sección cubre dos misterios atmosféricos que NUNCA se resuelven dentro de esta campaña. No están atados a Ozyr ni a Mnemós directamente — son lore de fondo sobre el Guardián de la Esperanza (sección 9.4) y sobre el propio Chromatus, pensados para dar al mundo la sensación de ser más grande que la historia que se está contando. Ninguno de los dos necesita explicarse a la mesa ni resolverse — de hecho, el efecto deseado depende de que NUNCA se resuelvan en esta campaña."),
    pEmpty(80),

    h3("12.8.1 — El Día Sin Nombre (atado al Guardián de la Esperanza)"),
    p("Hace mucho más de 300 años —antes de Mnemós, antes incluso del primer experimento documentado de Ozyr con los otros guardianes antiguos— hubo un día específico en el que el Guardián de la Esperanza fue vaciado (ver sección 9.4 para el resto de su historia). No fue un evento silencioso en su momento: probablemente tuvo testigos, generó reacciones, fue noticia en su época."),
    pEmpty(80),
    secretBox("POR QUÉ NO SE SIENTE HOY, SOLO SE REGISTRA MAL: la esperanza no es solo 'querer que el futuro sea mejor' — es también el mecanismo que permite que una sociedad narre su propia historia hacia adelante, que diga 'esto importó, por eso lo recordamos así'. En el instante exacto en que ese mecanismo desapareció del mundo, la capacidad colectiva de integrar ESE día específico a una narrativa coherente se rompió con él — como sacar una página de un libro pero dejando el resto del texto fluyendo alrededor del hueco. La esperanza volvió (parcialmente, de formas distintas) a las generaciones siguientes — por eso nadie HOY siente que falte algo en su vida diaria. Lo que quedó dañado para siempre es específicamente el registro histórico de ESE día, como una herida vieja que cicatrizó mal: el cuerpo funciona, pero esa zona nunca volvió a sanar del todo. Esto es deliberadamente DISTINTO de pedirle a Chromatus que lo explique — él no tiene este recuerdo, no es su historia, es de antes de su propia existencia como guardián."),
    pEmpty(80),
    p("Cómo se manifiesta — tres pistas sembradas en la campaña principal, ninguna con un lugar donde 'resolverse':"),
    pEmpty(60),
    infoTable([
      ["#","Dónde está sembrada","CD para notarla","Qué se observa"],
      ["1","Cualquier conversación con un erudito o anciano de pueblo, en cualquier zona (a tu elección de cuál y cuándo)","Ninguna — es ambiental, una frase de color que soltás vos como DM sin que la mesa tenga que buscarla","El NPC menciona una tradición familiar rara sin origen conocido: 'mi abuela nunca contaba historias de esa época, decía que esa parte no se cuenta bien.' Ni el NPC ni nadie sabe por qué existe la costumbre"],
      ["2","Biblioteca Real de Neverwinter, si el grupo la visita por cualquier motivo (ya está establecida como lugar de investigación en el Cap. 12, secciones 12.4 y 12.6)","Investigación CD 14 para notar que un texto antiguo se corta de forma rara","Un documento histórico describe 'los días que siguieron a [un evento importante de tu lore de fondo]' y la frase se interrumpe sin punto, sin tachadura, sin daño visible — como si el escriba original no hubiera podido seguir escribiendo sobre ese día específico, y retomara al día siguiente sin ningún comentario sobre la interrupción"],
      ["3 (la más difícil, la única que requiere cruzar datos)","Dos eruditos DISTINTOS, en DOS zonas o momentos distintos de la campaña, mencionando el mismo evento histórico de tu lore de fondo","Investigación o Historia CD 17 — y solo si el grupo efectivamente recuerda y cruza ambas menciones, posiblemente sesiones después una de la otra","Las fechas o descripciones del evento NO coinciden del todo entre ambos eruditos, y ninguno de los dos lo nota como problema. Si el grupo les señala la discrepancia, ambos responden con genuina incertidumbre ('puede ser, la verdad no estoy seguro de la fecha exacta') y siguen con su vida — nunca hay confirmación de que algo esté mal, solo la sensación de que algo no cierra"],
    ], 800, 2800, 2000, 4760),
    pEmpty(80),
    secretBox("Ninguna de estas tres pistas tiene una 'resolución' en esta campaña. Si tu mesa las junta y empieza a especular, dejalas especular — no confirmes ni niegues nada. El gancho queda perfecto para una campaña futura centrada en el Guardián de la Esperanza (sección 12.10)."),
    pEmpty(140),

    h3("12.8.2 — El Sueño Compartido (eco accidental de Chromatus)"),
    p("Cuando Mnemós vació a Chromatus, hubo un instante —antes de que la Niebla Gris terminara de extenderse— donde el dolor del Guardián-prisma, al ser multidimensional (sostiene los CINCO Sentires a la vez), se filtró como una imagen onírica esparcida al azar entre mentes sensibles a la magia en toda la región."),
    pEmpty(80),
    secretBox("POR QUÉ CHROMATUS NO PUEDE EXPLICARLO (aunque sí podría explicar otras cosas, a diferencia del Día Sin Nombre): no es Chromatus 'enviando' el sueño a propósito — es un eco accidental, como una onda de radio que nadie sintonizó a propósito. Literalmente no lo recuerda con claridad, porque ocurrió en el instante de menor consciencia de toda su existencia: el momento exacto de su propio vaciado. Si el grupo le describe el sueño directamente, su única reacción posible y genuina es desconcierto real: 'No sé qué es eso. Pero algo en mí... duele al escucharlo.' Esto preserva el misterio sin que Chromatus mienta ni evada — simplemente está fuera de su propio acceso."),
    pEmpty(80),
    p("La imagen del sueño (siempre la misma, fragmentada): una puerta que no es una puerta —más bien un hueco con forma de puerta, en medio de un espacio sin paredes— y una voz, en ningún idioma reconocible, contando algo al revés: números o palabras, descendiendo hacia algo que nunca se nombra."),
    pEmpty(80),
    infoTable([
      ["#","Dónde está sembrada","CD para notarla","Qué se observa"],
      ["1","Un NPC menor de cualquier zona (sugerido: alguien del Pantano o de Cuerda-Floja, cerca del momento en que llegó la Niebla por primera vez)","Ninguna — se entrega como color narrativo si el grupo pregunta a un NPC '¿qué hacías cuando llegó la Niebla?' o similar","El NPC menciona, casi como anécdota sin importancia, haber tenido 'un sueño rarísimo esa noche' — si el grupo pide que lo describa, da la imagen completa (la puerta-hueco, la voz al revés)"],
      ["2 (la coincidencia)","Un SEGUNDO NPC, en una zona distinta, mencionando un sueño similar de forma totalmente independiente","Percepción o Perspicacia CD 15 para notar que la descripción coincide casi palabra por palabra con la del primer NPC","Mismos detalles centrales: la puerta-hueco, la voz contando al revés. Ninguno de los NPCs sabe del otro"],
      ["3 (opcional, para un PJ)","Cualquier PJ puede tener el mismo sueño en algún momento de descanso largo (sugerido: después de una escama elemental, nunca antes de la primera)","No aplica — es una experiencia personal del PJ","El jugador vive la misma imagen en primera persona. Es una experiencia rara y personal, no una pista de trama — no necesita compartirla con el grupo"],
    ], 800, 2800, 2000, 4760),
    pEmpty(80),
    secretBox("Igual que el Día Sin Nombre, este misterio no tiene resolución en esta campaña. Funciona mejor si se siembra con calma, separado en el tiempo (no las tres pistas en la misma sesión), y si vos como DM nunca confirmás ni negás ninguna interpretación que la mesa proponga."),
    pEmpty(140),

    h2("12.9 Iarno, el Experimento Recurrente"),
    p("Iarno Albrek (el mago menor de la Araña Negra en Phandelver, derrotado por este mismo grupo) es la pieza más personal del Titiritero — y la única donde el villano-titiritero y un villano que la party ya conoce se cruzan directamente."),
    pEmpty(80),

    h3("12.9.1 — El Trato: Qué Quiere Ganar Iarno"),
    p("Iarno murió sabiendo que perdió — no solo el combate final, sino toda su historia con la Araña Negra: siempre fue el segundo, el que ejecutaba pero nunca mandaba, el que se escapó una y otra vez hasta que finalmente cayó. Lo que más le quedó de esa derrota no fue rencor contra la party en particular — fue la humillación de haber sido siempre el peón de alguien más grande."),
    pEmpty(80),
    voiceBox("\"En el instante exacto en que el alma de Iarno se separaba del cuerpo —ese segundo entre estar vivo y no estarlo— algo lo atrapó antes de que se fuera del todo. Una voz, paciente, que no sonaba apurada ni desesperada como las voces de los nigromantes baratos que conocía. 'Podés volver,' le dijo Ozyr Thane, sin presentarse, sin pedir nada todavía. 'No como sirviente de otro. Esta vez, al mando. Tu propia revancha, sin nadie por encima dándote órdenes. Solo te pido una cosa simple: encargate de la molestia que te mató. El resto es tuyo.'\""),
    pEmpty(80),
    secretBox("LA IRONÍA QUE IARNO NUNCA VE: Ozyr no le importa en absoluto si Iarno gana o pierde contra la party — coherente con todo lo establecido en la sección 12.7. Lo que Ozyr SÍ obtiene, sin que Iarno lo sepa, es un sujeto de prueba gratuito y desesperado por demostrar algo, perfecto para perfeccionar su magia de resurrección. Cada fallo de Iarno es información valiosa. Iarno interpreta cada nueva resurrección como que Ozyr 'cree en él' y le da más poder por mérito. En realidad es un científico ajustando variables en su experimento más barato."),
    pEmpty(140),

    h3("12.9.2 — El Precio de Cada Resurrección: la Mutación hacia Lich"),
    p("Cada vez que Ozyr lo trae de vuelta, el proceso no es gratis para Iarno. Pierde algo emocional Y cambia algo físico — un eco, del lado del villano menor, del mismo tema que recorre toda la campaña: nadie obtiene poder vaciándose de algo sin que eso cueste."),
    pEmpty(80),
    infoTable([
      ["Aparición","Pierde (emocional)","Cambia (físico)","Resultado visual"],
      ["1ª","El miedo — ya no puede sentir terror, ni ante su propia muerte","Piel más pálida de lo normal, venas oscuras apenas visibles bajo la piel, voz un tono más baja y hueca","Casi el Iarno que conocían, pero apagado — algo no cierra del todo"],
      ["2ª","La empatía — deja de poder sentir lástima por nadie, ni por sí mismo","Pierde el pelo, los ojos se hunden y oscurecen, las manos empiezan a alargarse levemente","Visiblemente mal — la mesa debería empezar a sospechar que hay un patrón"],
      ["3ª","Lo último que le queda — posiblemente su propio nombre, o la capacidad de disfrutar ganar","Transformación casi completa hacia lich: filacteria visible, rasgos de no-muerto innegables","Lich funcional, o a un paso de serlo — apenas queda Iarno reconocible"],
    ], 1600, 3200, 3200, 2360),
    pEmpty(80),
    secretBox("EL GANCHO EMOCIONAL: cada vez que la party 'gana' matándolo, en realidad lo está ayudando a completar su transformación en algo peor. Es una victoria que se siente como derrota a medias — dejá que esto se sienta en la narración de cada combate, sin que la mesa necesite que se lo expliques."),
    pEmpty(140),

    h3("12.9.3 — La Clase: Mago/Warlock, y Por Qué Cambia"),
    p("Tu Iarno original era Mago nivel 5. Un trato con una entidad poderosa a cambio de poder es, mecánicamente, la definición de un Warlock — así que la progresión correcta es: Mago/Warlock multiclase en la primera aparición, y Warlock puro en la segunda y tercera."),
    pEmpty(80),
    noteBox("CÓMO JUGAR LA MULTICLASE MAGO/WARLOCK EN MESA","Para la 1ª aparición, usá esta proporción: Mago 5 / Warlock 2 (nivel total 7). Conjuros de Mago: usa la lista que ya tenía como Iarno de Phandelver (4/3/2 espacios de niveles 1/2/3). Conjuros de Warlock: 2 espacios de nivel 1 que se recargan con descanso CORTO — esto lo hace más resistente en combates largos. Invocaciones: dale 'Pacto de la Cadena' narrado como un familiar oscuro (un cuervo sin ojos). No necesitás manejar las reglas completas de multiclase al pie de la letra — alcanza con que tenga ambas fuentes disponibles.","FFF8E7",C.goldDeep),
    pEmpty(80),
    p("Para la 2ª y 3ª aparición, ya es Warlock puro — esto es mecánicamente más simple de manejar en mesa, y narrativamente remarca que cada vez queda menos del mago que conocieron."),
    pEmpty(140),

    h3("12.9.4 — Las Tres Apariciones: Estadísticas Completas"),

    h3("Primera Aparición — El Ritual Interrumpido (nivel de personaje ~7)"),
    p("Esta es la aparición sorpresa. El grupo lo encuentra por casualidad, investigando algo que NO tiene que ver con él — entran a un sótano, una cueva, una cripta olvidada (elegí cualquier ubicación de paso entre las zonas 2 o 3) y lo encuentran a media invocación de un ritual menor, sin capucha. No los esperaba. Reacciona con sorpresa genuina al verlos, y combate."),
    pEmpty(80),
    warningBox("REGLA DE ORO PARA ESTA ESCENA: NO lo nombres como Iarno, NO uses ninguna descripción que coincida con el Iarno de Phandelver. Describilo simplemente como 'un hechicero pálido de mediana edad' — genérico a propósito. Su personalidad también cambió: el Iarno que conocieron era nervioso, servil, se escapaba corriendo. Este es frío, calculador, casi aburrido — el opuesto de carácter, lo cual activamente desvía la sospecha. La revelación de quién es llega DESPUÉS de este combate (ver 12.9.5)."),
    pEmpty(80),
    warningBox("CALIBRACIÓN DE PG: tu party tiene 4 jugadores + 2 golems + posible quimera — hasta 7 ataques por ronda en el peor caso para Iarno. Con eso en mente, sus PG están deliberadamente altos para esta primera aparición (115, no los ~50 que tendría un personaje de nivel 7 estándar). Esto representa que el trato con Ozyr ya lo reforzó más allá de lo normal."),
    pEmpty(80),
    infoTable([
      ["Estadística","Valor"],
      ["Nivel narrativo / CR equivalente","Mago 5 / Warlock 2 — CR efectivo ~8 (ajustado hacia arriba por PG y por la economía de acciones de tu party)"],
      ["PG","115 (14d8+42 aprox. — reforzado por el trato, no PG estándar de nivel 7)"],
      ["CA","14 (armadura de mago + protección residual del pacto)"],
      ["Velocidad","9 m"],
      ["Atributos clave","INT 18 (+4), SAB 12 (+1), CAR 16 (+3), CON 16 (+3)"],
      ["Salvaciones","INT +7, SAB +4, CAR +6, CON +6"],
      ["Resistencia a conjuros","Ventaja en salvaciones contra ser Encantado (residuo temprano del pacto)"],
    ], 2800, 7560),
    pEmpty(80),
    p("Conjuros de Mago (espacios: 4 de nivel 1, 3 de nivel 2, 3 de nivel 3):"),
    pEmpty(60),
    infoTable([
      ["Conjuro","Nivel","Efecto completo"],
      ["Misil Mágico","1","Acción. 3 dardos de fuerza, 1d4+1 cada uno (impacto automático). Total esperado: ~10-11 de daño"],
      ["Rayo de Escarcha","1","Acción. +7 al impacto (alcance 18 m), 3d8 frío, velocidad del objetivo reducida a la mitad hasta el final de su próximo turno"],
      ["Niebla Oscurecedora","1","Acción. Nube de niebla densa de 6 m de radio que bloquea visión — usalo para escapar o reposicionarse"],
      ["Telaraña","2","Acción, CD 15 Destreza. Área de 6 m. Falla: Apresado. Excelente para inmovilizar al golem o a un PJ clave antes de huir"],
      ["Nube Pestilente","2","Acción, CD 15 Constitución. Esfera de 3 m de radio, gas venenoso. Falla: Envenenado (Desventaja en ataques y habilidades)"],
      ["Bola de Fuego","3","Acción, CD 16 Destreza. Esfera de 6 m de radio a 45 m. 8d6 fuego (mitad con éxito). Su mejor pieza de daño en área"],
      ["Contrahechizo","3","Reacción. Anula automáticamente conjuros de nivel 3 o menos. Útil contra curaciones o buffs del grupo"],
    ], 2800, 1200, 5360),
    pEmpty(80),
    p("Conjuros de Warlock (2 espacios de nivel 1, se recargan con descanso CORTO):"),
    pEmpty(60),
    infoTable([
      ["Conjuro","Efecto completo"],
      ["Maldición de Agonía","Acción, CD 16 Sabiduría. Un objetivo a 18 m. Falla: 3d10 psíquico y queda Aturdido hasta el final de su próximo turno. Éxito: mitad de daño, sin aturdimiento. Su mejor arma de un solo objetivo"],
      ["Garra de Espino (truco, ilimitado)","Acción, +7 al impacto, alcance 9 m, 2d8 necrótico. Su ataque básico cuando no quiere gastar espacios de conjuro"],
    ], 3200, 7160),
    pEmpty(80),
    infoTable([
      ["Rasgo / Invocación","Efecto"],
      ["Pacto de la Cadena","Un familiar oscuro (un cuervo sin ojos) lo acompaña: CA 13, 1 PG, ataca con +5 al impacto por 1d4 necrótico, o puede ver en radio de 30 m. Aparece sin explicación — primera pista de identidad (sección 12.9.5)"],
      ["Comportamiento en combate","Frío y calculador, NADA parecido al pánico del Iarno original. Abre con Telaraña o Niebla Oscurecedora para controlar el campo, no con daño directo. Si el combate va claramente perdido (menos de 25 PG), usa Niebla Oscurecedora para escapar — no corre como hacía antes"],
    ], 2800, 7560),
    pEmpty(140),

    h3("Segunda Aparición — La Revelación Completa (nivel de personaje ~10-11)"),
    p("Ya es Warlock puro. Para este punto, el patrón de muerte-y-regreso debería empezar a notarse para la mesa. UBICACIÓN SEMBRADA: la frontera con el Plano de las Hadas en el Bosque de Neverwinter (Cap. 7, sección MS-4B) — ya tiene la nota de DM lista para usar en ese punto exacto del documento."),
    pEmpty(80),
    infoTable([
      ["Estadística","Valor"],
      ["Nivel narrativo / CR equivalente","Warlock puro nivel 9 — CR efectivo ~10"],
      ["PG","165 (sube notablemente de la primera aparición — el trato lo refuerza con cada regreso)"],
      ["CA","16 (la mutación hacia no-muerto empieza a endurecer su piel; ya no necesita armadura de tela)"],
      ["Velocidad","9 m"],
      ["Atributos clave","CAR 20 (+5), CON 18 (+4), SAB 14 (+2)"],
      ["Salvaciones","CAR +9, CON +8, SAB +6"],
      ["Resistencias","Necrótico (su propio cuerpo empieza a no-pertenecer del todo al mundo de los vivos)"],
      ["Inmunidades","Asustado (perdió la empatía y el miedo desde la 1ª resurrección)"],
    ], 2800, 7560),
    pEmpty(80),
    p("Conjuros de Warlock (4 espacios de nivel 5, se recargan con descanso corto):"),
    pEmpty(60),
    infoTable([
      ["Conjuro","Efecto completo"],
      ["Maldición de Agonía (mejorada)","Acción, CD 19 Sabiduría. Falla: 6d10 psíquico y Aturdido hasta el final de su próximo turno. Éxito: mitad, sin aturdimiento"],
      ["Esfera Gris (versión corrupta de Esfera de Fuego)","Acción, CD 19 Destreza. Esfera de 6 m de radio a 45 m. 10d6 necrótico (en vez de fuego — representa la corrupción de su propia magia). Mitad con éxito"],
      ["Muro de Fuego Oscuro","Acción. Crea un muro de 18 m de largo y 6 m de alto, CD 19 Destreza al atravesarlo: 5d8 necrótico (mitad con éxito). Dura hasta 10 minutos"],
      ["Dominar Persona","Acción, CD 19 Sabiduría. Un humanoide a 18 m. Falla: Encantado por 24 horas. Usalo con moderación — es un efecto fuerte para una mesa con hijos"],
      ["Garra de Espino (truco)","Acción, +9 al impacto, alcance 9 m, 4d8 necrótico (escalado a este nivel)"],
    ], 3200, 7160),
    pEmpty(80),
    infoTable([
      ["Rasgo / Invocación","Efecto"],
      ["Pacto de la Cadena (evolucionado)","El familiar ahora es más grande y agresivo: CA 15, 22 PG, ataca con +7, 2d6 necrótico, vuela 18 m"],
      ["Visión del Pacto","Puede ver a través de la oscuridad mágica y detectar mentiras automáticamente"],
      ["Piel que ya no Siente","Resistencia a daño de veneno — mecánicamente representa lo que perdió en la 1ª resurrección"],
      ["Comportamiento en combate","Más agresivo que la primera vez — ya no controla tanto el campo, ataca con una especie de hambre directa. Si lo derrotan, hace un comentario sobre 'volver a empezar' antes de desaparecer, sin miedo en la voz"],
    ], 2800, 7560),
    pEmpty(140),

    h3("Tercera Aparición (Opcional) — Casi Lich (nivel de personaje ~13-14)"),
    p("La última oportunidad, si tu mesa la quiere usar. UBICACIÓN SEMBRADA: la Colección Antigua dentro del Plano del Archivo (Cap. 9, sección 9.4) — ANTES o DESPUÉS de Mnemós, nunca a la vez. Acá decidís si esta vez muere para siempre, o si queda un hilo suelto deliberado para una campaña futura."),
    pEmpty(80),
    infoTable([
      ["Estadística","Valor"],
      ["Nivel narrativo / CR equivalente","Warlock puro con rasgos de lich incipiente — CR efectivo ~13"],
      ["PG","220 (la mutación final lo refuerza al máximo antes de cruzar del todo a no-muerto completo)"],
      ["CA","18 (armadura natural de no-muerto + magia de protección residual)"],
      ["Velocidad","9 m, vuela 9 m (ya casi no toca el piso, otra señal visual)"],
      ["Atributos clave","CAR 22 (+6), CON 20 (+5), INT 18 (+4)"],
      ["Salvaciones","CAR +11, CON +10, INT +9"],
      ["Resistencias","Contundente, perforante y cortante de armas no mágicas"],
      ["Inmunidades","Veneno, Encantado, Asustado, Agotamiento"],
    ], 2800, 7560),
    pEmpty(80),
    p("Conjuros (6 espacios de nivel 5 entre Warlock y rasgos de lich incipiente, se recargan con descanso corto):"),
    pEmpty(60),
    infoTable([
      ["Conjuro / Acción","Efecto completo"],
      ["Toque Paralizante (rasgo de lich incipiente)","Acción, ataque de toque +12, 4d8 frío necrótico, y CD 19 Constitución o el objetivo queda Paralizado 1 minuto"],
      ["Maldición de Agonía (máxima)","Acción, CD 21 Sabiduría. Falla: 8d10 psíquico + Aturdido hasta el final de su próximo turno. Éxito: mitad, sin aturdimiento"],
      ["Cono de Frío Necrótico","Acción, CD 21 Constitución, cono de 18 m. 10d8 necrótico (mitad con éxito) — su mejor arma de área"],
      ["Dominar Persona","Igual que en la 2ª aparición, CD 21 Sabiduría, 24 horas de duración"],
      ["Garra de Espino (truco)","Acción, +11 al impacto, alcance 9 m, 6d8 necrótico"],
    ], 3200, 7160),
    pEmpty(80),
    infoTable([
      ["Rasgo","Efecto"],
      ["Filacteria visible","Lleva un objeto (sugerido: un anillo, o su viejo libro de conjuros ennegrecido) que es el ancla real de su resurrección. Destruir ESE objeto, no solo matarlo, es la única forma de que esta sea realmente la última vez. Pista: Arcanos CD 18 durante el combate, o Detectar Magia bien usado"],
      ["Regeneración Parcial","Al inicio de su turno, recupera 10 PG si tiene al menos 1 PG y la filacteria sigue intacta. Si la filacteria fue destruida, este rasgo deja de funcionar inmediatamente"],
      ["Comportamiento en combate","Casi sin personalidad reconocible — responde como una máquina de combate más que como Iarno. Si el grupo no destruye la filacteria, escapa una vez más al llegar a 0 PG en vez de morir del todo"],
    ], 2800, 7560),
    pEmpty(140),

    h3("12.9.5 — Cómo Cae la Ficha: la Revelación de Identidad"),
    p("Tu pedido era que la primera aparición NO disparara sospecha en la mesa. La revelación de que es Iarno debería llegar DESPUÉS del primer combate, por uno de estos medios:"),
    pEmpty(80),
    bullet("Un objeto que cae en el combate: el familiar oscuro (el cuervo sin ojos), al morir o ser destruido, suelta algo reconocible — un anillo, un fragmento de su viejo libro de conjuros de Phandelver, algo que un jugador con buena memoria de la campaña anterior pueda reconocer (Investigación o Historia, CD baja)"),
    bullet("Una voz reconocida en otro contexto: mucho después de este combate, en una escena completamente distinta, alguien menciona o imita una frase característica que el Iarno original solía decir — y un jugador conecta los puntos solo"),
    bullet("Logos con un dato tardío: si el grupo describe el encuentro a Logos en algún momento posterior, Logos puede procesar la descripción y decir: 'Coincidencia de patrón de comportamiento mágico: 89%. Sujeto identificado: Iarno Albrek. Nota: este sujeto fue registrado como fallecido.'"),
    pEmpty(80),
    secretBox("El golpe de la revelación funciona mejor si la mesa ya pasó la página emocionalmente — si genuinamente creían que esa historia había terminado. Dejá pasar al menos 1-2 sesiones completas entre el primer combate y la revelación de identidad, para que el 'ya lo derrotamos, no puede ser' pegue fuerte cuando caiga la ficha."),
    pEmpty(140),

    h2("12.10 Semilla para una Campaña Futura"),
    p("Si tu mesa quiere seguir jugando en este mundo después de 'El Guardián de los Sentires', acá tenés el punto de partida natural: el guardián sin nombre de la Esperanza (sección 9.4) podría no haber sido vaciado por Mnemós directamente — podría haber sido Ozyr quien orquestó esa pérdida específica hace mucho más tiempo, antes incluso de sembrar a Mnemós, como un primer experimento personal. Eso conecta las dos capas de villano en una sola historia más grande: Ozyr no solo creó indirectamente a un vaciador de Guardianes — empezó él mismo, hace siglos, y luego aprendió que es más eficiente que otro haga el trabajo mientras él gobierna desde las sombras."),
    pEmpty(80),
    secretBox("Si alguna vez decidís usar esto, la campaña futura podría empezar con algo tan simple como: la party, ya conocida en Neverwinter por su heroísmo, es invitada a una cena por el Magistrado Lord Veil, quien quiere 'agradecerles personalmente'. Nada amenazante. Solo una cena. Y un libro en blanco sobre un escritorio, en una sala que ellos nunca llegan a ver. Y si Iarno sigue 'vivo' de alguna forma tras la tercera aparición, ese mismo libro podría ser donde Ozyr guarda los datos de su experimento más largo."),
    pageBreak(),

    h2("12.11 Objetos de los Guardianes Perdidos"),
    p("Estos tres objetos ya circulan por el mundo antes de que el grupo llegue a tocarlos — pequeños, livianos, fáciles de confundir con baratijas. Cada uno es un fragmento simbiótico de un Guardián antiguo vaciado por Mnemós (ver la tabla de 2.6): no un arma ni una herramienta cualquiera, sino un resto consciente de algo que alguna vez sostuvo un hilo entero del tapiz emocional del mundo. Ninguno se puede quitar por la fuerza sin consecuencias reales — están fusionados a su portador, no atados."),
    pEmpty(80),
    secretBox("De los tres, solo el Guantelete Callado corresponde a un Guardián ya catalogado en la Colección Antigua (sección 9.4): Tahel, el Unicornio de los Vados, dueño de la Confianza. La Máscara y el Brazal son fragmentos que ni siquiera Mnemós tiene registrados — piezas que se perdieron o escaparon antes de que él pudiera sumarlas a su colección. Esto es deliberado: no todo lo que Mnemós vació está bajo su control, y eso es una grieta que podés explotar más adelante si querés."),
    pEmpty(140),

    h3("La Máscara de Hola (fragmento no catalogado)"),
    p("Tallada en madera oscura y porosa, increíblemente ligera, con runas desgastadas en los bordes. Al ponérsela, la madera se siente tibia, casi viva. Comprada sin saberlo en un mercado de Phandalin, mucho antes de que nadie sospechara qué era."),
    pEmpty(60),
    bullet("Etapa 1 — El Eco del Bosque (al lanzar un conjuro con componente Verbal): la mandíbula de madera se mueve en sincronía con los labios de Hola, y su voz gana un eco profundo. Ventaja en Intimidación mientras la lleve puesta."),
    bullet("Etapa 2 — El Detector de los Muertos (No-Muertos ocultos a menos de 9 m): la madera se pone gélida y huele a tierra podrida — Hola sabe que hay muerte antinatural cerca, aunque no la vea."),
    bullet("Etapa 3 — Simbiosis Defensiva (1/día, al recibir un golpe crítico o quedar a menos de la mitad de sus PG): raíces de madera brotan del borde y absorben el golpe — de forma automática, la máscara lanza Escudo (Shield) o da 1d8+4 PG temporales, sin gastar espacio de conjuro ni reacción."),
    bullet("Etapa 4 — La Astilla de la Verdad (maldición, al intentar mentir descaradamente): un pinchazo agudo en la mandíbula, 1 de daño perforante, y salvación de Constitución CD 10 o empieza a toser polen brillante, delatando la mentira."),
    bullet("Etapa 5 — La Voz que Vuelve (consciente): una vez que Hola la 'escucha' de verdad (una escena tranquila, sin apuro), el fragmento habla por primera vez, mente a mente: 'No recuerdo mi nombre. Recuerdo que alguien me lo preguntó una vez, con una voz parecida a la que usás vos para tus conjuros. Hace mucho que no hablaba con nadie. Gracias por no arrancarme.' A partir de ahí es un consejero, no un pasajero: 1/día puede lanzar Zona de Verdad sin gastar espacio, puede avisarle a Hola si alguien cerca miente con mala intención (antes del hecho, no después), y puede sentir si alguien se acerca con intención de robársela ('algo se acerca. No a vos. A mí.'). La maldición de la Etapa 4 se vuelve negociable: Hola puede pedirle que se quede callada una vez si necesita mentir tácticamente, a cambio de una punzada menor en vez del daño completo."),
    pEmpty(80),
    infoTable([
      ["Regla","Detalle"],
      ["Extracción Forzada","Constitución CD 14 para arrancarla a la fuerza (Hola u otro). Si falla: 2d4 de daño perforante, sangrado, y Envenenado (Desventaja en ataques y pruebas de habilidad) por 1 hora. La máscara NO sale — las raíces se aferran más fuerte a los huesos de la cara"],
      ["El Costo del Alquiler","Cada Descanso Largo, Hola gasta 1 Dado de Golpe sin curar nada — alimenta las raíces que la mantienen viva"],
      ["Comer y beber","La madera se afloja en la zona de los labios para permitirlo, aunque toda comida sabe ligeramente a tierra húmeda y ceniza"],
    ], 2800, 6560),
    pEmpty(140),

    h3("El Guantelete Callado (fragmento de Tahel, el Unicornio de los Vados — Confianza)"),
    p("Un guante de cuero curtido y bronce viejo, los dedos ligeramente curvados como a mitad de un apretón de manos que nunca terminó de darse."),
    pEmpty(60),
    bullet("Etapa 1 — Cosmético: al cerrar un trato o dar la palabra, el guantelete se entibia."),
    bullet("Etapa 2 — Útil: detecta intención de traición — un pulso breve cuando alguien con quien negocian planea romper el acuerdo en los próximos minutos."),
    bullet("Etapa 3 — Defensivo (1/día): si el portador va a recibir un ataque furtivo o una traición de un aliado en combate, el guantelete da Ventaja en la salvación o CA +2 contra ese golpe específico."),
    bullet("Etapa 4 — El Precio de Confiar (maldición, solo al usar la Etapa 5): cada vez que el portador use el poder consciente (Ayuda/Aid), la próxima tirada de Engaño que intente tiene Desventaja — protegerlos de verdad le cuesta parte de su propia capacidad de mentir, aunque sea un farol táctico en combate."),
    bullet("Etapa 5 — consciente: otorga Ayuda (Aid) 1/día sin gastar espacio de conjuro, reforzando a los aliados como gesto de 'confío en que van a estar bien'."),
    pEmpty(80),
    infoTable([
      ["Regla","Detalle"],
      ["Extracción Forzada","Igual que la Máscara: Constitución CD 14, mismo fallo (2d4 perforante, sangrado, Envenenado 1 hora), no sale por la fuerza"],
      ["Origen","Falta de la Colección Antigua del Archivo (sección 9.4) — escapó o fue robado hace mucho. Si el grupo lo lleva a esa sala, reacciona (ver 9.4)"],
    ], 2800, 6560),
    pEmpty(140),

    h3("El Brazal sin Miedo (fragmento no catalogado)"),
    p("Un brazal de hueso pulido, liviano, con una grieta que nunca terminó de sanar — se ve frágil pero no se rompe."),
    pEmpty(60),
    bullet("Etapa 1 — Cosmético: antes de un combate importante, vibra suavemente, como si se preparara con el portador."),
    bullet("Etapa 2 — Útil: Ventaja en salvaciones contra miedo mientras se lleva puesto."),
    bullet("Etapa 3 — Defensivo (1/día): si el portador queda Aterrorizado, puede terminar la condición de inmediato como reacción."),
    bullet("Etapa 4 — El Precio del Valor (maldición, solo al usar un poder del brazal): cada vez que el portador use el poder consciente (Heroísmo) o el rasgo defensivo (cortar el Miedo), la próxima vez que saque un 1 natural en un ataque o salvación siente la punzada fría de un miedo que no es suyo (1d4 de daño psíquico)."),
    bullet("Etapa 5 — consciente: otorga Heroísmo (Heroism) 1/día sobre un aliado, sin gastar espacio de conjuro."),
    pEmpty(80),
    infoTable([
      ["Regla","Detalle"],
      ["Extracción Forzada","Igual que los otros dos: Constitución CD 14, mismo fallo, no sale por la fuerza"],
    ], 2800, 6560),
    pageBreak(),

    h2("12.12 La Guardia de Ámbar — Facción"),
    p("Trabajan para Ozyr, aunque ni sus propios agentes lo saben con certeza — reciben órdenes de un intermediario, nunca del benefactor real, coherente con que Ozyr nunca se revela como villano (Regla de Oro, sección 12.1)."),
    pEmpty(80),
    secretBox("EL MOTIVO DE OZYR, EXPLÍCITO: no los quiere por sentimentalismo ni por avaricia simple. Cada fragmento de Guardián suelto por el mundo es evidencia física de un vaciado que no salió 'limpio' — ya sea de Tahel (catalogado, se le escapó a Mnemós) o de los no catalogados (que ni Mnemós sabe que sobrevivieron). Como científico frío que ya es (ver 12.9, el experimento de Iarno), estudiarlos lo acerca a entender por qué algunos vaciados dejan resto y otros no — información valiosa sea cual sea su plan final. Y mientras sigan sueltos, son un cabo suelto: prueba de siglos de experimentos que podría usarse en su contra, o en contra de Mnemós, si cae en las manos equivocadas. No los necesita para su plan (sigue sin depender de ningún resultado puntual, coherente con 12.7) — recuperarlos es limpieza de riesgo, no un objetivo central."),
    pEmpty(80),
    p("Estructura: tienen agentes infiltrados dentro de Los Sin-Color (sección 9.2), vigilando si algo relacionado a estos fragmentos surge en actividad ritual. Su otro brazo es una red de buscadores que se mueven de zona en zona posando como anticuarios o compradores de curiosidades — de ahí que objetos como el Guantelete Callado terminen, sin que el vendedor lo sepa, en un puesto de mercado como el de Kestrel Amonet (sección 9.1). Como sello de identidad, dejan una pequeña marca de cera color ámbar donde encontraron o perdieron el rastro de algo."),
    pEmpty(140),

    h3("Ilvara Thorne, \"La Curadora\" (líder)"),
    p("Una erudita-coleccionista que estudió estos objetos por curiosidad genuina antes de que Ozyr la reclutara. Fría, meticulosa, nunca sube la voz. Trata a sus tenientes como colegas, no subordinados."),
    pEmpty(60),
    p("Su ítem — El Ojo sin Párpado: un monóculo tallado en madera pálida, siempre húmedo, con vetas como venas. Le permite 'leer' el eco histórico de objetos y lugares — así rastrea tan bien estos fragmentos. Otorga Rastrear el Eco (como Localizar Objeto, pero solo contra ítems de Guardianes antiguos) 1/día sin gastar espacio. El costo: cada vez que lo fuerza más allá de su uso normal, pierde un fragmento de su propia memoria — buena parte de por qué se está volviendo cada vez más obsesiva es que, literalmente, se le está borrando quién era antes de esto."),
    pEmpty(80),
    secretBox("SI LA MATAN: el Ojo sin Párpado queda como loot. Quien se lo quede hereda la habilidad de rastreo — y también el costo de memoria. Ficha de combate completa en cap. 11 (Bestiario)."),
    pEmpty(140),

    h3("Sable Wren, \"El Rastro\""),
    p("Explorador/pícaro, experto en disfraces. Evita el combate directo y prioriza seguir al grupo sin ser visto, reportando por mensajero. Suele ser quien detecta la oportunidad y se la pasa a Grendal. Ficha completa en cap. 11."),
    pEmpty(80),

    h3("Grendal Ashwood, \"El Cincel\""),
    p("El que de verdad intenta arrancar los ítems a la fuerza. Grandote, directo, casi sin diálogo. Es quien ejecuta la Extracción Forzada si el grupo se lo permite — tanto en el intento nocturno en Neverwinter como en la emboscada posterior (ver cap. 9 y cap. 11.2). Ficha completa en cap. 11."),
    pEmpty(80),

    h3("Perpetua Voss, \"La Devota\""),
    p("Infiltrada dentro de Los Sin-Color hace tiempo, pasando por una verdadera creyente. Clériga/brujo, reporta cualquier actividad ritual que huela a estos ítems. Prefiere manipular antes que pelear. Ficha completa en cap. 11."),
    pEmpty(80),

    h3("Buscadores de Ámbar (soldados de a pie)"),
    p("Mercenarios genéricos, van en grupos de 3-4. Al morir o retirarse, dejan la marca de cera característica de la facción — una pista reconocible para el grupo. Ficha completa en cap. 11."),
    pageBreak(),
  ];
}
module.exports = { cap12 };