const { p, pEmpty, h1, h2, h3, bullet, numBullet, infoTable, noteBox, secretBox, loreBox, voiceBox, warningBox, xpBox, pageBreak, C } = require('./helpers');

function cap1() {
  return [
    h1("1. Visión General de la Campaña"),

    h2("1.1 Premisa Central (Información del DM — NO leer en mesa)"),
    p("Tras derrotar a Nezznar el Araña Negra en la Mina del Eco, el mundo empieza a perder color. Una niebla densa y sin saturación desciende de las montañas. El fuego es gris. La hierba es ceniza. Las personas ríen o lloran sin entender por qué."),
    pEmpty(),
    p("La causa: Chromatus, el Dragón Guardián de los Sentires, ha sido vaciado. Mnemós, un archivista inmortal, robó sus cinco Escamas de Color y las dispersó por la Costa de la Espada. Sin ellas, el mundo pierde sus emociones — y con ellas, la voluntad de existir."),
    pEmpty(80),
    warningBox("Esta sección es para que TÚ, como DM, entiendas la historia completa desde el inicio. El nombre 'Mnemós' es información de bambalinas — NO debe mencionarse en la mesa de juego hasta Monte Hotenow (sección 6.7), y la conexión con Logos no se revela hasta el Plano del Archivo (sección 8.6). Ver la Regla de Oro completa en la sección 10.3."),
    pEmpty(140),

    secretBox("OBJETIVO TEMÁTICO — Esta campaña trabaja la expresión emocional de forma lateral. Cada escama representa una emoción real. Los jugadores aprenderán que nombrar, entender y aceptar las emociones — incluso las difíciles — es lo que restaura el mundo. Esto nunca se dice en voz alta. Se vive en el juego."),
    pEmpty(140),

    h2("1.2 La Noche en que Cayeron las Estrellas — Cómo Empezó Realmente (Escena Ya Jugada)"),
    p("Esta sección documenta el evento real que ya ocurrió en la mesa, al cierre de 'La Mina Perdida de Phandelver' — el origen compartido de todo lo que sigue. No es una escena para volver a jugar: es el registro de lo que la party YA VIVIÓ, para que el resto del documento (especialmente los callbacks del clímax, sección 8.9 y 14.x) tenga el detalle exacto al que puede referirse más adelante."),
    pEmpty(80),
    voiceBox("\"Phandalin festejaba. Nezznar había caído, la Mina del Eco estaba a salvo, y el pueblo entero —Toblen, Sildar, cada vecino que el grupo había llegado a conocer en su primera aventura— se había juntado para celebrar a los héroes que los salvaron. Hubo comida, hubo música, hubo el tipo de alegría ruidosa y genuina que solo llega después de un peligro real superado. Y entonces, en medio del festejo, el color empezó a irse.\""),
    pEmpty(80),
    p("No fue gradual ni sutil: en el momento exacto en que ocurrió, todo —el fuego de las fogatas, la ropa de la gente, los rostros mismos— pasó a verse en blanco, negro y grises, como si el mundo entero hubiera sido pintado de nuevo con una paleta equivocada. Nadie en el pueblo lo entendió. La fiesta no se detuvo de golpe — siguió, confundida, mientras la gente se miraba entre sí sin saber qué decir de lo que estaban viendo."),
    pEmpty(80),
    voiceBox("\"Fue ahí, con el mundo ya sin color, que una tirada de Percepción de uno de los jugadores marcó la diferencia entre ver y no ver lo que pasó después: algo cruzó el cielo nocturno, una bola de fuego que debería haber ardido en naranja y rojo pero ardía en blanco y negro, como todo lo demás esa noche. No cayó lejos, en el horizonte — cayó cerca, en las afueras del pueblo. El impacto se sintió en el suelo bajo los pies de todos los presentes. Una nube de polvo se levantó contra el cielo sin color, y ahí, esa noche, la escena terminó — sin que nadie supiera todavía qué había caído, ni por qué el mundo se había apagado en el mismo instante.\""),
    pEmpty(80),
    secretBox("LO QUE REALMENTE PASÓ (para vos, DM): ese fue el momento exacto del vaciado de Chromatus — Mnemós completando la extracción de sus cinco Escamas, en algún lugar lejano. La pérdida de color y la caída no son dos eventos separados: son el mismo evento, percibido desde dos ángulos. Lo que cayó cerca de Phandalin esa noche es Chromatus mismo, debilitado y sin sus escamas, estrellándose contra la tierra después de perder el control de su propio vuelo. La investigación de ese cráter, al día siguiente o cuando la mesa decida ir, es el gancho natural que lleva al grupo a conocer tanto a Chromatus como a Logos por primera vez."),
    pEmpty(80),
    secretBox("POR QUÉ ESTO IMPORTA PARA EL RESTO DE LA CAMPAÑA: esta escena le da a la party un vínculo presencial directo con el origen mismo de la historia, algo que ningún NPC les contó — ellos LO VIERON. Esto se puede (y debe) usar como callback explícito en el clímax: cuando Chromatus recupere su memoria completa en el Plano del Archivo (sección 8.6), su propio recuerdo de la caída —el impacto, el mundo ya sin color, la cercanía de un pueblo con gente reunida— debería coincidir, punto por punto, con lo que la mesa misma vivió esa noche. El reconocimiento de 'eso fuimos nosotros' es uno de los cierres más fuertes posibles para toda la campaña."),
    pEmpty(140),

    h2("1.3 Tono y Estilo"),
    infoTable([
      ["Aspecto","Descripción"],
      ["Referencia de tono","Studio Ghibli + D&D oscuro. Maravilloso pero con peso real"],
      ["Combate / Roleplay","Equilibrado. Cada zona tiene combate Y un desafío moral o puzzle"],
      ["Complejidad","Alta. Decisiones sin respuesta correcta. Misterio que se revela lento"],
      ["Duración estimada","25–35 sesiones (comparable a Phandelver en extensión)"],
      ["Jugadores","Niño 11, adolescente 14, adulta — cada uno tiene un hilo narrativo propio"],
    ]),
    pEmpty(140),

    h2("1.4 Los Personajes Jugadores"),
    infoTable([
      ["Personaje","Hilo narrativo personal"],
      ["Angelus — Clérigo de la Muerte","Entiende que las cosas deben terminar para tener valor. Su arco: aprender que la alegría también termina, y eso no la hace menor"],
      ["Hola — Mago de Conjuración","Construye puentes entre lo que es y lo que podría ser. Su arco: aprender que algunos puentes no se pueden construir solo con magia"],
      ["Greyskull — Fighter / Clérigo","La fuerza sin fe es peligrosa, con fe es protectora. Su arco: entender que proteger incluye dejar que otros fallen y aprendan"],
      ["[DM] — Pícaro","Se mueve en silencio. Su arco: descubrir que ser invisible no es lo mismo que no importar"],
    ]),
    pEmpty(140),

    h2("1.5 Estructura de Tres Actos"),
    infoTable([
      ["Acto","Contenido","Sesiones Est."],
      ["I — La Niebla","Gancho en Phandalin. Chromatus. Logos. Primera calibración","1–3"],
      ["II — Las Escamas","Cuatro zonas, cuatro escamas, cuatro decisiones morales","4–25"],
      ["III — El Coleccionista","El Plano del Archivo. El clímax. Los tres finales posibles","26–35+"],
    ], 1800, 5580),
    pEmpty(140),

    h2("1.6 Progresión de Nivel — Hitos Narrativos"),
    p("La campaña usa progresión por hitos: el grupo sube de nivel al completar momentos narrativos clave, no por contar XP de combates individuales. Empiezan en nivel 5 (recién salidos de Phandelver)."),
    pEmpty(80),
    warningBox("Nota de balance: la party tiene aliados permanentes de alto poder (un golem de Hola, una quimera montura de Greyskull). Todos los CR y CDs de esta campaña están calibrados asumiendo esos aliados como parte del poder ofensivo del grupo — no como bonus adicional. Si en tu mesa estos aliados no participan en un combate específico (por ejemplo, el golem no entra en un espacio reducido), considera bajar el CR del encuentro en 1-2 o agregar una ronda de ventaja a la party."),
    pEmpty(80),
    xpBox([
      ["Inicio de campaña","Tras derrotar a Nezznar (fin de Phandelver)","5"],
      ["Hito 1","Restaurar la Escama Amarilla (Cuerda-Floja)","6"],
      ["Hito 2","Restaurar la Escama Azul (Pantano de los Muertos)","7"],
      ["Hito 2.5 (opcional)","Resolver el Taller del Recuerdo y descubrir a Vex","7 (sin subir, +1 objeto mágico menor)"],
      ["Hito 3","Restaurar la Escama Roja (Monte Hotenow)","9"],
      ["Hito 3.5 (opcional)","Resolver Los Sin-Color","9 (sin subir, +reputación/aliados)"],
      ["Hito 4","Restaurar la Escama Verde (Bosque de Neverwinter)","11"],
      ["Hito 5","Acceder al Plano del Archivo y enfrentar los Miedos","12"],
      ["Hito Final","Resolución del clímax (cualquier final)","13"],
    ]),
    pEmpty(140),

    h2("1.7 Flujo de la Campaña — Orden de las Zonas"),
    p("Esta sección aclara cómo fluye la campaña sesión a sesión, para que no haya dudas sobre a dónde va el grupo ni en qué orden."),
    pEmpty(80),
    p("El Sextante de Cromaticidad (que Logos provee, ver Cap. 3) detecta las cinco escamas y recomienda recuperarlas 'de menor a mayor inestabilidad'. Ese es el orden sugerido y el que usan la tabla de niveles y la cronología:"),
    pEmpty(60),
    numBullet("Escama AMARILLA (Cuerda-Floja) — nivel 5→6"),
    numBullet("Escama AZUL (Pantano de los Muertos) — nivel 6→7"),
    numBullet("Escama ROJA (Monte Hotenow) — nivel 7→9"),
    numBullet("Escama VERDE (Bosque de Neverwinter) — nivel 9→11"),
    numBullet("Escama NEGRA (Plano del Archivo, clímax) — nivel 11→13. Esta SIEMPRE es la última: el Archivo solo se vuelve accesible cuando las otras cuatro escamas están reunidas (ver sección 8.1)"),
    pEmpty(80),
    noteBox("¿ORDEN FIJO U ORDEN LIBRE?","Las cuatro escamas elementales (amarilla, azul, roja, verde) pueden hacerse en el orden que el grupo prefiera — el Sextante las detecta todas a la vez y el grupo elige cuál seguir. PERO los encuentros de cada zona están calibrados para el nivel de la tabla de arriba. Si tu grupo quiere romper el orden, ajustá el nivel de los enemigos de esa zona al nivel real del grupo: subí o bajá los CR en 1-2 puntos según corresponda. La quinta escama (negra) es siempre la última, sin excepción. Recomendación: si tu mesa prefiere no preocuparse por el balance, dejá que Logos insista en el orden sugerido.","FFF8E7",C.goldDeep),
    pEmpty(80),
    p("Cómo sabe el grupo a dónde ir: después de cada escama recuperada, Logos recalibra el Sextante y señala la siguiente señal más estable. Además, cada zona deja una pista que apunta temáticamente a la próxima. El grupo nunca debería quedarse sin saber su próximo destino: si dudan, Logos lo dice con su honestidad de siempre — 'Siguiente anomalía estable detectada: [zona]. ¿Procedemos?'"),
    pEmpty(140),

    h2("1.8 Neverwinter — Por Qué el Grupo Va Ahí"),
    p("Gran parte del contenido de la campaña (el Taller del Recuerdo, los Sin-Color, varias pistas, y el comercio de equipo) vive en Neverwinter. Si el grupo nunca tiene un motivo concreto para entrar a la ciudad, todo eso se pierde. Estos son tres ganchos concretos, escalonados en el tiempo, para asegurar que la ciudad se sienta necesaria y no opcional:"),
    pEmpty(80),
    infoTable([
      ["Gancho","Cuándo se activa","Por qué funciona"],
      ["1. Logos necesita calibrar el Sextante con un 'ancla de civilización'","Tras la primera escama (Amarilla), antes de viajar a la segunda zona","Logos lo dice con su honestidad técnica: 'El Sextante requiere recalibración periódica contra una fuente de datos estable. Recomiendo una ciudad de tamaño significativo. Neverwinter es la más cercana.' Esto convierte la primera visita en un paso MECÁNICO del viaje, no en una excursión opcional"],
      ["2. Phandalin no alcanza — necesidad de mercado real","Después de cualquier dungeon (Cap. 11) o tras la zona 2, cuando el grupo tenga loot que vender o necesite reabastecerse","Phandalin es un pueblo pequeño sin mercado de objetos mágicos. Si el grupo junta gemas, objetos raros, o necesita pociones/pergaminos que no existen en Phandalin, Neverwinter es la única ciudad con la infraestructura para eso en toda la región"],
      ["3. Un NPC los envía directamente","Tras la zona 1 (Cuerda-Floja) — Barnaby o Donto lo sugiere explícitamente","Antes de que el grupo deba 'tropezar' con el caso de Dax por casualidad en el mercado, dale un empujón activo: Donto (el posadero) o Barnaby le pide al grupo, como favor, que entregue una carta o un paquete a un primo/conocido en Neverwinter — cualquier excusa simple de pueblo chico"],
    ], 2400, 2400, 5560),
    pEmpty(80),
    noteBox("RECOMENDACIÓN PRÁCTICA","Usá el Gancho 1 (Logos y el Sextante) como el motivo PRINCIPAL y recurrente — es el más limpio porque convierte cada visita a Neverwinter en parte del viaje normal entre zonas, no en una desviación que hay que justificar cada vez. Los Ganchos 2 y 3 son refuerzos para la primera vez. Una vez que conocen a Dax, a Tera, o tienen algo pendiente en la ciudad, ya no necesitás ningún gancho — vuelven solos porque tienen asuntos ahí.","FFF8E7",C.goldDeep),
    pEmpty(140),

    h3("Eco de Cuerda-Floja — 'El Pueblo que Volvió a Reír'"),
    p("Si el grupo resolvió bien la zona 1 (Cuerda-Floja) — salvaron la cocina, restauraron a Barnaby, devolvieron algo genuino de alegría al pueblo — esa noticia viaja, sin que el grupo tenga que hacer nada para que pase. No es un sistema mecánico ni un Boon: es puro eco de mundo, reputación que se siembra sola."),
    pEmpty(80),
    secretBox("CÓMO USARLO: en la primera visita del grupo a Neverwinter (cualquiera de los tres ganchos de arriba), dejá que un NPC menor —un comerciante, un guardia, alguien en una taberna— mencione de pasada haber escuchado del 'pueblo de la montaña que volvió a reír'. No hace falta que sepan que se refiere a Cuerda-Floja específicamente con ese nombre, ni que conecten los puntos de inmediato — el efecto es más fuerte si la mesa tarda un segundo en darse cuenta de que están hablando DEL LUGAR DONDE ELLOS ESTUVIERON. Algo simple alcanza: 'Dicen que hay un pueblo en la montaña donde la Niebla se rompió antes que en cualquier otro lado. La gente ríe distinto ahí, dicen. Como si se hubieran olvidado de qué se sentía y de golpe se acordaron.'"),
    pEmpty(80),
    noteBox("SI CUERDA-FLOJA NO SE RESOLVIÓ TAN BIEN","Si el grupo perdió la cocina, o la zona quedó con un final agridulce, este eco simplemente no se siembra — no hace falta una versión negativa ni un castigo narrativo, el silencio mismo ya dice algo. El mundo no habla del lugar donde no pasó nada memorable.","FFF8E7",C.goldDeep),
    pEmpty(80),
    secretBox("Entre zonas hay espacio para respirar: descansos en Phandalin o Neverwinter, compras, misiones secundarias globales (Cap. 9), encuentros de camino (sección 11.2) y desarrollo del arco de Logos (sección 9.3). No hace falta correr de una escama a la siguiente — el ritmo de Phandelver (varias sesiones por zona) es el ideal."),
    pageBreak(),
  ];
}
module.exports = { cap1 };
