const { p, pEmpty, h1, h2, h3, bullet, numBullet, infoTable, noteBox, secretBox, loreBox, voiceBox, warningBox, cdBox, xpBox, pageBreak, npcBlock, C } = require('./helpers');

function cap14() {
  return [
    h1("14. Arcos Personales de los Personajes Jugadores"),
    p("Este capítulo desarrolla tres arcos secundarios, uno por jugador (Hola, Angelus, Greyskull), basados en el trasfondo familiar real de cada uno. Son completamente opcionales y modulares — podés activarlos cuando la mesa esté lista, en cualquier orden, sin que dependan entre sí ni de la trama principal de Mnemós."),
    pEmpty(80),
    warningBox("ESTE CAPÍTULO MEZCLA CONTENIDO DE MESA Y CONTENIDO SECRETO. Cada sección está marcada claramente: lo que es para LEER O NARRAR EN MESA, y lo que es SOLO PARA EL DM (la verdad de fondo que nunca se confirma del todo en el juego). Prestá atención a esas etiquetas antes de usar cada parte."),
    pageBreak(),

    // ============ HOLA ============
    h2("14.1 El Arco de Hola — La Casa, el Hermanastro, el Padre"),
    p("Basado en el trasfondo real de Hola: una casa con sirvientes en Neverwinter, un hermanastro con un pájaro llamado Peter (el mismo nombre que el familiar de Hola, ahora un lobo, originalmente un águila devorada por Venomfang), y un padre ejecutado por crucifixión."),
    pEmpty(80),

    h3("14.1.1 — Escena de Apertura (Cold Open): El Día de la Ejecución"),
    p("Inspirada en las escenas de flashback jugables de Brennan Lee Mulligan (Critical Role, Campaña 4) — una escena dramática al INICIO de una sesión, sin combate, donde el jugador de Hola controla a su propio personaje de joven, estudiante de magia, presente en la ejecución pública de su padre. El resultado de la escena es siempre el mismo (la muerte del padre); lo que varía es el tono y la experiencia de Hola viviéndolo."),
    pEmpty(80),
    warningBox("REGLA DE ORO DE ESTA ESCENA: Hola reconoce y recuerda la CARA de Lord Veil para siempre. Hola NUNCA conecta a Lord Veil con Ozyr Thane ni con nada sobrenatural — para él, simplemente queda grabado el rostro de 'el magistrado que ordenó la muerte de mi padre'. Esto no rompe la regla de oro del Titiritero (sección 12.1): la identidad de Ozyr como lich sigue siendo un secreto total. Lo que cambia es que, a partir de esta escena, Hola SÍ puede reconocer a Lord Veil si lo ve en persona más adelante en Neverwinter — eso es intencional y le da a Hola un gancho emocional único en la mesa."),
    pEmpty(80),
    voiceBox("\"La plaza principal de Neverwinter está más llena de lo normal — no es día de mercado, pero la gente se junta igual, con esa mezcla de morbo y silencio que tienen las multitudes cuando saben que algo grave está por pasar. Hola, todavía joven, con los libros de la escuela de magia bajo el brazo, se abre paso entre la gente sin entender del todo por qué sus pies lo llevaron hasta ahí. Y entonces lo ve: a su padre, en el centro de la plaza, ya en la cruz.\""),
    pEmpty(80),
    p("Estructura de la escena — tres momentos, cada uno con una tirada de sabor que NO cambia el resultado final:"),
    pEmpty(60),
    infoTable([
      ["Momento","Qué intenta Hola","Tirada","Resultado (siempre el mismo desenlace, cambia el tono)"],
      ["1 — Acercarse","Hola intenta abrirse paso entre la multitud para llegar más cerca","Atletismo o Acrobacias CD 12","Éxito alto: llega justo al borde de la primera línea de guardias, lo suficientemente cerca para que su padre, quizás, lo vea un instante. Éxito bajo o fallo: la multitud lo traga, o un brazo conocido lo sujeta con firmeza"],
      ["2 — Intentar algo","Hola intenta canalizar algo de magia —cualquier cosa— sin saber bien qué espera lograr","Conocimiento Arcano o Inteligencia CD 15","Sin importar el resultado, no pasa nada visible — es demasiado joven, sin el poder ni el conjuro correcto. Una chispa que no prende, un picor en las manos que no se convierte en nada"],
      ["3 — Las últimas palabras","Antes de que se cumpla la sentencia, el padre de Hola dice algo — el jugador elige qué, sin tirada","Ninguna — elección pura del jugador","Lo que el padre diga puede tener eco más adelante en la campaña (ver nota abajo)"],
    ], 1600, 2400, 2200, 3960),
    pEmpty(80),
    voiceBox("\"En el centro de la plaza, sobre un estrado de piedra, un hombre de mediana edad observa con la espalda recta y las manos cruzadas — ropa fina pero discreta, el tipo de elegancia que no necesita llamar la atención porque el poder ya está dado por sentado. No grita la sentencia con dramatismo: la lee de un pergamino, en voz clara y pareja, casi aburrida.\n\n'Por orden del Consejo de Neverwinter y en virtud de la autoridad que me ha sido conferida, se declara lo siguiente: que el acusado, habiendo sido hallado en posesión de documentos y correspondencia que comprometen la seguridad del orden civil de esta ciudad, y habiendo actuado en conspiración contra la corona y contra la paz de sus habitantes, es por la presente condenado por traición a la corona y conspiración contra el orden de esta ciudad.\n\nLa pena dictada es la muerte, ejecutada en público, como corresponde a la gravedad del delito y como recordatorio para cualquiera que considere seguir su mismo camino. La sentencia se cumple hoy, a esta hora, en este lugar, ante esta ciudad como testigo.\n\nQue quede constancia de que el Consejo no actúa por crueldad, sino por necesidad. El orden de Neverwinter no se sostiene solo con leyes — se sostiene con la certeza de que las leyes se cumplen. Que esto sirva de lección, no de espectáculo.\n\nQue se proceda.'\n\nNo mira al padre de Hola a los ojos en ningún momento — mira al pergamino, o a la multitud, nunca al hombre que está condenando. Cuando todo termina, simplemente se da vuelta y se retira, sin esperar a que se cumpla del todo. No hubo crueldad en su voz. Tampoco hubo piedad. Solo trabajo, hecho.\""),
    pEmpty(80),
    secretBox("ESE HOMBRE ES LORD VEIL (Ozyr Thane, sección 12.1) — y esto es deliberado en su personalidad: frialdad profesional, no crueldad performativa. Describilo con detalles físicos consistentes (edad aparente ~50, elegancia discreta, postura recta) para que, mucho más adelante en la campaña, si Hola se cruza con Lord Veil en Neverwinter (sección 12.5), el jugador pueda reconocerlo por su cuenta sin que vos tengas que señalarlo. Si eso pasa, dejá que sea el jugador quien lo note primero."),
    pEmpty(80),
    noteBox("LAS ÚLTIMAS PALABRAS DEL PADRE — CÓMO USARLAS DESPUÉS","Lo que el jugador eligió que el padre dijera en el Momento 3 puede convertirse en un hilo recurrente: una frase que Hola recuerda en momentos de duda a lo largo de la campaña, algo que quizás coincide (sin que Hola lo busque a propósito) con el documento incompleto que encuentra después en el estudio del padre (sección 14.1.3).","FFF8E7",C.goldDeep),
    pEmpty(80),
    secretBox("CUÁNDO USAR ESTA ESCENA: al inicio de la primera sesión, antes de que arranque cualquier otra cosa de la campaña — es la cold open perfecta, sin combate, pura escena dramática que establece el tono y le da a Hola un trasfondo activado desde el minuto uno."),
    pEmpty(140),

    h3("14.1.2 — La Verdad de Fondo (SOLO PARA EL DM)"),
    secretBox("EL PADRE NO MURIÓ AL AZAR: el padre de Hola supo algo sobre la red de Ozyr Thane (Cap. 12) — no se especifica exactamente qué, y no hace falta que lo sepas tampoco antes de jugarlo: podés decidirlo en el momento, o dejarlo deliberadamente vago incluso para vos. Lo que sí es fijo: lo que sabía era peligroso, y la ejecución pública por crucifixión no fue solo castigo — fue un MENSAJE deliberado, exhibido a propósito, para que cualquier otro que supiera algo similar entendiera las consecuencias. Es el tipo de operación silenciosa y quirúrgica que ya establecimos como estilo de Ozyr (sección 12.5) — nada de magia oscura visible, solo poder político ejercido con frialdad."),
    pEmpty(80),
    secretBox("POR QUÉ LA RED SIGUE PAGANDO LA CASA — LO QUE TODAVÍA NO ENCONTRARON: la red de Ozyr nunca recuperó lo que el padre escondió. No fue generosidad lo que dejó a la familia con sirvientes y propiedad — fue, y sigue siendo, VIGILANCIA. Los sirvientes de la casa son, sin que la familia lo sepa, parte de la misma red de informantes de bajo perfil descrita en 12.5 ('el bajo mundo / información'): reportan movimientos, visitas, cualquier señal de que alguien busca algo en la casa. La compensación económica es la tapadera perfecta — mantener a la familia cómoda y sin sospechas mientras se sigue buscando, con paciencia de siglos, lo que el padre escondió antes de morir."),
    pEmpty(80),
    secretBox("QUÉ ES LO QUE ESCONDIÓ EXACTAMENTE: un documento parcial — no una prueba completa contra Ozyr (eso sería demasiado limpio), sino fragmentos de su propia investigación: nombres de otras personas que también empezaron a sospechar algo y luego 'desaparecieron de los registros' (el mismo patrón que la Crónica de la Corte Desvanecida, sección 12.4, usa para describir a Ozyr mismo), y una anotación final, incompleta, que menciona 'el magistrado que nunca envejece' sin nombrarlo del todo. Está escondido DENTRO de la propia casa — sugerido: un compartimento falso en un mueble viejo del estudio del padre, algo que ningún sirviente (ni siquiera los infiltrados) encontró en años porque nadie sospechó que un objeto tan modesto pudiera ser el escondite."),
    pEmpty(80),
    secretBox("CÓMO CONECTA CON EL HERMANASTRO: el hermanastro de Hola se unió a Los Sin-Color (sección 9.2) — y la casa funciona, sin que él lo note, como un ancla de retorno: un lugar cómodo al que siempre puede 'volver' si alguna vez duda de la secta, asegurando que su salida de los Sin-Color siempre lo lleve de vuelta a un entorno que la red de Ozyr sigue vigilando. Esto no es necesariamente activo ni intencional segunda capa — es simplemente cómo opera la indiferencia eficiente de Ozyr (sección 12.7): cualquier resultado le sirve."),
    pEmpty(80),
    secretBox("LO QUE EL HERMANASTRO HIZO ANTES DE IRSE — LA PIEZA QUE FALTA: años antes de unirse a Los Sin-Color, el hermanastro también investigó por su cuenta la muerte del padre — de noche, a escondidas, sin decírselo a nadie. No llegó a una respuesta: encontró algo (un objeto, una frase repetida, un nombre a medias — decidilo vos según lo que necesite tu mesa) pero no supo qué hacer con eso, y nunca se lo contó ni a Hola ni a su madre. Esa búsqueda sin cierre es, en parte, lo que lo dejó vulnerable al mensaje de Los Sin-Color: si no podés resolver el dolor de no saber, quizás sea más fácil dejar de sentirlo. Esta pieza es la que le falta al documento del padre (sección 14.1.5) — y solo el hermanastro la tiene."),
    pEmpty(140),

    h3("14.1.3 — Parte 1: La Visita a la Casa"),
    p("Sugerido: este arco se activa naturalmente la primera vez que el grupo visita Neverwinter y pasa por la casa de Hola."),
    pEmpty(80),
    infoTable([
      ["Paso","Detalle"],
      ["1. Llegada a la casa","Los sirvientes reciben a Hola con calidez genuina. Nada parece sospechoso a primera vista"],
      ["2. El hermanastro","Si todavía no se unió a los Sin-Color, puede aparecer aquí con Peter (el pájaro real, vivo, distinto del lobo-familiar de Hola). Si ya se unió, su cuarto vacío, Peter sin dueño que lo cuide bien"],
      ["3. El estudio del padre","Investigación CD 15 para notar que un mueble tiene un compartimento falso"],
      ["4. El documento (incompleto)","Dentro: fragmentos de investigación incompletos y la frase final sin completar: 'el magistrado que nunca envejece...' — sigue incompleto hasta la Parte 3"],
    ]),
    pEmpty(80),
    p("El gancho hacia la Parte 2: una sirvienta llamada Dessa."),
    pEmpty(60),
    voiceBox("\"Dessa deja de doblar la ropa a medio camino. No mira a Hola a los ojos cuando responde. 'Su hermano... él también hacía preguntas. Hace años, antes de irse. Sobre el estudio, sobre lo que guardaba tu padre ahí. No sé qué encontró — si encontró algo. Nunca volvimos a hablar de eso, ni él ni yo. No es mi lugar decir más.' Se aleja rápido, con la ropa todavía a medio doblar.\""),
    pEmpty(80),
    cdBox([
      ["Perspicacia o Persuasión para que Dessa diga más","13-14","Admite, reticente, que las búsquedas del hermanastro eran de noche, a escondidas, y que dejó de hacerlas más o menos cuando empezó a juntarse con 'gente nueva' — la primera señal, sin que ella lo supiera, de Los Sin-Color"],
    ]),
    pEmpty(80),
    secretBox("DESSA REACCIONA AL HERMANASTRO, NO AL PADRE: ya está entrenada para hablar del padre sin inmutarse — es tema resuelto para la red que la puso ahí. El hermanastro es distinto: es el único cabo suelto que esa red nunca cerró, y Dessa lo sabe sin saber por qué le importa tanto."),
    pEmpty(80),
    noteBox("RECOMPENSA — PUENTE DE SANGRE, ETAPA 1","Al completar esta escena (encontrar el documento Y el gancho de Dessa), el vínculo de Hola con su golem da un primer paso: una vez por descanso largo, puede cederle hasta 5 PG temporales a un aliado adyacente. Todavía no hay redirección de daño — es apenas el inicio de algo que va a crecer en las próximas partes.","FFF8E7",C.goldDeep),
    pEmpty(140),

    h3("14.1.4 — Parte 2: El Hermanastro"),
    p("El grupo localiza al hermanastro a través de Los Sin-Color (sección 9.2) o de contactos en Neverwinter. El encuentro no tiene garantía de final feliz."),
    pEmpty(80),
    voiceBox("\"Está más flaco de lo que Hola recuerda, y hay algo apagado en su forma de hablar — no hostil, solo... distante, como si hubiera bajado el volumen de todo. Reconoce a Hola de inmediato. 'Viniste,' dice, sin sorpresa. 'Supongo que era cuestión de tiempo.'\""),
    pEmpty(80),
    infoTable([
      ["Si Hola le pregunta directamente por el estudio del padre","Respuesta"],
      ["Con calidez o sin presión","El hermanastro se ablanda un poco. Cuenta que buscó, de noche, durante meses, y que encontró algo que nunca entendió del todo — y lo entrega (objeto, frase o nombre a medias, a elección del DM), sin pedir nada a cambio, casi aliviado de compartir el peso"],
      ["Con presión o acusación","Se cierra. Lo entrega igual, pero con resentimiento: 'Tomalo. A mí no me sirvió de nada.' No hay reconciliación en esta versión — la pieza se consigue, el vínculo no se repara"],
    ], 4000, 5560),
    pEmpty(80),
    secretBox("NO FUERCES UN FINAL FELIZ: el hermanastro puede quedarse en Los Sin-Color después de esta escena, y es válido que lo haga. Lo que importa mecánicamente es que entrega la pieza; lo que importa emocionalmente es que Hola decide cómo se siente con eso, sin que el juego le diga si hizo lo correcto."),
    pEmpty(80),
    noteBox("RECOMPENSA — PUENTE DE SANGRE, ETAPA 2","El vínculo crece: una vez por descanso largo, como reacción, el golem puede interponerse ante un solo golpe dirigido a un aliado adyacente y absorber la mitad de ese daño (hasta un máximo de 10 puntos absorbidos). Todavía es puntual, no continuo — eso llega en la Parte 4.","FFF8E7",C.goldDeep),
    pEmpty(140),

    h3("14.1.5 — Parte 3: Dungeon — El Sótano del Padre"),
    p("Al combinar la pieza del hermanastro con los fragmentos de la Parte 1, Logos detecta algo que no es solo texto."),
    pEmpty(80),
    voiceBox("\"Logos escanea ambos fragmentos en silencio durante más tiempo del habitual. 'Coincidencia textual: 87%. Pero hay algo más.' Una pausa. 'Detecto un patrón geométrico superpuesto al texto — no es escritura, es un sello arcano. Reconstrucción posible: es un mapa.' Otra pausa, más larga. 'Este documento no es la respuesta. Es la llave a donde está la respuesta.'\""),
    pEmpty(80),
    secretBox("QUÉ SEÑALA EL MAPA: un sótano bajo la propia mansión, construido y sellado por el padre de Hola en secreto — ni la madre ni el hermanastro supieron nunca que existía. Es la razón real por la que la red de vigilancia (sección 14.1.2) nunca encontró lo que buscaba: nunca estuvo en el estudio. El compartimento falso solo guardaba el mapa hacia el verdadero escondite."),
    pEmpty(80),
    warningBox("LA CARRERA: el acto de combinar las piezas también genera una firma mágica breve que la red capta, sin saber exactamente qué significa — solo que algo cambió en la casa que vigilan hace años. Esto NO es un reloj narrativo silencioso (sección 10.7): es explícito y urgente. Un grupo de agentes se mueve hacia la mansión al mismo tiempo que el grupo, para llegar antes. Si tu mesa tarda mucho en decidirse a bajar, los agentes ya están adentro cuando entren (ver Área 1)."),
    pEmpty(140),

    h3("Área 1 — La Entrada Oculta"),
    voiceBox("\"El mapa señala la bodega de la casa, detrás de un estante de vinos que nunca se movió en años de polvo acumulado — salvo que, mirando de cerca, SÍ se movió, y hace poco. Dessa, si está cerca, frunce el ceño: 'Esas dos personas de ahí... no son del servicio. Nunca las vi. ¿Quién las dejó entrar?'\""),
    pEmpty(80),
    cdBox([
      ["Combate — 3 Agentes de la Red (CR 1 c/u)","—","Mercenarios profesionales, no fanáticos — pelean con eficiencia fría, se rinden o huyen si quedan solos y sin apoyo. Ninguno sabe para quién trabaja más allá de 'un contrato, pagado por adelantado, sin preguntas'"],
    ]),
    pEmpty(140),

    h3("Área 2 — El Corredor de Vigilancia"),
    voiceBox("\"Más allá de la entrada, el corredor de piedra tiene marcas de años de búsqueda: paneles arrancados, herramientas de excavación abandonadas, una mesa plegable con notas en un código que nadie del grupo reconoce. Llevan mucho tiempo buscando esto. Nunca lo encontraron.\""),
    pEmpty(80),
    cdBox([
      ["Investigación o Arcanos para notar el ward residual antes de pisarlo","14","Fallo: activan una alarma arcana silenciosa — no hace daño, pero alerta de inmediato al grupo del Área 3, perdiendo el factor sorpresa"],
    ]),
    pEmpty(80),
    noteBox("LAS NOTAS EN CÓDIGO","Si el grupo se las lleva y las descifra más adelante (Arcanos o Investigación CD 16, fuera de esta escena), confirman que la red lleva 'al menos dos décadas' buscando este sótano sin éxito — tiempo suficiente para insinuar que quien los contrata tiene paciencia fuera de lo normal, sin nombrar a nadie.","FFF8E7",C.goldDeep),
    pEmpty(140),

    h3("Área 3 — La Cámara de los Buscadores"),
    voiceBox("\"La cámara final antes de la puerta de piedra maciza en el fondo. Un grupo de agentes trabaja contra el sello con herramientas y algo de magia menor, de espaldas al grupo, sin darse cuenta todavía de que ya no están solos.\""),
    pEmpty(80),
    cdBox([
      ["Combate — 1 Líder de Célula (CR 4) + 3 Agentes de la Red (CR 1 c/u)","—","El líder es la primera oposición seria del arco de Hola — un combate real, no un trámite. Si el grupo ataca por sorpresa (posible si no activaron la alarma del Área 2), gana una ronda de ventaja"],
    ]),
    pEmpty(80),
    secretBox("SI SE LO INTERROGA: el líder no sabe el nombre real de quien lo contrata — solo un intermediario, pagos en oro sin marcar, instrucciones específicas de 'encontrar el sótano y no tocar nada de lo que hay adentro, solo fotografiar y reportar'. Ni siquiera la propia red confía en sus agentes con la verdad completa — coherente con la indiferencia eficiente de Ozyr (sección 12.7)."),
    pEmpty(140),

    h3("Área 4 — La Puerta Final"),
    voiceBox("\"La puerta de piedra no tiene cerradura visible, ni bisagras, ni picaporte — solo un sello grabado, la misma marca del mapa. Cuando Hola se acerca, el sello responde: una luz tenue recorre las líneas grabadas, como si reconociera algo en él más que en cualquier otro presente. La puerta se abre sola, sin tirada, sin llave — solo para él.\""),
    pEmpty(80),
    secretBox("POR QUÉ SOLO HOLA: el padre selló esta puerta con un ward de sangre y firma arcana, keyeado específicamente a su propio linaje — anticipando que, si alguna vez alguien necesitaba encontrar esto, sería su hijo, no un desconocido. Ni la red ni el resto del grupo pueden abrirla, sin importar cuánto lo intenten. Es, deliberadamente, el único momento de todo el arco que le pertenece solo a Hola."),
    pEmpty(80),
    voiceBox("\"Adentro, una habitación pequeña y seca, sin polvo — el sello mantuvo el aire fuera de esta también. Sobre un escritorio, una carta, con la letra del padre, dirigida 'A quien la sangre reconozca'.\""),
    pEmpty(80),
    secretBox("CONTENIDO DE LA CARTA (para leer o parafrasear en mesa): el padre escribe que pasó años investigando desapariciones de gente que, como él, empezó a hacer las preguntas equivocadas — nombres, fechas, patrones que no deberían repetirse en una sola vida humana. Concluye, como sospecha personal y no como hecho probado, que detrás de todo hay una sola persona, con acceso a los registros civiles de Neverwinter desde hace más tiempo del que cualquiera admitiría en público — 'el magistrado que nunca envejece'. No nombra a Ozyr Thane ni a Lord Veil en ningún momento — ni siquiera él llegó a esa conexión. Termina pidiendo perdón por el riesgo que esto significa para su familia, y esperando que, si alguien lee esto alguna vez, sea porque hizo falta, no porque él ya no está."),
    pEmpty(80),
    secretBox("SIN NOMBRAR A OZYR: esto NO revela a Ozyr Thane como villano (Regla de Oro, sección 12.1) — es la sospecha personal de un hombre, no una confirmación de la trama, exactamente al mismo nivel de insinuación que la pista 4 del Cap. 12 (la carta sin remitente). Sugiere con fuerza. No confirma nada."),
    pEmpty(140),

    h3("14.1.6 — Parte 4: Cierre — El Ancla que Suelta"),
    p("Con la carta del padre en mano (aunque su sospecha siga sin confirmarse), Hola tiene que decidir qué hacer con la casa que, sin saberlo del todo su familia, sigue vigilada."),
    pEmpty(80),
    infoTable([
      ["Decisión de Hola","Consecuencia"],
      ["Sacar a su madre de la casa","Pierden la comodidad económica y la propiedad — pero la vigilancia pierde su ancla. Es una victoria a medias: seguridad real a cambio de estabilidad material"],
      ["Dejar las cosas como están","La madre sigue cómoda, sin saber que la observan. Hola carga solo con ese conocimiento — ninguna opción es sencilla, y esa es la idea"],
    ], 3600, 5960),
    pEmpty(80),
    noteBox("RECOMPENSA — PUENTE DE SANGRE, ETAPA 3 (completa)","Cualquiera sea la decisión, el arco cierra y el vínculo llega a su forma final: una vez por descanso largo, como acción bonus, Hola vincula a su golem con un aliado durante 1 minuto — todo el daño que ese aliado reciba se divide a la mitad con el golem, golpe a golpe, hasta un máximo de 15 puntos absorbidos por golpe.","FFF8E7",C.goldDeep),
    pageBreak(),

    // ============ ANGELUS ============
    h2("14.2 El Arco de Angelus — El Plano Gris y el Abuelo Sobreviviente"),
    p("Basado en el trasfondo real de Angelus: perdió a toda su familia en un brote de no-muertos 'en otro plano'. Este arco le da un camino propio de investigación, separado del plan activo de Ozyr, con dos fuentes de información: un sobreviviente (a través de su familia) y visiones de la Raven Queen."),
    pEmpty(80),

    h3("14.2.1 — Escena de Apertura (Cold Open): El Día del Colapso"),
    p("Igual que la escena de Hola (sección 14.1.1), inspirada en los flashbacks jugables de Brennan Lee Mulligan — una escena dramática al INICIO de una sesión, sin combate real, donde el jugador de Angelus controla a su propio personaje de niño, en el momento del colapso del Plano Gris."),
    pEmpty(80),
    warningBox("VALIDACIÓN DE CONTINUIDAD IMPORTANTE: el abuelo sobreviviente de la familia de vendedores (sección 14.2.4) NO es pariente de Angelus y NO aparece en esta escena. Es un sobreviviente totalmente distinto e independiente, que escapó del Plano Gris por su cuenta. Esta escena de apertura es la vivencia DIRECTA y propia de Angelus con SU familia."),
    pEmpty(80),
    warningBox("CALIBRACIÓN PARA UN JUGADOR DE 11 AÑOS: el horror del Plano Gris está diseñado para ser NO gráfico — la gente camina, no ataca, no hay sangre ni gore. El peso emocional viene del sacrificio y la separación, no del miedo físico. Angelus nunca ve a su familia morir — los ve alejarse, perderse en el gris, mientras lo empujan a salvarse."),
    pEmpty(80),
    voiceBox("\"Todo es gris. No el gris de una tormenta, ni el de la ceniza — un gris que parece que siempre estuvo ahí, como si el color nunca hubiera existido en ese lugar. Angelus, todavía muy chico, está sosteniendo la mano de uno de sus padres (a elección del jugador: madre o padre) mientras caminan rápido, buscando una salida que no termina de aparecer. No hay monstruos corriendo, no hay gritos de ataque — solo gente, a la distancia, caminando despacio, en círculos, como buscando algo que perdieron hace mucho y ya ni recuerdan qué era.\""),
    pEmpty(80),
    infoTable([
      ["Momento","Qué intenta Angelus","Tirada","Resultado"],
      ["1 — Buscar la salida","Junto a su familia, intenta encontrar el camino de vuelta entre el gris","Sabiduría o Supervivencia CD 12","Éxito alto: casi encuentran algo — una grieta, una luz — pero se cierra justo antes de llegar. Fallo: se equivocan de camino, pierden tiempo, el gris se hace más denso"],
      ["2 — No soltar la mano","Cuando el gris empieza a tirar de su familia hacia adentro, Angelus se aferra con todas sus fuerzas","Fuerza o Atletismo CD 13","Sin importar el resultado, logra sostenerla un instante más de lo que el gris 'quería' permitir — pero nunca es suficiente"],
      ["3 — El empujón","En el último instante, alguien de su familia empuja a Angelus con todas sus fuerzas hacia la única grieta de salida","Ninguna — elección pura del jugador","El jugador decide qué le dice esa persona en el último segundo, y qué hace o grita Angelus al verse arrancado de ahí a la fuerza"],
    ], 1600, 2400, 1800, 3960),
    pEmpty(80),
    voiceBox("\"La última imagen que Angelus tiene, antes de que la grieta lo expulse hacia el mundo material, es la de su familia quedándose atrás, ya casi indistinguibles del gris que las rodea — no gritando, no luchando contra algo que los ataca, solo... quedándose, mientras él se va. No hubo monstruo al que vencer. No hubo última batalla. Solo una decisión que ellos tomaron por él, en el único segundo que tuvieron para tomarla.\""),
    pEmpty(80),
    noteBox("POR QUÉ ESTO IMPORTA PARA SU FE ACTUAL","Angelus no tenía fe en la Raven Queen en este momento — eso vino después, ya en la aventura de Phandelver. La escena NO incluye ningún consuelo divino. Esa ausencia total de sentido es lo que más adelante lo empuja a necesitar una fe que le diga que los finales SÍ pueden tener valor.","FFF8E7",C.goldDeep),
    pEmpty(80),
    secretBox("CUÁNDO USAR ESTA ESCENA: funciona mejor como cold open de una sesión temprana, o como flashback justo antes de la Escena 2 con el abuelo de los vendedores (sección 14.2.4)."),
    pageBreak(),

    h3("14.2.2 — La Verdad de Fondo (SOLO PARA EL DM)"),
    secretBox("EL PLANO GRIS Y SU ORIGEN: hace mucho tiempo, Ozyr experimentó con la frontera entre planos — intentando entender si la muerte misma podía manipularse. Se descontroló: generó una plaga de no-muertos sin fin, un plano entero donde la muerte deja de funcionar como cierre y se vuelve un loop infinito. Ozyr lo selló y lo abandonó. Es el único experimento que reconoce internamente como un error real."),
    pEmpty(80),
    secretBox("POR QUÉ OZYR LO ABANDONÓ Y POR QUÉ ESTO ES DISTINTO DE TODO LO DEMÁS QUE HACE: es, internamente (nunca lo admite ante nadie, ni siquiera Iarno lo sabe), el único experimento que Ozyr reconoce como un error real y no como una variable aceptable. Lo selló y lo abandonó. A diferencia de Mnemós, al que sigue observando con paciencia científica, el Plano Gris simplemente lo asusta lo suficiente para no volver — es la prueba de que incluso Ozyr tiene límites de lo que está dispuesto a arriesgar. Esto NO debe conectarse de forma explícita con la trama activa de Mnemós en esta campaña: es lore de trasfondo para el arco de Angelus, no una pista hacia el clímax."),
    pEmpty(80),
    secretBox("LA FAMILIA DE ANGELUS Y EL ABUELO: la familia de Angelus quedó atrapada en el loop cuando el plano colapsó. Una sola persona logró escapar por una vía distinta — un anciano que encontró una grieta en el sello de Ozyr en el momento exacto del colapso, y salió con vida, marcado para siempre por lo que vio. Han pasado los años; hoy es muy mayor, vive con su familia (los vendedores ambulantes que la party va a conocer), y rara vez habla del tema."),
    pEmpty(80),
    secretBox("¿SON PARIENTES DE SANGRE? — DEJALO ABIERTO: el documento no resuelve esto a propósito. El reconocimiento físico y de comportamiento (sección 14.2.3) sugiere fuertemente un parentesco de sangre no documentado — quizás una rama familiar separada hace generaciones, quizás coincidencia genética dentro del mismo pueblo de origen. Vos como DM podés decidirlo en el momento que mejor sirva a tu mesa, o dejarlo sin resolver para siempre, incluso después de conocer al abuelo. Ambas opciones son válidas y el documento funciona igual."),
    pEmpty(140),

    h3("14.2.3 — Escena 1: El Encuentro con los Vendedores (PARA MESA)"),
    p("Variante de Encuentro de Camino — usalo en cualquier viaje entre zonas, idealmente después de la zona 2 o 3."),
    pEmpty(80),
    voiceBox("\"En el camino, una familia de mercaderes ambulantes lleva un carro cargado de telas y especias. Es un encuentro comercial normal hasta que Angelus saca algo de su equipo y uno de los vendedores se queda mirándolo fijo, a media frase.\""),
    pEmpty(80),
    infoTable([
      ["Qué reconoce exactamente","Cómo se dispara"],
      ["El objeto","Un objeto del equipo inicial de Angelus — su símbolo sagrado de la Raven Queen, con un grabado o material particular — que el vendedor reconoce porque su abuelo describió algo idéntico contando historias viejas"],
      ["La forma de hablar y moverse","El vendedor nota que Angelus inclina la cabeza de cierta forma particular al pensar, que coincide exactamente con un gesto que su abuelo hace. Sale DESPUÉS del objeto: 'Es que... la forma en que recién inclinaste la cabeza. Mi abuelo hace exactamente eso.'"],
    ], 3200, 6160),
    pEmpty(80),
    p("El vendedor puede ofrecer llevar a Angelus a conocer al abuelo — vive en Neverwinter. Si la mesa no tiene tiempo, puede dar instrucciones para encontrarlo más adelante."),
    pEmpty(140),

    h3("14.2.4 — Escena 2: El Abuelo (PARA MESA)"),
    voiceBox("\"El abuelo es muy mayor, de manos temblorosas pero ojos todavía alertas. No se sorprende tanto como Angelus esperaría al verlo — como si una parte de él hubiera estado esperando este momento desde hace mucho. 'Te pareces a tu...' empieza, y se detiene, sin terminar la frase. 'Hace mucho que no hablo de esto. Pero supongo que ya es hora.'\""),
    pEmpty(80),
    infoTable([
      ["Fragmento del relato","Contenido"],
      ["Cómo era el lugar","'Gris. No oscuro — gris, como un día sin sol que nunca termina. La gente caminaba. No corría, no atacaba como esperarías de los no-muertos de las historias. Solo... caminaba. En círculos, a veces. Como buscando una puerta que no estaba en ningún lado.'"],
      ["Qué pasó con la familia de Angelus","El abuelo vio a la familia pero perdió contacto con ellos en el caos del colapso. No los vio morir directamente; solo sabe que no lograron salir con él. Esto deja un pequeño espacio de incertidumbre — no una confirmación total"],
      ["Cómo escapó","Encontró una grieta — 'un lugar donde el gris se rompía, solo un segundo' — y la cruzó sin pensar. No sabe qué causó esa grieta"],
      ["Lo que nunca pudo explicar","'Sé que no fue un castigo de ningún dios. Y sé que no fue mala suerte. Alguien, o algo, hizo eso. Pasé años queriendo encontrar a quién. Ya no tengo años para seguir buscando. Quizás vos sí.'"],
    ], 2400, 6960),
    pEmpty(80),
    secretBox("ESTO ES TODA LA VERDAD QUE EL ABUELO PUEDE DAR — el QUÉ y el CÓMO, sin el QUIÉN. La otra mitad (el porqué cósmico) viene de la Raven Queen, sección 14.2.7. Ninguna de las dos fuentes debe nombrar a Ozyr."),
    pEmpty(80),
    voiceBox("\"Antes de que Angelus se vaya, el abuelo lo detiene con una mano temblorosa. 'Una cosa más. Cuando salí, no traje nada — no hubo tiempo. Pero sé dónde quedó el bastón de mi esposa. Ella lo talló con sus propias manos, mucho antes de todo esto. No es un objeto mágico ni nada que valga dinero. Pero es lo único de ella que podría quedar en este mundo, y yo ya no tengo piernas para ir a buscarlo.' Describe el lugar: un pueblo, en el límite físico donde el gris se filtró hace años sin llegar a tragárselo del todo — no el plano en sí, sino su cicatriz en este lado.\""),
    pEmpty(140),

    h3("14.2.5 — Parte 1: Buscar la Casa del Abuelo"),
    p("No es un dungeon ni hay enemigos acá — es una búsqueda tranquila con una sola pregunta real: ¿pueden encontrar la casa correcta, y qué queda de ella? El pueblo está en la frontera física donde el Plano Gris se filtró generaciones atrás, sin llegar a abrirse del todo: niebla baja persistente, vegetación descolorida, un silencio que incomoda pero no ahoga. NO es el Plano Gris — es su cicatriz en el mundo material, y por eso es seguro explorarlo sin reabrir nada."),
    pEmpty(80),
    voiceBox("\"Las casas se repiten, una tras otra, todas del mismo gris apagado, todas con la misma puerta entreabierta como si sus dueños fueran a volver en cualquier momento. No hay ruinas, no hay destrucción — todo está exactamente donde quedó, solo descolorido, como una pintura que perdió el sol. El silencio no es total: el viento mueve postigos sueltos, en algún lado, con un ritmo que no termina de sonar natural.\""),
    pEmpty(80),
    cdBox([
      ["Percepción o Supervivencia para reconocer la veleta que describió el abuelo","13","Fallo: recorren varias casas idénticas antes de dar con la correcta — pierden tiempo, sin ninguna otra consecuencia. Pueden reintentar cuantas veces haga falta"],
    ]),
    pEmpty(140),

    h3("La Casa Vacía"),
    voiceBox("\"Adentro, todo sigue como si el tiempo se hubiera detenido a mitad de un día cualquiera. Una mesa puesta para dos, con platos que nunca se retiraron. Una mecedora frente a una chimenea apagada hace generaciones, con un chal todavía colgado del respaldo, deshaciéndose de a hilos. En un jarrón, flores secas que alguna vez fueron de color — ahora son solo forma, sin color que las sostenga. El polvo es espeso pero no violento: nadie entró a romper nada. Solo el tiempo, quedándose.\""),
    pEmpty(80),
    p("El bastón no está a la vista de inmediato — el abuelo recordaba mal, o la casa cambió más de lo que pensaba."),
    pEmpty(60),
    cdBox([
      ["Percepción o Investigación para encontrar el bastón","14","Con éxito, lo encuentran enseguida, apoyado en un rincón, casi exactamente donde el abuelo dijo. Con fallo, tarda más — revisan toda la casa antes de encontrarlo medio escondido bajo una manta que se deshace al tocarla — pero además encuentran, sin buscarla, una carta sin enviar, dirigida a nadie en particular, que el abuelo nunca contó que existía (gancho opcional de roleplay, contenido a elección del DM)"],
    ]),
    pEmpty(80),
    secretBox("EL BASTÓN NO ES MÁGICO — Y ESTÁ BIEN ASÍ: no todo objeto recuperado necesita una propiedad mecánica. Su valor es completamente emocional. Si tu mesa quiere algo mecánico igual, lo más simple: mientras Angelus lo lleve encima (guardado, no como arma), una vez por descanso largo puede tocarlo antes de un ritual o plegaria para tener Ventaja en esa tirada — un pequeño consuelo, no un arma."),
    pEmpty(80),
    noteBox("RECOMPENSA — GUARDIA DE LA REINA CUERVO, ETAPA 1","Al recuperar el bastón y volver con el abuelo, Angelus desbloquea la primera etapa de su vínculo con la Reina Cuervo: una vez por descanso largo, como reacción, si un ALIADO a 9 m cae a 0 PG, puede darle Ventaja en su próxima tirada de salvación de muerte. Todavía no funciona sobre enemigos — eso llega en la Parte 2.","FFF8E7",C.goldDeep),
    pEmpty(140),

    h3("14.2.6 — Parte 2: Dungeon — La Cripta sin Nombres"),
    p("El abuelo, agradecido, menciona algo más: una cripta vieja cerca del pueblo, muertos sin nombre y sin descendencia que nadie visita hace generaciones, con quejidos que a veces se escuchan de noche. No está conectada con el Plano Gris — es un problema propio, mundano, del tipo que un Clérigo de la Muerte puede resolver de verdad. A diferencia de la Parte 1, esto SÍ es un dungeon con combate real."),
    pEmpty(80),

    h3("Área 1 — El Corredor de Entrada"),
    voiceBox("\"La entrada es un corredor angosto tallado directamente en la roca, con nichos a ambos lados — la mayoría vacíos hace mucho, un puñado todavía con huesos que nadie vino a reclamar. El aire es frío de una forma que no tiene que ver con la temperatura. A mitad de camino, sin ruido de aviso, tres siluetas se incorporan desde el piso: esqueletos que no atacan con furia, sino con la persistencia lenta y sin voluntad propia de algo que reacciona al movimiento, no a la presencia.\""),
    pEmpty(80),
    cdBox([
      ["Combate — 3 Esqueletos (CR 1/4 c/u)","—","Estadísticas estándar de Manual de Monstruos. No emboscan: se incorporan apenas el grupo pasa la mitad del corredor, dando una ronda de aviso antes de atacar"],
      ["Alternativa — Angelus expulsa no-muertos (si tiene el rasgo de Clérigo disponible a su nivel)","—","Los 3 Esqueletos se desmoronan sin pelear — una victoria limpia y temática, coherente con su clase"],
    ]),
    pEmpty(140),

    h3("Área 2 — La Grieta del Piso"),
    p("Un tramo de piso colapsado hace años, con escombro suelto entre el corredor y la siguiente cámara. No es un enemigo — es un obstáculo físico."),
    pEmpty(60),
    cdBox([
      ["Destreza (Acrobacias) para cruzar sin caer","12","Fallo: cae parcialmente en la grieta, 1d6 contundente, y debe trepar de vuelta (pierde el turno, sin peligro real de quedar atrapado)"],
    ]),
    pEmpty(140),

    h3("Área 3 — La Cámara de los Olvidados"),
    voiceBox("\"Esta cámara es distinta: hay estantes, no solo nichos, cada uno con un objeto personal — un peine, un dedal, un juguete de madera gastado. Nadie vino jamás a llevarse nada, porque nadie quedó para reclamarlo. El mismo tipo de historia que el brazalete sin reclamar de Dax (sección 9.1). Dos siluetas se materializan entre los estantes, sobresaltadas, como si no esperaran visitas después de tanto tiempo.\""),
    pEmpty(80),
    cdBox([
      ["Religión o Persuasión para hablarles antes de combatir (símbolo sagrado como foco)","13","Con éxito, los 2 Espectros menores (CR 1/2 c/u) se disuelven en paz, sin pelear. Con fallo (o si el grupo prefiere combatir directamente), combate normal — son frágiles, más tristes que peligrosos"],
    ]),
    pEmpty(80),
    noteBox("LOOT DE LA CÁMARA","Entre los objetos de los estantes, uno se puede llevar sin culpa: un guardapelo vacío, sin retrato ni mechón — perteneció a alguien que nadie recuerda ya. Sin valor mecánico, pura textura temática (o 50 po si tu mesa prefiere loot material).","FFF8E7",C.goldDeep),
    pEmpty(140),

    h3("Área 4 — La Cámara Central"),
    voiceBox("\"El corredor se abre a una cámara redonda, más silenciosa que las anteriores. En el centro, un altar simple, sin dedicar a ningún dios en particular — quien lo construyó no llegó a decidir a quién rezarle, o quizás nunca hizo falta decidirlo.\""),
    pEmpty(80),
    p("Sin combate. Aquí Angelus oficia el rito (ver abajo)."),
    pEmpty(80),
    voiceBox("\"Angelus enciende el altar con lo poco que tiene — una vela, quizás, o solo su símbolo sagrado en alto — y dice en voz alta los nombres que sí conoce (los del abuelo, los suyos propios, cualquiera que la mesa quiera nombrar), y después, con la misma seriedad, dice: 'Y por los que no tienen nombre que yo pueda decir: también los recuerdo.' El aire de la cripta cambia — no dramáticamente, pero cambia.\""),
    pEmpty(80),
    secretBox("NO HAY TIRADA PARA EL RITO EN SÍ — es una decisión de rol, no un desafío mecánico. La Cripta sin Nombres es la versión chica y accionable de un tema grande de la campaña (honrar lo desconocido — ver 2.6 y 9.1), pero para Angelus se resuelve con una acción concreta, no con una pregunta sin respuesta. Coherente con darle a él victorias claras."),
    pEmpty(80),
    noteBox("RECOMPENSA — GUARDIA DE LA REINA CUERVO, ETAPA 2","El vínculo crece: ahora, cuando la reacción se activa por un ENEMIGO cayendo a 0 PG a 9 m (en vez de un aliado), Angelus puede imponer Desventaja en el próximo ataque o tirada de salvación de una criatura enemiga a su elección dentro de 9 m. Sigue siendo 1/descanso largo — la frecuencia mejora recién en la Parte 4.","FFF8E7",C.goldDeep),
    pEmpty(140),

    h3("14.2.7 — Parte 3: Las Visiones de la Raven Queen (PARA MESA)"),
    p("Tres visiones fragmentarias para repartir a lo largo de la campaña, una después de la Parte 1, otra después del dungeon de la Parte 2, y una de cierre opcional. Son simbólicas, nunca explicaciones directas — Angelus las recibe dormido, y se despierta sin poder explicarlas del todo."),
    pEmpty(80),
    secretBox("POR QUÉ A LA RAVEN QUEEN LE IMPORTA: el Plano Gris es una herida en su propio dominio — un lugar donde la muerte se rompió y dejó de funcionar. Para ella, eso es un insulto directo a lo que sostiene."),
    pEmpty(140),

    h3("Visión 1 — El Cuervo que no Puede Posarse (después de la Parte 1)"),
    voiceBox("\"Angelus sueña con un cielo sin color, parecido al del día del colapso pero sin la gente caminando. Un solo cuervo vuela en círculos sobre una rama gris y quieta, e intenta posarse una y otra vez — sus garras rozan la madera y resbalan, como si la rama no terminara de estar ahí del todo. El cuervo no se cansa, no se rinde, simplemente lo vuelve a intentar, una vez, y otra, y otra. Angelus se despierta antes de ver si lo logra, con la sensación clara de que 'algo no terminó bien, en algún lugar, hace mucho tiempo' — y que todavía no termina.\""),
    pEmpty(80),
    secretBox("QUÉ SIGNIFICA (PARA VOS, DM): el cuervo es la propia Raven Queen, o una extensión de su atención — no puede posarse del todo en el Plano Gris porque ahí la muerte no funciona como debería, y ella no tiene dominio real sobre un lugar que rompe sus propias reglas. Es su forma de decirle a Angelus, sin palabras, que el problema le importa genuinamente, no solo como curiosidad."),
    pEmpty(140),

    h3("Visión 2 — La Balanza Detenida (después de la Parte 2)"),
    voiceBox("\"Una balanza enorme, hecha de huesos pulidos, ocupa el centro del sueño. Un plato sube y baja con un ritmo tranquilo, natural. El otro está completamente quieto, cubierto de óxido, como si llevara siglos sin moverse. Una voz — no exactamente la de la Raven Queen, algo más antiguo, hablando a través de ella — dice: 'Alguien tocó lo que no debía. Y dejó la balanza así.' Angelus mira el plato oxidado, y por un instante lo ve moverse, apenas, un centímetro, antes de quedar quieto otra vez. La misma voz, ahora más cerca de la Raven Queen: 'Vos, en cambio, devolviste paz donde nadie la pedía. Eso también lo siento. No arregla la balanza. Pero lo siento.'\""),
    pEmpty(80),
    secretBox("QUÉ SIGNIFICA: la balanza detenida ES el Plano Gris — un lugar donde el equilibrio natural de la muerte se rompió y no se cura solo. El pequeño movimiento que Angelus ve (el plato moviéndose un centímetro) es una señal directa de que lo que hizo en La Cripta sin Nombres SÍ tuvo efecto en algo más grande de lo que él imagina — sin explicar del todo qué ni cuánto. Dejalo ambiguo: es una recompensa emocional, no una pista mecánica."),
    pEmpty(140),

    h3("Visión 3 — El Contraste (opcional, para cierre o puente al clímax)"),
    voiceBox("\"La última visión es distinta a las demás — no hay símbolos esta vez, hay una imagen casi directa: un hombre sentado a una mesa, con libros y frascos alrededor, sin nombre ni rostro claro (Angelus no puede describirlo después, por más que lo intente). La Raven Queen no lo señala como enemigo ni como nada en particular. Solo dice: 'Este busca corregir el dolor borrándolo. Aquello que rompió tu plano buscaba algo distinto, y peor: jugar con el final mismo. No son la misma herida. Pero ambas son heridas que yo siento.'\""),
    pEmpty(80),
    secretBox("CUÁNDO USARLA Y QUÉ NO HACER: usala cuando la mesa decida cerrar o pausar el arco, idealmente cerca de cuando el nombre 'Mnemós' ya se conoce (después de Hotenow, sección 6.7) pero SIN nombrarlo acá tampoco — la imagen es deliberadamente borrosa. Esto NO es una pista hacia la identidad de Mnemós ni de Ozyr: es una confirmación emocional de que el dolor de Angelus y el conflicto central de la campaña están relacionados temáticamente, sin estar conectados en la trama. No fuerces la conexión más allá de esta única frase."),
    pEmpty(140),

    h3("14.2.8 — Parte 4: Cierre — La Vigilia que Continúa"),
    p("Semanas o sesiones después (a criterio del DM), el abuelo muere — de viejo, en paz, sin drama ni combate."),
    pEmpty(80),
    voiceBox("\"Cuando llega la noticia, no es una sorpresa — era de esperar, y de alguna forma eso ayuda. La familia de vendedores le cuenta a Angelus que, en sus últimos días, el abuelo volvió a tener el bastón cerca todo el tiempo, y que habló, más de una vez, de 'el chico que sigue la vigilia'. Nadie tiene que explicarle a Angelus qué quiso decir con eso.\""),
    pEmpty(80),
    noteBox("RECOMPENSA — GUARDIA DE LA REINA CUERVO, ETAPA 3 (completa)","El vínculo llega a su forma final: deja de necesitar descanso para recargarse. Se vuelve una reacción normal, disponible siempre que la condición se cumpla (una criatura a 9 m cae a 0 PG), sin límite de usos por descanso. Ambos efectos (Ventaja en salvación de muerte para un aliado, o Desventaja impuesta a un enemigo) siguen disponibles, elegidos en el momento según quién cayó.","FFF8E7",C.goldDeep),
    pageBreak(),

    // ============ GREYSKULL ============
    h2("14.3 El Arco de Greyskull — Sangre Ancestral de Gigantes"),
    p("Basado en el trasfondo real de Greyskull: quiere tener familia de gigantes, su familia humana actual vive con gigantes, y hay deseo expreso de desarrollar un rasgo relacionado. Greyskull es interpretada por la jugadora adulta del grupo — las dos escenas de apertura que siguen están pensadas con algo más de matiz emocional, acorde a esa diferencia."),
    pEmpty(80),

    h3("14.3.1 — Escena de Apertura 1 (Cold Open): El Gigante que la Encontró"),
    p("Distinta en estructura a las de Hola y Angelus — no es una tragedia, es el origen de una pertenencia. La jugadora controla a Greyskull joven (sugerido: 16-17 años), antes de que su familia decidiera vivir entre gigantes."),
    pEmpty(80),
    p("Contexto: Greyskull se separó de un grupo de viaje durante una tormenta en las faldas de una cordillera. No fue un descuido infantil — ya era lo bastante capaz para que nadie esperara que se perdiera, lo cual hace que el miedo venga mezclado con vergüenza. Lleva horas caminando, de noche, sin fuego."),
    pEmpty(80),
    voiceBox("\"El frío de la montaña corta distinto al frío de cualquier otro lugar — no es solo temperatura, es la sensación de que el aire mismo se volvió más fino, más hostil. Greyskull lleva horas caminando, y el miedo ya dejó de ser agudo: se volvió un cansancio pesado, el tipo de miedo que ya no grita, solo pesa sobre los hombros como una carga física más. Las piedras bajo sus pies son cada vez más grandes, más afiladas. En algún momento dejó de reconocer el terreno del todo. Y entonces, el suelo tiembla. No es un terremoto. Son pasos. Grandes, lentos, deliberados, cada uno separado del siguiente por un silencio que se estira demasiado.\""),
    pEmpty(80),
    p("Dale un momento a la jugadora para reaccionar antes de seguir. Después:"),
    pEmpty(80),
    voiceBox("\"De entre las rocas más oscuras, algo se mueve que es demasiado grande para ser cualquier animal que ella conozca. La silueta termina de revelarse contra la poca luz de las estrellas: un gigante, enorme, con la piel curtida como corteza de árbol viejo, deteniéndose a varios metros de distancia. No avanza más. Y entonces, despacio, muy despacio, abre las manos —vacías, sin armas, las palmas hacia arriba. Greyskull siente algo extraño en las manos — un impulso, casi animal, de cerrarlas sobre la piedra más cercana y afilada que pueda alcanzar. No es valentía. Es puro instinto de pelear antes de que algo la aplaste primero.\""),
    pEmpty(80),
    p("MOMENTO 1 — EL INSTINTO DE PELEAR: pedile a la jugadora una tirada de Sabiduría CD 14. La dificultad no está en correr — está en contener algo que sube desde más adentro de lo que el miedo común explica: un instinto de atacar primero."),
    pEmpty(60),
    infoTable([
      ["Resultado","Qué pasa"],
      ["ÉXITO","Greyskull logra quedarse quieta justo a tiempo, con la piedra todavía apretada en la mano pero sin levantarla. Nota las manos del gigante abiertas. No es sumisión lo que sintió al contenerse — es haber elegido, con esfuerzo real, no atacar primero"],
      ["FALLO","El instinto gana: lanza la piedra, o grita una amenaza vacía. El gigante ni se inmuta pero se detiene por completo, agachándose más despacio todavía, las manos ahora más explícitamente abiertas. Greyskull se queda con la respiración agitada, avergonzada de su propia reacción"],
    ], 2400, 7160),
    pEmpty(80),
    voiceBox("\"'No vine a hacerte daño,' dice el gigante, en Común, con un acento pesado pero claro. Su voz es profunda pero no ruge: habla como quien sabe que su propio volumen normal ya es demasiado para oídos humanos, y se esfuerza por bajarlo. 'Hace frío. Y vos sola, tan lejos de donde debería haber gente como vos. Eso no es seguro, ni para los gigantes ni para los suyos.' Se queda en cuclillas, manteniendo la distancia, esperando.\""),
    pEmpty(80),
    p("MOMENTO 2 — EL ORGULLO DE NECESITAR AYUDA: el gigante ofrece llevarla a un refugio cercano. Pedile una tirada de Carisma o Sabiduría CD 13. No es sobre si confía en el gigante — sino sobre tragarse el orgullo de necesitar ayuda de algo que toda su vida le enseñaron a temer."),
    pEmpty(60),
    infoTable([
      ["Resultado","Qué pasa"],
      ["ÉXITO","Greyskull encuentra la forma de aceptar sin que se sienta como una rendición — quizás lo dice como si fuera ella quien le hace un favor. Acepta sintiendo que eligió, no que se resignó"],
      ["FALLO","El orgullo gana por un momento: duda, quizás dice que puede sola, quizás intenta caminar unos pasos en otra dirección antes de que el cansancio la haga volver. Lo hace con el cuerpo tenso, con una vergüenza extra que tarda más en disolverse"],
    ], 2400, 7160),
    pEmpty(80),
    voiceBox("\"El refugio es una hendidura entre dos rocas enormes, apenas visible desde afuera. Hace fuego con una facilidad que a Greyskull le resulta casi cómica, y lo comparte sin pedir nada. Se sienta del otro lado del fuego, lo suficientemente lejos para no abrumarla con su tamaño, y se queda despierto toda la noche. Por la mañana, la guía de vuelta hacia terreno conocido.\""),
    pEmpty(80),
    voiceBox("\"'No hizo falta nada especial,' dice el gigante, casi desconcertado de que ella insista en darle las gracias. 'Estabas perdida. Yo sabía el camino. Eso es todo.' Se da vuelta para irse, y solo entonces agrega: 'Las historias que cuentan sobre nosotros nunca incluyen esta parte. Quizás deberían.'\""),
    pEmpty(80),
    secretBox("POR QUÉ ESTO IMPORTA: es el origen emocional de por qué ella ama esa cultura. El instinto de pelear que sintió (Momento 1) es el primer eco de los 'instintos que no son suyos' de sección 14.3.3. El orgullo que tuvo que tragarse (Momento 2) conecta con por qué persigue tan activamente la fuerza y el linaje de gigante hoy."),
    pEmpty(140),

    h3("14.3.2 — Escena de Apertura 2 (Cold Open): El Sueño de Ser Más Grande"),
    p("No es un recuerdo de algo que pasó, es un SUEÑO, jugado en el presente narrativo del sueño mismo. Funciona como un 'preview' emocional del rasgo de Sangre Ancestral (sección 14.3.5), antes de que sea real. Con TRES momentos de tirada en vez de dos."),
    pEmpty(80),
    warningBox("CUÁNDO USARLA: en algún descanso largo después de que Greyskull ya empezó a sentir 'la sensación del fuego' o los 'instintos que no son suyos' (sección 14.3.3), pero antes de llegar a Hotenow. Es el puente entre las señales tempranas y la confirmación de Korrund."),
    pEmpty(80),
    voiceBox("\"El sueño no empieza de golpe — se desliza, como cuando el agua tibia sube despacio alrededor del cuerpo. Greyskull está de pie en algún lugar que no termina de reconocer: piedra roja bajo los pies, un cielo sin estrellas pero no oscuro, una luz pareja que no viene de ningún sol. Y entonces nota sus propias manos. Son enormes. No deformes, no monstruosas — simplemente del tamaño correcto para algo que no es ella, o que es ella de otra forma. Hay una sensación que no recuerda haber sentido nunca despierta: la de PERTENECER por completo al propio cuerpo.\""),
    pEmpty(80),
    p("MOMENTO 1 — PROBAR EL CUERPO NUEVO: antes de que aparezca nadie más, dale a la jugadora la oportunidad de intentar algo físico. Pedile una tirada de Fuerza CD 12."),
    pEmpty(60),
    infoTable([
      ["Resultado","Qué pasa"],
      ["ÉXITO","El cuerpo responde exactamente como ella espera, sin esfuerzo. Una euforia pura y física"],
      ["FALLO","El cuerpo no responde del todo bien todavía — la sensación incómoda de que este cuerpo todavía no es completamente suyo"],
    ], 2400, 7160),
    pEmpty(80),
    voiceBox("\"Frente a ella hay una figura. No es del todo un gigante — demasiado esbelta — ni del todo humana: cada vez que Greyskull intenta enfocar sus rasgos, algo en ellos se reordena. 'Esto podría ser todo lo que hay,' dice la figura, o quizás no dice nada y Greyskull simplemente entiende sin palabras. 'No habría que volver. No habría que esforzarse de nuevo por ser suficiente. Solo esto. Solo quedarse.' Y algo en el sueño mismo empieza a tirar de ella hacia esa puerta — no con violencia, con la suavidad lenta con la que el agua sube, pero ahora hacia adentro.\""),
    pEmpty(80),
    p("MOMENTO 2 — RESISTIR LA CORRIENTE: el sueño mismo empieza a arrastrarla hacia quedarse, sin pedirle permiso. Pedile una tirada de Sabiduría o Constitución CD 14 para que llegue al momento de elegir siendo ella misma quien decide."),
    pEmpty(60),
    infoTable([
      ["Resultado","Qué pasa"],
      ["ÉXITO","Greyskull siente la corriente tirando de ella, la nota con claridad, y logra plantarse el tiempo suficiente para que la decisión que viene sea genuinamente suya"],
      ["FALLO","La corriente la arrastra un poco más de lo que hubiera querido antes de que logre anclarse — unos segundos donde casi no es ella quien decide. Logra recuperar el control justo a tiempo, con la sensación incómoda de haber estado más cerca de perderse de lo que le gustaría admitir"],
    ], 2400, 7160),
    pEmpty(80),
    p("MOMENTO 3 — LA DECISIÓN FINAL: sin tirada, pura decisión de la jugadora. ¿Se queda un momento más, o elige volver?"),
    pEmpty(80),
    voiceBox("\"Si decide quedarse: el sueño se estira, generoso, un momento más. Greyskull camina por ese paisaje imposible hasta que la luz empieza a desvanecerse de los bordes hacia el centro. La figura no la detiene. Solo observa.\n\nSi decide volver: apenas lo piensa, el sueño cede de inmediato. La figura inclina la cabeza — algo parecido al respeto — justo antes de que todo se disuelva en gris.\n\nDespierta de golpe, en su propio cuerpo de siempre, con la sensación física real de extrañar algo que nunca tuvo. Las manos le parecen, por un instante completo, demasiado chicas — como ponerse de nuevo unos zapatos un número más chico de lo que recordaba.\""),
    pEmpty(80),
    secretBox("CONEXIÓN MECÁNICA: cuando finalmente desbloquee la Etapa 2 o 3 del rasgo real, podés usar la línea 'esto ya lo sentiste una vez, ¿te acordás?' — es uno de los momentos más fuertes posibles para ese hito."),
    pEmpty(140),

    h3("14.3.3 — Señales Tempranas (PARA MESA, desde el inicio de la campaña)"),
    infoTable([
      ["Señal","Cuándo se activa","Cómo se siente"],
      ["1 — La Sensación del Fuego","Cerca de fuego intenso o de gigantes — Brasas Iracundas, la forja de Dax en Neverwinter, cualquier fragua o volcán","No es dolor — es reconocimiento. Un calor que no quema, una sensación de 'estar cerca de algo familiar' que Greyskull no puede explicar"],
      ["2 — Instintos que no son Suyos","En momentos de combate de alto estrés (en 1/3 o menos de sus PG máximos, o enfrentando a un enemigo mucho más grande que ella)","Un movimiento, una forma de plantarse o sostener el arma a dos manos, que Greyskull no recuerda haber aprendido — demasiado grande, demasiado seguro. Mecánicamente no otorga nada todavía — es pura narración"],
    ], 2400, 3000, 3960),
    pEmpty(80),
    noteBox("FRECUENCIA SUGERIDA","No abuses de esto — 1 vez cada 2-3 sesiones es suficiente para que se sienta como un patrón sin saturar.","FFF8E7",C.goldDeep),
    pEmpty(140),

    h3("14.3.4 — La Confirmación de Korrund y el Legado de Greyskall (4 Partes)"),
    voiceBox("\"Korrund se detiene a media frase al escuchar el nombre de Greyskull. Por primera vez desde que el grupo llegó a Hotenow, su expresión cambia a algo que no es ira ni dolor — es sorpresa genuina. 'Ese nombre... no es de aquí. Es de antes. De las historias que cantaban los gigantes antes de que yo naciera siquiera.' Hace una pausa larga. 'Si lo que dicen las viejas canciones es cierto, hubo un Greyskall — así lo decían los más viejos, con esa pronunciación — que evitó que una erupción destruyera un asentamiento entero. Dicen muchas cosas. No sé cuántas son verdad.'\""),
    pEmpty(80),
    secretBox("EL LORE BASE CONFIRMADO: Greyskall redirigió el flujo de lava de una erupción en Hotenow para salvar un asentamiento gigante. No pudo hacerlo sola — necesitó al enano Baldrek Cenicilla para identificar y romper correctamente el conducto subterráneo (conocimiento minero que ningún gigante tenía). La canción gigante borró a Baldrek por orgullo de raza, no por maldad. Rhen Brasacorta conoce fragmentos de la versión enana. El costo personal del pacto: Greyskall prometió a Baldrek que su linaje respondería al linaje Cenicilla si alguna vez necesitara ayuda — pacto de sangre, sellado en el arma. Cuatro generaciones después, nadie lo activó todavía… hasta ahora."),
    pEmpty(80),
    p("Esto abre la misión global 'El Legado de Greyskall' — 4 partes repartidas a lo largo de la campaña, con ambigüedad real entre fuentes y una decisión moral al final."),
    pEmpty(100),

    h3("Parte 1 — El Canto de Korrund (Hotenow)"),
    p("Korrund canta la versión gigante de la leyenda. Es hermosa y está llena de orgullo de raza — y tiene un hueco deliberado que un oyente atento puede notar."),
    pEmpty(60),
    voiceBox("\"En las laderas del fuego eterno,\ncuando la tierra quiso tragarse el cielo,\nGreyskall llegó sola al corazón del volcán\ny dobló la montaña con sus manos.\nNi el fuego la quemó, ni la piedra la detuvo,\nporque llevaba en la sangre lo que los gigantes llevan en los huesos.\nDonde el fuego y la piedra se encuentran,\ndejó su marca para que el mundo no olvidara.\nGreyskall. Greyskall. El volcán recuerda su nombre.\""),
    pEmpty(80),
    cdBox([
      ["Historia para notar que el canto salta de 'llegó al conducto' a 'salvó el asentamiento' sin explicar el cómo","14","Oyen la leyenda completa pero no detectan el hueco — la pista de Rhen (Parte 2) sigue disponible"],
    ]),
    p("Con éxito en la tirada: el personaje nota la elipsis y puede preguntarle a Korrund directamente. Él responde con honestidad que la versión completa 'la cantaban los más viejos, y ya no quedan muchos viejos'. El estribillo 'donde el fuego y la piedra se encuentran' es la pista críptica que conecta con las Galerías Profundas (Parte 4)."),
    pEmpty(100),

    h3("Parte 2 — Rhen Brasacorta y la Versión Enana (Hotenow)"),
    p("Si el grupo menciona el nombre 'Cenicilla' o 'Baldrek' cerca de Rhen (puede ser la misma sesión o una posterior), él comparte lo que sabe en dos capas:"),
    pEmpty(60),
    voiceBox("\"FRAGMENTO 1 — el nombre y el lugar: 'Cenicilla. Sí, ese nombre lo conozco. Eran del gremio de aquí, del volcán, hace generaciones. El viejo Durven — murió hace diez años, era el más viejo del campamento cuando yo llegué — mencionaba a veces que los Cenicilla se fueron a las Minas de Karak Dûm, al sureste. Dijo que se fueron con mala cara, sin despedirse bien. No sé si siguen ahí. Hace mucho.'\""),
    pEmpty(60),
    voiceBox("\"FRAGMENTO 2 — dar solo si el grupo pregunta más: 'Lo raro es que hace dos inviernos, vino al campamento un mensajero. Enano, viejo, sin apellido dado. Preguntaba si alguien conocía a una guerrera del nombre Greyskull. No dejó mensaje, no dejó nombre propio. Se fue cuando le dijimos que no sabíamos de nadie así. No volví a pensar en eso hasta ahora que mencionás el nombre.'\""),
    pEmpty(80),
    noteBox("QUÉ AÑADE ESTA PARTE","Confirma el hueco de la canción (Baldrek existió y tuvo un rol), da el nombre del clan Cenicilla, da la ubicación vaga de Karak Dûm, y siembra que los Cenicilla también están buscando a Greyskull — el pacto corre en los dos sentidos.","FFF8E7",C.goldDeep),
    pEmpty(100),

    h3("Parte 3 — Los Tres Susurros (Bosque de Neverwinter)"),
    p("Si el grupo pregunta directamente a los Tres Susurros sobre gigantes antiguos o sobre Greyskall, responden con un acertijo propio — esta vez más específico que los seis estándar (sección 7.8), porque el vínculo de sangre de un PJ presente los enternece."),
    pEmpty(60),
    voiceBox("\"Busca donde el fuego nació dos veces:\nuna vez del corazón de la tierra,\nuna vez de las manos de quien prometió.\nLa firma de dos manos que forjaron una sola cosa\nduerme donde nadie vuelve a buscar\nporque todos creen haberlo visto ya.\""),
    pEmpty(80),
    secretBox("SOLUCIÓN DEL ACERTIJO: 'donde el fuego nació dos veces' = la cámara volcánica de las Galerías Profundas (dungeon opcional, sección 11.4) — el fuego natural del volcán Y el fuego del pacto de Greyskall. 'La firma de dos manos que forjaron una sola cosa' = los dos símbolos grabados en el Martillo de la Deuda (marca de Greyskall + marca de los Cenicilla). 'Donde nadie vuelve a buscar porque todos creen haberlo visto ya' = una cámara oculta en las Galerías que el grupo ya visitó (o podría visitar). Hay que volver con este nuevo contexto."),
    pEmpty(60),
    cdBox([
      ["Historia o Arcanos para decodificar el acertijo","14","Los Susurros dan una pista adicional pero cobran un precio menor (a criterio del DM)"],
    ]),
    pEmpty(100),

    h3("Parte 4 — El Hallazgo en las Galerías y la Decisión Moral"),
    p("El grupo vuelve a las Galerías Profundas (Área 4, junto al cristal grande) con la pista de los Tres Susurros. Una grieta en la roca volcánica, invisible sin esa pista específica, lleva a una cámara oculta."),
    pEmpty(60),
    cdBox([
      ["Investigación para encontrar la grieta (solo con la pista de los Susurros)","15","No la encuentran en esta visita — pueden volver con más información"],
    ]),
    pEmpty(60),
    voiceBox("\"Una hendidura en la roca volcánica, apenas lo suficientemente ancha para pasar de costado. Adentro, una cámara pequeña, sin lava, sin cristales — solo piedra vieja y fría. En el centro, sostenido por dos soportes de roca tallados a mano, hay un martillo. Un maul de roca volcánica negra, más ligero de lo que debería ser para su tamaño, con el mango envuelto en cuero de bestia ígnea todavía rojizo. En la cabeza del martillo, grabados con precisión, dos símbolos: uno que el grupo puede reconocer como la marca de Greyskall (la misma del canto de Korrund), y uno que no conocen — más geométrico, más técnico, claramente de otro estilo. Entre los dos símbolos, en giant arcaico, una inscripción.\""),
    pEmpty(80),
    noteBox("TEXTO DEL PACTO EN GIANT ARCAICO (con traducción)",
      "Giant: 'Dûm-Greyskall verak Cenicilla-Baldrek. Iirn thurak, iirn thurak. Karak shan thurak.'\n\nTraducción (Logos puede hacerla, o Historia CD 16): 'La mano de Greyskall responde a la mano de Cenicilla-Baldrek. En la necesidad, en la necesidad. El clan llama, el clan responde.'",
      "E8F8F8", C.tealDark),
    pEmpty(80),
    p("Al tomar el martillo, Greyskull siente que el símbolo de los Cenicilla está frío — no responde todavía. La Etapa 1 del arma se activa al instante (ver sección 14.3.6). La Etapa 2 requiere que el pacto se honre. Aquí la mesa debe decidir:"),
    pEmpty(60),
    infoTable([
      ["Camino","Qué implica","Qué desbloquea"],
      ["1 — Honrar el pacto activamente","Buscar a los Cenicilla en Karak Dûm y responder a lo que necesiten, sin conocer primero la magnitud del pedido","Etapa 2 del arma. El símbolo de los Cenicilla 'responde' al momento de decidir honrarlo"],
      ["2 — Ignorarlo por ahora","Quedarse con el arma sin buscar a los Cenicilla — tenerla como objeto pero no como legado","Etapa 1 activa indefinidamente. Memoria de la Roca NO se activa hasta cerrar el círculo"],
      ["3 — Buscarlos para renegociar","Ir a Karak Dûm no para honrar el pacto ciegamente, sino para conocer el problema y decidir con información completa","Igual de válido que el Camino 1 — Etapa 2 se activa cuando Dûrin reconozca el pacto, sin importar la motivación inicial"],
    ], 1800, 3200, 4360),
    pEmpty(140),

    h3("14.3.5 — Rasgo de Sangre Ancestral (Mecánica)"),
    p("Tres etapas desbloqueadas por hitos narrativos del arco. Las etapas del rasgo y del Martillo de la Deuda (sección 14.3.6) se alinean deliberadamente — si ambas llegan al mismo tiempo, el momento es más poderoso."),
    pEmpty(80),
    infoTable([
      ["Etapa","Se desbloquea cuando...","Beneficio mecánico"],
      ["1 — Reconocimiento","Korrund (o cualquier gigante) confirma el linaje. Coincide con encontrar el Martillo de la Deuda (Etapa 1 del arma activa desde ese momento)","Ventaja en tiradas sociales con gigantes o gigantkin (Persuasión, Perspicacia, Intimidación). Resistencia menor al fuego: el primer punto de daño de fuego por combate se reduce a 0"],
      ["2 — Despertar","Al conocer a los Cenicilla y que Dûrin reconozca el pacto, o al nivel 9 — lo que ocurra primero. Coincide con Etapa 2 del arma (Memoria de la Roca activa)","Alcance Ancestral: arma cuerpo a cuerpo principal gana +1,5 m de alcance. Empuje de Gigante: 1 vez por combate, un ataque cuerpo a cuerpo exitoso puede forzar al objetivo a hacer Salvación de Fuerza (CD = 8 + bono de competencia + mod de Fuerza de Greyskull) o ser derribado, sin acción adicional"],
      ["3 — Manifestación","Al cerrar el arco completo (resolver el problema de los Cenicilla en Karak Dûm), o al nivel 13 — lo que ocurra primero. Coincide con Etapa 3 del arma","Cambio físico menor permanente: Greyskull crece unos centímetros, su voz se vuelve levemente más profunda, sus rasgos se endurecen (puramente cosmético). Resistencia al fuego COMPLETA. Empuje de Gigante mejorado: 2 veces por combate. Piel de la Montaña: como reacción a un golpe crítico recibido, puede reducirlo a daño normal (cancela los dados extra del crítico). 1/descanso largo. Ira Contenida: cuando Greyskull cae por primera vez a la mitad de sus PG máximos en un combate, todas sus tiradas de daño cuerpo a cuerpo ese turno son el valor máximo del dado (sin tirar — se toma el máximo). 1/descanso largo"],
    ], 1400, 3200, 5360),
    pEmpty(80),
    secretBox("Si tu mesa decide NO completar la misión de los Cenicilla del todo, podés otorgar las etapas por hitos alternativos (tiempo pasado en Hotenow, momentos de vínculo con Korrund, decisión del DM). Lo importante es que la Etapa 3 llegue cerca del final de la campaña — el pago emocional debe coincidir con el clímax."),
    pEmpty(140),

    h3("14.3.6 — El Martillo de la Deuda (Objeto en 3 Etapas)"),
    p("El arma de Greyskall — un maul de roca volcánica negra, más ligero de lo que debería ser, con dos símbolos grabados: la marca de Greyskall y la marca de los Cenicilla. Las tres etapas se desbloquean en paralelo con el rasgo de Sangre Ancestral. Es un arma y un arco a la vez."),
    pEmpty(80),
    warningBox("REGLA DE SINTONÍA: el Martillo de la Deuda solo puede ser usado por Greyskull — está sintonizado por sangre al linaje de Greyskall. Otro personaje puede cargarlo, pero no puede activar ninguna de sus propiedades mágicas. Si Greyskull muere permanentemente, el martillo vuelve a ser un maul ordinario hasta que alguien del linaje lo reclame."),
    pEmpty(80),

    h3("Etapa 1 — Al encontrarlo en las Galerías (activa inmediatamente al tomarlo)"),
    infoTable([
      ["Propiedad","Detalle"],
      ["Estadísticas base","Maul +2. Daño: 2d6+2 contundente (+ modificador de Fuerza)"],
      ["Sensibilidad de la Roca (pasivo)","Ventaja en tiradas de Percepción para detectar: estructuras inestables, trampas en roca, pasajes ocultos en piedra, o irregularidades en suelo de piedra natural o trabajado"],
      ["Memoria de la Roca","NO activa todavía. El símbolo de los Cenicilla está frío — no responde hasta que el pacto se honre (Etapa 2)"],
    ], 2800, 6560),
    pEmpty(80),

    h3("Etapa 2 — Al conocer a los Cenicilla y que Dûrin reconozca el pacto"),
    p("(Incluye todo lo de Etapa 1, más:)"),
    pEmpty(60),
    infoTable([
      ["Propiedad","Detalle"],
      ["Estadísticas mejoradas","Maul +3. Daño: 2d6+3 contundente (+ mod Fuerza)"],
      ["+1d6 fuego (condicional)","Daño adicional contra criaturas de piedra, tierra o no-muertos (el calor del volcán que recuerda)"],
      ["Memoria de la Roca (activa)","Acción, 1 vez por descanso largo. Apoya el martillo contra cualquier superficie de piedra o mineral. Tirada de Historia: CD 10 = última semana en ese lugar; CD 14 = últimos meses o años; CD 18 = décadas o generaciones; CD 22 = la memoria más profunda de la piedra (antes de que hubiera gente). Con éxito: imagen o sensación breve, fragmentada, sensorial — no una descripción completa. Con fallo: el uso se consume igualmente, la piedra habló pero en un idioma que no pudo descifrar"],
    ], 2800, 6560),
    pEmpty(80),

    h3("Etapa 3 — Al cerrar el arco completo (resolver el problema de los Cenicilla)"),
    p("(Incluye todo lo de Etapas 1 y 2, más:)"),
    pEmpty(60),
    infoTable([
      ["Propiedad","Detalle"],
      ["Cambio visual del arma","El símbolo de los Cenicilla desarrolla un brillo dorado-rojizo permanente — el pacto de sangre cumplido"],
      ["Estadísticas","Maul +3 (el bonus no sube — la diferencia está en las propiedades nuevas)"],
      ["Resistencia al daño de fuego","Completa y permanente mientras lleve el martillo (se apila con la resistencia completa del rasgo Etapa 3 si ambas llegan juntas)"],
      ["El Volcán Recuerda (1/descanso largo)","Como acción adicional antes de un ataque cuerpo a cuerpo: ese ataque, si impacta, hace +4d6 daño de fuego adicional. Narrado como un pulso de calor volcánico que sube por el mango al momento del golpe — evoca la hazaña original de Greyskall. Puede combinarse con el +1d6 de fuego estándar contra piedra/tierra/no-muertos"],
      ["Juramento del Pacto (1/descanso largo)","Cuando un aliado visible cae a 0 PG, Greyskull puede usar su reacción para golpear el suelo con el martillo. Todos los aliados en 9 m reciben Ventaja en sus tiradas de salvación de muerte hasta el inicio del próximo turno de Greyskull, y el aliado caído puede tirar inmediatamente su primera tirada de salvación de muerte. Representa el 'responder cuando alguien necesita ayuda' del pacto, ahora generalizado a toda la party"],
    ], 2800, 6560),
    pEmpty(80),
    secretBox("EL ARCO COMPLETO EN UNA LÍNEA: Greyskull encuentra el arma de su ancestral, descubre que no puede usarla completamente hasta honrar una deuda que no sabía que existía, honra esa deuda enfrentando algo difícil, y el arma se convierte en la expresión mecánica de quién es al final de la campaña. El Juramento del Pacto en Etapa 3 es deliberadamente el rasgo más 'de equipo' de todos — Greyskull llega al final siendo alguien que protege, no solo alguien que golpea."),
    pageBreak(),

    h3("14.3.7 — La Misión de los Cenicilla (Karak Dûm)"),
    p("Si el grupo decide honrar el pacto (o al menos investigarlo), viajan a Karak Dûm — una mina enana al sureste de Hotenow, activa pero en problemas. Lo que encuentran ahí es el cierre del arco de Greyskall y el desbloqueo de la Etapa 3 del rasgo y del arma."),
    pEmpty(80),

    h3("El Clan Cenicilla — Los Tres Miembros Activos"),
    infoTable([
      ["NPC","Quién es","Frase característica"],
      ["Dûrin Cenicilla (~70 años, el líder)","Conoce el pacto completo de memoria — se lo transmitió su abuela. Desconfiado pero desesperado: el mensajero que mandó hace dos inviernos nunca trajo respuesta. Al ver el arma (el Martillo de la Deuda), cambia de actitud inmediatamente. Habla poco, pesa cada palabra. Es el tipo de enano que te mira a los ojos más tiempo del cómodo antes de hablar.","'Nosotros cumplimos. Siempre cumplimos.'"],
      ["Mira Cenicilla (~40 años, la pragmática)","Más pragmática que Dûrin — menos apegada al pacto por honor y más por necesidad real. Es quien trabaja en la mina todos los días y quien mejor conoce el problema. La que puede guiar al grupo dentro de Karak Dûm. Mandó al mensajero hace dos inviernos porque Dûrin tardaba demasiado en decidirse.","'El honor está bien. Pero el honor no saca los muertos de los túneles.'"],
      ["Torrek Cenicilla (~25 años, el escéptico)","Escéptico del pacto y de que alguien externo pueda resolver algo que ellos no pudieron. No es hostil — es amargo. Empieza siendo el obstáculo de roleplay y puede convertirse en aliado genuino si el grupo demuestra algo concreto en la mina. Candidato a NPC llevable (ver Cap. 13) si la mesa lo quiere.","'¿Un pacto de hace cuatro generaciones? ¿Y eso se supone que nos salva ahora?'"],
    ], 2400, 4200, 3760),
    pEmpty(80),
    secretBox("CÓMO JUGAR EL PRIMER ENCUENTRO CON LOS CENICILLA: Dûrin ve el arma antes de decir nada más. Se detiene. Mira a Greyskull. Después mira el martillo. Después a Greyskull de nuevo. 'El clanado respondió.' No es una pregunta. Es el reconocimiento de algo que esperaba sin creer que llegaría. Torrek, desde un rincón: '¿Ahora? ¿Ahora llegan?' — la amargura de cuatro generaciones de espera, sin ser injustificada. Mira ya está pensando en qué pasará después."),
    pEmpty(140),

    h3("El Problema — Sombras Ancladas en Karak Dûm"),
    p("Hace tres meses, los mineros de Karak Dûm abrieron un pasaje viejo sellado. Lo que salió no fue gas ni derrumbe: fueron las sombras de los mineros que murieron ahí durante el Gran Derrumbe del 1347, atrapadas en el lugar de su muerte por una magia que nadie pidió y nadie entiende. Los vivos no pueden trabajar en las galerías profundas. Los Cenicilla llevan semanas intentando limpiar la mina solos y no pueden — los no-muertos son demasiado resistentes para las herramientas de minero y demasiado extraños para las oraciones de un clan que nunca fue especialmente devoto."),
    pEmpty(80),
    noteBox("POR QUÉ AHORA Y NO ANTES","El Gran Derrumbe del 1347 mató a 11 mineros. Sus sombras quedaron ancladas al pasaje sellado como 'testigos involuntarios' de algo que pasó ahí — posiblemente magia de duelo descontrolado, posiblemente el resultado de que murieran sin ser honrados con el rito de enterramiento correcto (el derrumbe dejó los cuerpos inaccesibles). Cuando Mira mandó a romper el sello para expandir la mina, liberó lo que llevaba setenta y nueve años acumulándose. Los Cenicilla no tienen un Clérigo de la Muerte. Angelus sí.","FFF8E7",C.goldDeep),
    pEmpty(80),

    h3("Dungeon — Las Cuatro Áreas de Karak Dûm"),
    infoTable([
      ["Área","Qué hay","Enemigos","Detalle clave"],
      ["1 — La Galería de Entrada","El primer nivel de la mina, al que los Cenicilla todavía pueden acceder. Herramientas abandonadas, marcas de trabajo reciente interrumpido abruptamente. Mira puede acompañar al grupo hasta aquí.","4 Zombis de minero (CR 1/4 c/u) — los más recientes, los que murieron intentando limpiar las sombras en los últimos meses. No son del Gran Derrumbe — son víctimas nuevas. Más fáciles de tratar como no-muertos normales.","En una pared, alguien grabó con una clavija de hierro: 'No entren solos al Pasaje Viejo'. Abajo, con otra letra y otra mano: 'Ya es tarde para ese consejo'."],
      ["2 — El Pasaje Viejo","El pasaje que Mira mandó abrir. Paredes con marcas de herramienta antiguas, distintas de las modernas — estas son del 1347. Aquí el aire se siente diferente: más frío, más quieto, como si el sonido viajara mal.","2 Umber Hulks (CR 5 c/u) — no son no-muertos, son criaturas que entraron por los túneles superiores atraídas por la energía de las sombras. El problema práctico inmediato que impide avanzar. Las notas de Mira describen exactamente dónde están (si el grupo las consiguió).","La pared del fondo del Pasaje tiene once marcas de mano grabadas en la piedra — once mineros que supieron que iban a morir y dejaron su huella. Angelus reconoce el patrón: es instintivo en alguien que pasó tiempo con los muertos."],
      ["3 — La Sala del Derrumbe","La cámara donde ocurrió el Gran Derrumbe del 1347. Todavía hay restos bajo las rocas — los Cenicilla nunca pudieron recuperarlos. Las paredes tienen sombras que se mueven aunque no haya luz que las cause.","3 Specters (CR 1 c/u) — los mineros del Gran Derrumbe que no llegaron a irse del todo. Son frágiles pero corrosivos: su toque drena la fuerza vital. Angelus puede intentar hablarles antes de combatir (Persuasión CD 14, con su símbolo de la Raven Queen como foco).","Cada uno tiene nombre y una frase final (ver tabla más abajo, 'Los Tres Specters'). La dicen en ambos caminos: si Angelus los convence y se disuelven en paz, la dicen como despedida; si combaten, la dicen al caer. Guardá esas tres frases para el momento de la Sombra Anclada."],
      ["4 — La Cámara del Ancla","El punto más profundo, donde el derrumbe fue peor y donde la energía de los once muertos se concentró. Ahí, una Sombra de Duda (la misma especie del enemigo de viaje, sección 3.4) se quedó — y con generaciones de dolor sin resolver, echó raíces en la piedra misma.","LA SOMBRA ANCLADA (CR 5, 78 PG) — Sombra de Duda Anclada. Ver ficha abajo.","El 'ancla' física es doble: una viga de madera carbonizada del 1347, todavía en pie de milagro, y las vetas minerales oscurecidas que la rodean, donde la Sombra se filtró con los años. Destruir la viga Y purificar las vetas (ver ficha) o nombrar en voz alta la 'certeza' de los once muertos (ver mecánica) libera a la Sombra Anclada y cierra el círculo."],
    ], 1800, 2400, 2600, 2560),
    pEmpty(80),

    h3("Los Tres Specters de la Sala del Derrumbe — Sus Frases Finales"),
    p("Cada uno de los tres es un minero real del Gran Derrumbe del 1347, con nombre propio y un pensamiento final que —a propósito— no es de miedo, sino de certeza. En el último instante, la mente no se aferra a lo que se pierde sino a lo que fue genuinamente real. Es, sin que el grupo lo sepa todavía, el mismo tipo de frase que hace falta para 'Nombrar la Certeza' contra la Sombra Anclada (ver más abajo)."),
    pEmpty(80),
    infoTable([
      ["Specter","Frase final (leer en voz alta)","Nota"],
      ["Grynna Cenicilla, herrera de túnel (la más veterana)","\"Mis manos todavía saben dónde está cada veta de este lugar. Eso no me lo quita ningún derrumbe.\"","Enseñó a media mina a leer la piedra. Su marca es una de las once del Área 2"],
      ["Borin, aprendiz de picador (el más joven)","\"Le prometí a mi hermana que volvía para la fiesta de la cosecha. No llegué. Pero la promesa la hice de verdad, y eso fue real mientras duró.\"","Su hermana sigue viva en Hotenow — gancho opcional para otra sesión si el grupo quiere seguirlo"],
      ["Thodrek 'Dos Manos', capataz del turno","\"Trabajé cuarenta años codo a codo con gente que confiaba en mí para no morir. La mayoría no murió. Eso cuenta.\"","El capataz. Su nombre también está entre las marcas de mano del Área 2"],
    ], 3000, 4200, 2560),
    pEmpty(80),
    secretBox("POR QUÉ ESTAS FRASES Y NO GRITOS DE MIEDO — RESOLVIENDO LA CONTRADICCIÓN APARENTE: un derrumbe es traumático, y sería lógico esperar que el 'último pensamiento congelado' de cada minero fuera puro terror. A propósito, no lo es — es la elección de diseño que hace que 'Nombrar la Certeza' funcione en absoluto. Los Specters no repiten su muerte: repiten lo único a lo que se aferraron mientras morían, que no fue el derrumbe sino la certeza de que algo en su vida fue real. Si tu mesa espera un grito de terror y en cambio escucha esto, dejá que esa diferencia se sienta — es información, no un error de tono. Si el grupo los mata sin darles el momento de hablar (por ejemplo con daño a distancia), leé igual la frase en el instante exacto en que caen: el efecto está diseñado para llegar con o sin diálogo previo."),
    pEmpty(140),

    h3("La Sombra Anclada — Ficha"),
    p("Es una Sombra de Duda (misma especie que el enemigo de viaje de la sección 3.4) — pero esta nunca se fue. Se quedó, y con los años, echó raíces."),
    pEmpty(80),
    voiceBox("\"No tiene la silueta borrosa y errante de sus hermanas del camino. Esta está fija: un núcleo de niebla gris oscura que se filtra entre las vetas minerales de la pared, como si la roca misma sudara sombra. Donde toca la piedra, el mineral se oscurece — no se rompe, se apaga, como una brasa que perdió el color. Cuando se mueve, no camina: la niebla avanza por las vetas ya oscurecidas, salta de una a otra, y solo al final se condensa frente a quien la mira en algo casi humanoide, casi reconocible — cada quien ve una cara distinta en ella, igual que con las Sombras del camino. Pero esta no pregunta. Esta espera.\""),
    pEmpty(80),
    secretBox("CONTINUIDAD CON LA SECCIÓN 3.4 — POR QUÉ ESTO IMPORTA: las Sombras de Duda del camino son el argumento de Mnemós hecho criatura — ideas que aprendieron a moverse (ver el secretBox de 'La Sombra que Pregunta', sección 3.4). Esta es la prueba de que también pueden aprender a quedarse: cuando una duda encuentra suficiente dolor acumulado en un mismo lugar —once mineros, sin nombre, sin cierre, durante generaciones— deja de necesitar buscar víctimas nuevas. Se ancla. Las vetas minerales de Karak Dûm no crearon a la Sombra Anclada: la alimentaron, con el mismo yacimiento donde ocurrió el Gran Derrumbe. Si tu mesa ya conoció a La Sombra que Pregunta, podés hacer el callback explícito acá: misma voz, mismo tipo de pregunta sin responder — solo que esta vez la pregunta se quedó tanto tiempo que dejó de ser pregunta y se volvió ancla."),
    pEmpty(140),
    infoTable([
      ["Estadística","Valor"],
      ["CR / PG","CR 5 / 78 PG"],
      ["CA","13"],
      ["Velocidad","0 ft; vuela 40 ft (no puede salir de Karak Dûm — está anclada)"],
      ["Atributos","FUE 6 (-2), DES 14 (+2), CON 13 (+1), INT 6 (-2), SAB 10 (+0), CAR 14 (+2)"],
      ["Resistencias / Inmunidades","Resistente a daño no mágico, necrótico; Inmune a veneno, encantado, asustado, agotamiento"],
      ["Vulnerabilidad","Radiante (doble daño)"],
    ]),
    pEmpty(60),
    infoTable([
      ["Acción / Rasgo","Efecto"],
      ["Multiataque","2 Toques de Duda Concentrados (misma herencia que las Sombras del camino, sección 3.4): +5 al impacto, 2d6+2 psíquico cada uno. Si impacta, el objetivo tiene Desventaja en su próxima tirada de salvación de Sabiduría"],
      ["Anclada al Dolor (rasgo)","Al inicio de cada turno de la Sombra Anclada, si la viga de madera del 1347 y las vetas minerales oscurecidas que la rodean siguen intactas, recupera 5 PG. Destruir la viga (CA 15, 20 PG) O purificar las vetas (Herramientas de Minero, acción, CD 15) cancela este rasgo permanentemente"],
      ["Ecos del 1347 (acción, recarga 5-6)","La Sombra elige un personaje y le empuja a la mente el último pensamiento de uno de los mineros. Salvación de Sabiduría CD 14: con fallo, 2d8 psíquico (con éxito, mitad). Además, ese personaje hace una tirada de Percepción CD 13 (independiente del resultado anterior) para distinguir el mensaje con claridad: con éxito, lo recibe completo — una de las frases guardadas de los Specters del Área 3 si el grupo las tiene, o una equivalente genérica si no las tiene — información válida para 'Nombrar la Certeza'. Con fallo en la Percepción, el mensaje llega fragmentado y ruidoso: no alcanza por sí solo, aunque puede combinarse con otras pistas ya reunidas"],
      ["Nombrar la Certeza (mecánica especial)","Si alguien nombra en voz alta, con convicción genuina, lo que los once mineros SÍ tuvieron — no lo que perdieron, sino lo que fue real: su trabajo, sus manos, el tiempo que vivieron — la Sombra pierde su Resistencia a daño no mágico por 3 rondas. Si se hace dos veces en el mismo combate, la Sombra se disuelve sin llegar a 0 PG (la ancla se rompe narrativamente). No hay tirada — solo decisión del jugador de decirlo en voz alta."],
    ], 2800, 6560),
    pEmpty(80),
    secretBox("LA CONEXIÓN CON ANGELUS: la mecánica de 'Nombrar la Certeza' es el espejo exacto del desafío de los Miedos en el Archivo (sección 8.7) — ahí nombraban lo que MÁS TEMEN, acá nombran lo que fue GENUINAMENTE REAL. Son la misma habilidad vista desde el otro lado. Si Angelus es quien lo hace, Logos registra esto en silencio y en la siguiente sesión dice, sin anuncio: 'Reclasificando el evento de Karak Dûm. La mecánica de nombrar verdades absolutas parece tener efectos consistentes sobre entidades de origen emocional. Nota: esto coincide con lo que ocurrirá en el Plano del Archivo. Sugiero que lo recuerden.' Primera vez que Logos hace una conexión táctica entre dos eventos separados de la campaña — señal de que su aprendizaje emocional empieza a traducirse en predicciones."),
    pEmpty(140),

    secretBox("SOLO CONOCEN A 3 DE LOS 11 — Y ESTÁ BIEN ASÍ: 'Nombrar la Certeza' habla de los ONCE mineros, pero el grupo solo llegó a conocer a tres (los Specters del Área 3: Grynna, Borin, Thodrek). Esto NO es un hueco que haga falta tapar con más lore — es el punto. El desafío no pide un inventario de las once vidas, palabra por palabra: pide que alguien hable con convicción genuina extendiendo de buena fe lo que sí sabe ('si Grynna tenía sus manos y su oficio, si Borin tenía su promesa, si Thodrek tenía la confianza de los suyos — entonces los otros ocho, que nunca conocimos, también tuvieron algo así, aunque no sepamos qué'). Es honrar lo desconocido a través de lo conocido — el mismo gesto que ya aparece con El Guardián sin nombre (sección 2.6) y con el brazalete sin reclamar de Dax (sección 9.1): la campaña vuelve varias veces a la idea de que no hace falta un nombre completo para que un dolor merezca ser nombrado. Si un jugador se traba pensando que necesita 'saber más' de los ocho restantes, esa es la señal de que está listo para decirlo igual, sin saber — que es, literalmente, la certeza que hace falta nombrar."),
    pEmpty(140),

    noteBox("VÍA OPCIONAL — EL MARTILLO DE LA DEUDA COMO ATAJO A LA PISTA","Si Greyskull ya tiene el Martillo de la Deuda (Etapa 1 activa, sección 14.3.6 — a esta altura ya debería tenerlo, dado que Karak Dûm se visita después de encontrarlo), puede usar Memoria de la Roca apoyando el martillo contra la viga carbonizada o las vetas oscurecidas. Con éxito en Historia CD 18 ('décadas o generaciones'), revive como imagen sensorial una de las últimas frases de los mineros del 1347 — la misma clase de fragmento que dejan los Specters del Área 3 al caer. Esto NO reemplaza la mecánica de Nombrar la Certeza ni la vuelve automática: sigue haciendo falta que alguien la diga en voz alta con convicción, dos veces, para disolver a la Sombra. Es simplemente una segunda vía para conseguir el insumo emocional, útil si el grupo mató a los Specters sin roleplay o nunca guardó sus frases.","FFF8E7",C.goldDeep),
    pEmpty(140),

    h3("Cómo Cierra el Arco"),
    p("Con la Sombra Anclada vencida (de cualquier forma), los Cenicilla pueden volver a trabajar en profundidad. Dûrin convoca a los tres en la entrada de la mina y dice algo que no dice a menudo:"),
    pEmpty(60),
    voiceBox("\"'El pacto se cumplió. Greyskall respondió. Tardó cuatro generaciones, pero el clanado no falla.' Se queda un momento mirando el martillo. 'Tu ancestral hizo algo que ningún gigante hacía: confió en un enano. No porque tuviera que hacerlo. Porque entendió que algunas cosas se hacen mejor con dos manos distintas.' Pausa. 'Ese entendimiento vive en el arma. Ahora vive en vos.' Torrek, desde atrás, en voz baja, como si no quisiera que nadie lo oyera decir esto: 'No estuvo mal.'\""),
    pEmpty(80),
    p("En este momento se activan simultáneamente la Etapa 3 del rasgo de Sangre Ancestral y la Etapa 3 del Martillo de la Deuda. El símbolo de los Cenicilla en el arma desarrolla su brillo dorado-rojizo permanente. Si Torrek lo permitió, puede unirse al grupo como NPC llevable opcional (ver Cap. 13 para el formato)."),
    pEmpty(80),
    noteBox("LOOT ADICIONAL DE KARAK DÛM","Además del cierre narrativo: 400 po en monedas antiguas enanas (de los bolsillos de los Zombis del Área 1 y del cofre sellado que los Cenicilla guardaban para 'cuando se resolviera todo'), más las herramientas de minero de calidad enana que Mira ofrece voluntariamente — misma calidad que las del Área 3 de las Galerías Profundas.","FFF8E7",C.goldDeep),
    pageBreak(),
    p("Inspirado en el dilema de Vax/Vex con la Nightsong Stone (Critical Role, Campaña 4, episodio 30): un momento donde el poder acumulado del grupo es suficiente para resolver un dolor personal y profundo de UN solo personaje — pero usarlo tiene un costo real sobre Chromatus y sobre la historia, y solo uno de los tres puede intentarlo."),
    pEmpty(80),
    warningBox("CUÁNDO OCURRE: justo al reunir la 3ª escama (sin importar el orden). Nivel del grupo: aproximadamente 9, en la transición de Hotenow al Bosque."),
    pEmpty(140),

    h2("14.4 El Momento de las Tres Tentaciones (al reunir la 3ª Escama)"),
    pEmpty(80),

    h3("14.4.1 — Por Qué Solo Uno Puede Actuar, y Qué le Pasa a las Escamas"),
    p("La energía resonante de tres Sentires reunidos genera una sola ventana de uso — no es un objeto aparte que se gasta, es el poder de las TRES ESCAMAS YA CONSEGUIDAS, prestado por un instante para algo distinto de su propósito."),
    pEmpty(80),
    warningBox("DEJÁ ESTO EXPLÍCITO EN MESA: antes de que cualquiera actúe, decile a los jugadores con claridad que usar este poder significa tomarlo PRESTADO de las tres escamas que ya tienen. Las escamas van a sentir ese préstamo (sección 14.4.4). No es un costo oculto que revelás después — es una decisión informada que la mesa toma sabiendo de antemano que hay un precio real sobre algo que ya es suyo."),
    pEmpty(80),
    secretBox("ESTO ES UNA DECISIÓN DE MESA: dale un momento real y explícito para que los cuatro jugadores discutan qué hacer entre ellos. Decí en voz alta, fuera de personaje si hace falta, que la decisión de usar el poder de las escamas y a quién apoyar es una decisión que los JUGADORES toman juntos. La fuerza de esta escena viene de que tienen que decidir juntos a cuál apoyar, sabiendo que los otros dos se quedan sin la suya."),
    pEmpty(140),

    h3("14.4.2 — Las Tres Visiones (Simultáneas)"),

    h3("Visión de Angelus — La Raven Queen"),
    voiceBox("\"El mundo se vuelve gris por un instante — no la Niebla, algo distinto, más antiguo — y Angelus se encuentra de pie frente a una balanza enorme. Un plato sube y baja con normalidad. El otro sigue quieto, oxidado. Pero esta vez, la Raven Queen está ahí, como presencia real, alada. 'El poder que cargan ahora es suficiente,' dice. 'Suficiente para tocar ese plato oxidado y hacerlo moverse de nuevo. Suficiente para sacar a tu familia de donde quedaron atrapados y darles, por fin, el final que nunca tuvieron.' Pausa larga. 'Este poder no fue hecho para esto. Pero el final de tu familia nunca se completó del todo — quizás por eso responde. No te diré que no lo hagas. Te diré que el Destino tiene una forma de cobrarse lo que se le quita, incluso cuando tiene razones para entender por qué se lo hiciste.'\""),
    pEmpty(140),

    h3("Visión de Hola — El Documento que Casi Habla"),
    voiceBox("\"Hola siente el peso de las tres escamas como un calor en el pecho, y por un instante el documento incompleto del estudio de su padre parece vibrar, como si las palabras que faltan estuvieran ahí, a punto de completarse. Pero no es información lo que llega: es una sensación clara y pesada de que ese mismo calor podría usarse para algo más grande que leer el resto de la página. Podría usarse para deshacer el día de la plaza. Para traer a su padre de vuelta. La sensación no tiene voz que la explique — pero es igual de clara: este poder no se siente hecho para esto. Y aun así, ahí está, disponible, esperando una decisión.\""),
    pEmpty(140),

    h3("Visión de Greyskull — La Sangre que Empuja"),
    voiceBox("\"Un vértigo le sube por la columna a Greyskull, como si su propia sangre, despierta desde Hotenow, reconociera el poder de las tres escamas como algo que PUEDE usar para sí misma. Por un instante, siente lo que sería completar la transformación entera, ahora, de golpe — no esperar a la Etapa 3, simplemente crecer hasta ser, por fin, lo que su sangre antigua quiere ser. Si Korrund está presente o si lo recuerda con claridad, una frase suya puede resonar en este momento sin que el gigante sepa nada de la visión: 'La montaña que crece de golpe, se derrumba antes de tiempo.'\""),
    pEmpty(140),

    h3("14.4.3 — Las Tres Tiradas (con Fallo Real)"),
    p("Una vez que la MESA decidió, con la información completa de qué cuesta y a costa de qué escama (sección 14.4.4), a cuál de los tres apoyar, ese personaje hace UNA tirada. El éxito da el resultado deseado, y el costo en la escama se paga igual. El fallo NO cancela ese costo — el préstamo ya se hizo, la escama ya lo sintió — pero el resultado deseado no se logra del todo, o llega torcido."),
    pEmpty(80),
    infoTable([
      ["Personaje","Tirada","CD","Qué representa la dificultad"],
      ["Greyskull","Salvación de Constitución","15","Forzar el propio cuerpo a transformarse de golpe es un trauma físico real — la dificultad más baja, porque solo se afecta a sí misma"],
      ["Hola","Tirada de Sabiduría","17","La PRECISIÓN de manejar un poder de resurrección tan delicado sin entrenamiento real en nigromancia de ese calibre"],
      ["Angelus","Sabiduría o Carisma (a elección)","19","La dificultad más alta — manipular un loop de no-muerte completo, con varias personas atrapadas a la vez, sin entrenamiento en ese tipo de magia"],
    ], 1600, 2400, 1200, 4760),
    pEmpty(80),
    infoTable([
      ["Personaje","Si tiene ÉXITO","Si FALLA (el poder se gasta igual)"],
      ["Greyskull","Completa la Etapa 3 de su rasgo de Sangre Ancestral (sección 14.3.5) de golpe","Completa la Etapa 3 IGUAL pero queda con 1 Nivel de Agotamiento que NO se cura con descanso normal — solo con ayuda de un sanador gigante (Korrund)"],
      ["Hola","Su padre revive — vivo, sano — pero sin memoria de lo que sabía sobre la red de Ozyr. El documento del estudio se desvanece o queda ilegible","El padre revive, pero incompleto: vuelve sin poder hablar, o revive su propia ejecución mentalmente una y otra vez, o vuelve sabiendo que sabía algo peligroso pero sin recordar qué"],
      ["Angelus","Su familia sale del loop del Plano Gris, libre, con un final correcto y completo — el costo recae enteramente sobre Chromatus (ver 14.4.4)","La familia NO sale del loop. El poder se gasta de todas formas Y un residuo del Plano Gris se filtra brevemente hacia este lado: una Sombra de Duda especialmente fuerte aparece donde estén parados"],
    ], 1600, 4200, 4160),
    pEmpty(140),

    h3("14.4.4 — El Efecto en Chromatus (Escala según Magnitud)"),
    infoTable([
      ["Si se usó en...","Efecto en Chromatus","Cuándo se nota"],
      ["Greyskull (solo se afecta a sí misma)","Una fisura menor, casi cosmética: una escama tarda un poco más en asentarse al recuperarla","Solo en el momento de recuperar esa escama — una línea de descripción, nada más"],
      ["Hola (afecta a otra persona además de a sí mismo)","Una de las escamas ya reunidas pierde brillo para siempre — una grieta visible que nunca vuelve a sanar del todo","Visible cada vez que el grupo mire a Chromatus de cerca desde ese momento"],
      ["Angelus (manipula un loop de no-muerte con varias personas)","Chromatus pierde las alas y se vuelve agresivo o retraído — genuinamente herido por la libertad tomada con un poder que no fue diseñado para esto. Ver 14.4.5","Inmediato y permanente desde el momento en que se usa"],
    ], 2200, 5560, 2000),
    pEmpty(140),

    h3("14.4.5 — Si Eligen la Opción de Angelus: Chromatus Herido"),
    voiceBox("\"La próxima vez que el grupo vea a Chromatus, algo cambió: donde antes había alas translúcidas que reflejaban cada color de los Sentires, ahora hay cicatrices vacías. Chromatus no ataca al grupo — todavía los reconoce — pero se retrae cuando se acercan, o responde con una frialdad que nunca tuvo antes. 'Tomaron algo que no era para tomar,' dice, sin gritar, lo cual de alguna forma es peor que si gritara. 'Entiendo por qué. No significa que no doliera.'\""),
    pEmpty(80),
    infoTable([
      ["Aspecto","Cómo se manifiesta el resto de la campaña"],
      ["Comportamiento de Chromatus","Más distante en cualquier escena futura donde aparezca — todavía es un aliado, pero ya no es el aliado cálido que pudo haber sido. Las conversaciones con él tienen un trasfondo de tensión no resuelta"],
      ["Vuelo","No puede volar hasta que las cinco escamas estén completas y restauradas del todo en el clímax — esto puede tener implicaciones narrativas menores si alguna escena futura asumía que él podía trasladarse por aire"],
      ["Reconciliación posible (no obligatoria)","Si el grupo —especialmente Angelus— busca activamente reparar esto a lo largo de las zonas siguientes (un gesto genuino, una disculpa que no sea solo palabras, ayudar a Chromatus de alguna forma concreta), Chromatus puede recuperar parte de su calidez antes del clímax. No es automático ni gratuito — requiere esfuerzo real de roleplay, coherente con el tema de la campaña sobre comunicar lo que se siente en vez de dejarlo sin decir"],
      ["En el clímax final","Si nunca se reparó la relación, Chromatus restaurado al final recupera sus alas físicamente (la magia de las 5 escamas lo arregla), pero el MOMENTO de la restauración puede tener una línea de diálogo distinta — algo más parecido a un alivio cauteloso que a una alegría total, dependiendo de cómo se haya manejado el resto de la campaña"],
    ], 2400, 7160),
    pEmpty(80),
    secretBox("Esta es, de las tres, la consecuencia que más vale la pena dejar que pese durante varias sesiones — no la resuelvas rápido ni la dejes pasar sin comentario. Es el tipo de costo a largo plazo que hace que la decisión en el momento de las tres escamas se sienta real y no solo como un evento aislado que la campaña olvida después."),
    pEmpty(140),

    h3("14.4.6 — Si Nadie Decide Usarlo"),
    p("Resultado perfectamente válido. Si la mesa decide que ninguna tentación vale el costo, las tres visiones se disipan junto con la ventana de poder. Un breve momento de silencio entre los tres personajes después — sabiendo lo que cada uno pudo haber pedido, y eligiendo, juntos, no hacerlo. Eso también dice algo importante sobre quiénes son como grupo."),
  ];
}
module.exports = { cap14 };
