const { p, pEmpty, h1, h2, h3, bullet, numBullet, infoTable, noteBox, secretBox, loreBox, voiceBox, warningBox, cdBox, xpBox, pageBreak, C } = require('./helpers');

// Helper local: bloque de estad\u00edsticas compacto
function stat(nombre, cr, flavor, filas, acciones) {
  const out = [ h3(nombre + "  (" + cr + ")"), p(flavor), infoTable([["Atributo","Valor"], ...filas]) ];
  if (acciones && acciones.length) { out.push(pEmpty(40)); out.push(infoTable([["Acci\u00f3n / Rasgo","Efecto"], ...acciones], 3200, 6160)); }
  out.push(pEmpty(80));
  return out;
}

function cap11() {
  return [
    h1("11. Encuentros, Dungeons y Bestiario"),
    p("Este cap\u00edtulo agrupa todo el contenido de combate y exploraci\u00f3n de la campa\u00f1a, para que lo tengas en un solo lugar. Todo es modular: cada encuentro y cada dungeon puede usarse, recortarse o saltarse sin romper la trama principal. Los dungeons de exploraci\u00f3n est\u00e1n pensados para grupos a los que les gusta recorrer habitaciones, evaluar estrategias y buscar tesoro escondido."),
    pEmpty(80),
    warningBox("BALANCE \u2014 Record\u00e1 que la party tiene aliados de alto poder (golem de Hola, quimera de Greyskull). Todos los CR de aqu\u00ed ya asumen esos aliados. Si en una sala estrecha no caben, baja el CR del encuentro en 1-2 o dale a la party una ronda de ventaja. Para los dungeons, dale descansos cortos entre salas para que el desaf\u00edo sea de recursos, no de agotamiento injusto."),
    pEmpty(80),
    noteBox("CÓMO LEER LOS BLOQUES","Los bloques de estadísticas son abreviados (estilo 5e simplificado): CA = Clase de Armadura, PG = Puntos de Golpe, Vel = Velocidad. Tira iniciativa normalmente. Cuando un ataque dice '+X', es el bono al d20; el daño va aparte. Las CDs de salvación están indicadas en cada rasgo.","FAFAFA",C.grayMid),
    pEmpty(140),

    h2("11.0 Calibración — ¿Están bien los CR para el nivel de la party?"),
    p("Respuesta corta: sí, cada encuentro está pensado para el nivel que tendrá la party cuando llegue a él (según la tabla de hitos de la sección 1.6). Pero hay un matiz importante por culpa de tus aliados de alto poder."),
    pEmpty(80),
    infoTable([
      ["Encuentro","Nivel esperado de la party","Evaluación"],
      ["Manada de la Niebla / Bandidos","5","Fácil-medio (encuentros de camino, para calentar)"],
      ["Saqueadores de la Risa","5-6","Medio"],
      ["Anegados (trash de las Criptas)","6-7","Medio (más duro en el agua)"],
      ["Pena Ahogada (mini-jefe)","6-7","Medio-difícil"],
      ["Sepulturero Anegado (jefe Criptas)","7","Jefe — ver ajuste de jefes abajo"],
      ["Brasas Iracundas","8-9","Medio"],
      ["Salamandra del Furor (jefe Galerías, opcional)","8-9","Jefe — ver ajuste de jefes abajo"],
      ["Centinelas Despertados","9-10","Medio cada uno"],
      ["Acechantes de Hojaverde","10-11","Medio-difícil"],
      ["Guardián Dormido (jefe Raíces)","10-11","Jefe — ver ajuste de jefes abajo"],
      ["Custodios del Archivo","12","Fácil-medio cada uno (el riesgo es enfrentar varios)"],
      ["Mnemós (Final A)","13","Jefe final, letal — bien calibrado tal cual"],
    ], 3600, 2400, 3360),
    pEmpty(80),
    warningBox("EL MATIZ DE LA ECONOMÍA DE ACCIONES: tu party efectivamente juega 6 'turnos' por ronda (4 PJs + golem + quimera). Contra enemigos múltiples (trash, Anegados, Custodios) eso está perfectamente equilibrado SI sus PG están bien calibrados — ver la corrección ya aplicada en el bestiario. Pero contra un JEFE SOLITARIO, esa ventaja de acciones hace que el jefe caiga rápido y la pelea se sienta floja incluso con PG estándar. Por eso los tres jefes de dungeon traen abajo un 'Ajuste de Jefe Solitario' que recomiendo aplicar SIEMPRE en tu mesa."),
    pEmpty(80),
    infoTable([
      ["Jefe","Ajuste de Jefe Solitario (recomendado para tu party)"],
      ["Sepulturero Anegado","Ya integrado como base en su bloque de estadísticas (sección 11.3): 184 PG y 3 acciones legendarias por ronda. No hace falta sumar nada aparte — esto YA es el número final."],
      ["Salamandra del Furor","+55 PG (total 175). Gana 3 acciones legendarias: 'Coletazo', 'Aliento de furia' (línea de 6 m, Destreza CD 15, 4d6 fuego, recarga 1/ronda), o 'Calor Abrasador Extra' (1d6 fuego a todos a 3 m)"],
      ["Guardián Dormido","Ya 'despierta' a media vida ganando una acción extra. Súmale +40 PG (total 176) y 2 acciones legendarias por ronda: 'Pisotón' (Fuerza CD 15 en 3 m o derribo) y 'Zarcillos Reactivos' (repite su Zarcillos sin gastar la recarga, 1 vez por combate)"],
      ["Custodio del Archivo (solitario)","Si la party despierta solo UN Custodio, sumale +35 PG (total 150) y 1 acción legendaria: 'Golpe de Porcelana Extra'. Si despiertan varios, NO apliques este ajuste — ya funcionan bien en grupo"],
    ], 2800, 6560),
    pEmpty(80),
    secretBox("Regla práctica: si en las primeras 2 rondas la party le baja más de la mitad de la vida a cualquier jefe, aplicá el ajuste a mitad de pelea (sumá los PG y las acciones legendarias) en lugar de esperar a la próxima vez. Mejor un jefe que dura que uno que cae en una ronda."),
    pageBreak(),

    // ============ BESTIARIO ============
    h2("11.1 Bestiario Temático"),
    p("Enemigos nuevos, todos ligados al tema de la campa\u00f1a: criaturas drenadas de color, vaciadas de emoci\u00f3n, o formadas a partir del duelo. No son monstruos gen\u00e9ricos \u2014 cada uno refleja qu\u00e9 pasa cuando una emoci\u00f3n se rompe o se concentra demasiado."),
    pEmpty(100),

    ...stat("Bestia de la Niebla", "CR 2", "Un animal cualquiera \u2014ciervo, oso, lobo\u2014 al que la Niebla Gris le rob\u00f3 el color y, con \u00e9l, el juicio. Se mueve a tirones, ataca por confusi\u00f3n y miedo, no por hambre. Da pena y peligro a la vez.",
      [["CA / PG / Vel","13 / 68 / 12 m"],
       ["Atributos","FUE +3, DES +2, CON +2, INT -4, SAB +0, CAR -2"],
       ["Sentidos / Idiomas","Percepción pasiva 11 / —"]],
      [["Multiataque","Hace 2 ataques de garra/cornada: +5 al impacto, 1d8+3 contundente cada uno"],
       ["Aura Gris (rasgo)","Una criatura que empieza su turno a 1,5 m de la bestia debe superar Sabidur\u00eda CD 12 o sufre Desventaja en su primer ataque ese turno (la apat\u00eda gris la roza)"],
       ["Fr\u00e1gil de mente (rasgo)","Tiene Desventaja en salvaciones contra ser Asustada o Encantada; un personaje con Trato con Animales CD 14 puede calmarla en vez de matarla (cuenta como derrota)"]]),

    ...stat("Saqueador Oportunista", "CR 1", "Bandidos comunes que aprovechan el caos emocional para robar a pueblos que ni se enteran. No son vac\u00edos ni drenados \u2014son humanos ego\u00edstas\u2014 pero encajan como amenaza 'mundana' entre tanto enemigo extra\u00f1o.",
      [["CA / PG / Vel","13 (cuero) / 42 / 9 m"],
       ["Atributos","FUE +1, DES +2, CON +1, INT +0, SAB +0, CAR +0"],
       ["Sentidos / Idiomas","Percepci\u00f3n pasiva 10 / Com\u00fan"]],
      [["Cimitarra","+4 al impacto, 1d6+2 cortante"],
       ["Ballesta ligera","+4 al impacto, alcance 24/96 m, 1d8+2 perforante"],
       ["T\u00e1cticas de manada (rasgo)","Ventaja al atacar si un aliado est\u00e1 a 1,5 m del objetivo"]]),

    ...stat("Cabecilla Saqueador", "CR 3", "El jefe de la banda. M\u00e1s astuto y mejor armado. Suele tener el bot\u00edn del pueblo escondido cerca.",
      [["CA / PG / Vel","15 (cuero tachonado + escudo) / 88 / 9 m"],
       ["Atributos","FUE +2, DES +3, CON +2, INT +1, SAB +1, CAR +2"],
       ["Sentidos / Idiomas","Percepci\u00f3n pasiva 12 / Com\u00fan"]],
      [["Multiataque","2 ataques de espada corta: +5, 1d6+3 cortante"],
       ["\u00a1A ellos! (acci\u00f3n adicional)","Un aliado a 9 m que pueda o\u00edrlo usa su reacci\u00f3n para hacer un ataque con arma"],
       ["Escurridizo (reacci\u00f3n)","Cuando recibe un ataque, puede imponer Desventaja a ese ataque 1 vez por turno"]]),

    ...stat("Anegado", "CR 2", "El cuerpo de alguien que se ahog\u00f3 y al que el duelo del Pantano no dej\u00f3 descansar. Camina bajo el agua con los pulmones llenos, buscando arrastrar a otros a su mismo silencio. No-muerto.",
      [["CA / PG / Vel","11 / 72 / 6 m, nadar 9 m"],
       ["Atributos","FUE +3, DES +0, CON +3, INT -3, SAB +0, CAR -2"],
       ["Resist. / Vulnerab.","Resistente a necr\u00f3tico; Vulnerable a fuego"],
       ["Sentidos / Idiomas","Visi\u00f3n en la oscuridad 18 m; Percepci\u00f3n pasiva 9 / \u2014"]],
      [["Golpe ahogado","+5 al impacto, 2d6+3 contundente, y el objetivo hace Constituci\u00f3n CD 12 o no puede usar reacciones hasta su pr\u00f3ximo turno (agua en los pulmones)"],
       ["Arrastre (acci\u00f3n, solo en agua)","Agarra a una criatura a 1,5 m (escape CD 13) y la sumerge: mientras est\u00e9 agarrada bajo el agua, debe contener la respiraci\u00f3n o empezar a ahogarse"],
       ["Anfibio (rasgo)","Respira agua y aire por igual; tiene Ventaja para esconderse bajo el agua turbia"]]),

    ...stat("Pena Ahogada", "CR 4", "No es un cuerpo: es el duelo mismo de Grauwater, condensado en una figura de agua oscura con forma vagamente humana. Revive una y otra vez el momento de un ahogamiento. Mini-jefe del Pantano.",
      [["CA / PG / Vel","13 / 98 / 9 m, nadar 12 m"],
       ["Atributos","FUE +1, DES +3, CON +3, INT +0, SAB +2, CAR +3"],
       ["Resist. / Inmun.","Resistente a da\u00f1o no m\u00e1gico; Inmune a veneno, encantado, agotamiento"],
       ["Sentidos / Idiomas","Visi\u00f3n en la oscuridad 18 m; Percepci\u00f3n pasiva 14 / entiende Com\u00fan"]],
      [["Toque del duelo","+6 al impacto, 3d6 ps\u00edquico, y el objetivo no puede recuperar PG hasta el final de su pr\u00f3ximo turno"],
       ["Lamento (recarga 5-6)","Todas las criaturas a 4,5 m hacen Sabidur\u00eda CD 14: con fallo, 3d8 ps\u00edquico y quedan Asustadas 1 round; con \u00e9xito, mitad y sin miedo. La luz fuerte o el fuego le da Desventaja a este rasgo si se us\u00f3 contra ella ese round"],
       ["Atada al dolor (rasgo)","Si alguien le habla con compasi\u00f3n genuina del recuerdo que revive (roleplay, sin tirada o Persuasi\u00f3n CD 15), pierde 15 PG por round \u2014el duelo empieza a soltarse. Es una v\u00eda alternativa a matarla a golpes"]]),

    ...stat("Brasa Iracunda", "CR 3", "Un fragmento de fuego de Hotenow al que la Escama Roja perdida volvi\u00f3 rabioso. No quema por naturaleza: quema porque no encuentra d\u00f3nde descargar la furia. Elemental menor.",
      [["CA / PG / Vel","13 / 78 / 9 m"],
       ["Atributos","FUE +1, DES +3, CON +3, INT -2, SAB +0, CAR +0"],
       ["Resist. / Inmun.","Inmune a fuego, veneno; Vulnerable a fr\u00edo"],
       ["Sentidos / Idiomas","Visi\u00f3n en la oscuridad 18 m; Percepci\u00f3n pasiva 10 / \u00cdgneo"]],
      [["Golpe ardiente","+5 al impacto, 2d6+3 fuego"],
       ["Estallido de furia (al morir)","Cuando llega a 0 PG, explota: todos a 3 m hacen Destreza CD 13 o reciben 2d6 fuego (mitad si tienen \u00e9xito)"],
       ["Acumulaci\u00f3n (rasgo)","Cada vez que recibe da\u00f1o y sobrevive, su pr\u00f3ximo Golpe ardiente hace +1d6 fuego adicional (la furia se carga). Se reinicia al usarlo"]]),

    ...stat("Salamandra del Furor", "CR 5", "Una salamandra mayor que anid\u00f3 en las galer\u00edas profundas del volc\u00e1n, aliment\u00e1ndose de la ira concentrada. Jefe del dungeon opcional de Hotenow.",
      [["CA / PG / Vel","16 (escamas) / 120 / 9 m"],
       ["Atributos","FUE +4, DES +2, CON +4, INT +0, SAB +1, CAR +1"],
       ["Resist. / Inmun.","Inmune a fuego; Vulnerable a fr\u00edo"],
       ["Sentidos / Idiomas","Visi\u00f3n en la oscuridad 18 m; Percepci\u00f3n pasiva 11 / \u00cdgneo"]],
      [["Multiataque","Una Lanza ardiente y un Coletazo"],
       ["Lanza ardiente","+7 al impacto, 2d6+4 perforante + 1d6 fuego"],
       ["Coletazo","+7 al impacto, 2d8+4 contundente, y el objetivo hace Fuerza CD 15 o cae derribado"],
       ["Calor abrasador (rasgo)","Una criatura que termina su turno a 1,5 m sufre 1d6 fuego"]]),

    ...stat("Centinela Despertado", "CR 4", "Uno de los lobos de piedra de la entrada del bosque, animado mal por la Niebla. No es malvado: est\u00e1 confundido y busca 'la amenaza' sin poder reconocer amigo de enemigo. Constructo.",
      [["CA / PG / Vel","16 (piedra) / 100 / 12 m"],
       ["Atributos","FUE +4, DES +0, CON +3, INT -2, SAB +1, CAR -2"],
       ["Resist. / Inmun.","Inmune a veneno, ps\u00edquico, encantado, asustado, agotamiento"],
       ["Sentidos / Idiomas","Visi\u00f3n ciega 9 m, visi\u00f3n en la oscuridad 18 m; Percepci\u00f3n pasiva 11 / \u2014"]],
      [["Multiataque","Un Mordisco y un Embate de piedra"],
       ["Mordisco","+6 al impacto, 2d6+4 perforante"],
       ["Embate de piedra","+6 al impacto, 2d8+4 contundente; si la criatura es Grande o menor, hace Fuerza CD 14 o cae derribada"],
       ["Carga p\u00e9trea (rasgo)","Si se mueve 6 m en l\u00ednea recta hacia un objetivo y lo golpea, +2d8 de da\u00f1o"],
       ["Se lo puede calmar (rasgo)","En vez de combatir: si alguien le repite la 'orden de centinela' correcta (Historia CD 15 para deducirla, o se aprende de Sylveth/la Reina Espina), o lo somete con un reto de habilidad de 3 \u00e9xitos antes de 3 fallos (Trato con Animales, Persuasi\u00f3n, Atletismo), el Centinela se detiene y vuelve a la piedra sin pelear"]]),

    ...stat("Acechante de Hojaverde", "CR 5", "Un fe\u00e9rico veloz que cruz\u00f3 la frontera adelgazada. Se mueve tan r\u00e1pido que parece parpadear de un punto a otro. Cruel y juguet\u00f3n. Depredador del Plano de las Hadas.",
      [["CA / PG / Vel","15 / 98 / 24 m"],
       ["Atributos","FUE +0, DES +5, CON +2, INT +1, SAB +2, CAR +3"],
       ["Resist.","Resistente a da\u00f1o no m\u00e1gico"],
       ["Sentidos / Idiomas","Visi\u00f3n en la oscuridad 18 m; Percepci\u00f3n pasiva 14 / Silvano, Com\u00fan"]],
      [["Multiataque","2 ataques de Daga centelleante"],
       ["Daga centelleante","+8 al impacto, 1d4+5 perforante + 2d6 perforante adicional si el objetivo no actu\u00f3 todav\u00eda este combate"],
       ["Parpadeo (acci\u00f3n adicional)","Se teletransporta hasta 9 m a un punto que pueda ver; no provoca ataques de oportunidad"],
       ["Dif\u00edcil de fijar (rasgo)","Los ataques de oportunidad contra \u00e9l tienen Desventaja"]]),

    ...stat("Custodio del Archivo", "CR 6", "Constructo guardi\u00e1n de Mnem\u00f3s, uno por cada sala emocional del Archivo. Tienen forma de maniqu\u00ed de porcelana sin rostro. Se activan si alguien manipula los frascos. Cada variante tiene un rasgo seg\u00fan su emoci\u00f3n.",
      [["CA / PG / Vel","17 / 115 / 9 m"],
       ["Atributos","FUE +4, DES +2, CON +4, INT +0, SAB +2, CAR +0"],
       ["Resist. / Inmun.","Resistente a da\u00f1o no m\u00e1gico; Inmune a ps\u00edquico, veneno, encantado, asustado"],
       ["Sentidos / Idiomas","Visi\u00f3n en la oscuridad 18 m; Percepci\u00f3n pasiva 12 / entiende Com\u00fan"]],
      [["Multiataque","2 Golpes de porcelana"],
       ["Golpe de porcelana","+7 al impacto, 2d8+4 contundente"],
       ["Variante de Alegr\u00eda (rasgo)","Recarga 5-6: un objetivo a 9 m hace Sabidur\u00eda CD 15 o r\u00ede sin control y pierde su acci\u00f3n el pr\u00f3ximo turno"],
       ["Variante de Tristeza (rasgo)","Aura: las criaturas a 3 m tienen su velocidad reducida a la mitad (peso del duelo)"],
       ["Variante de Ira (rasgo)","Cuando recibe da\u00f1o cuerpo a cuerpo, el atacante sufre 1d8 fuego (represalia)"],
       ["Variante de Calma (rasgo)","Recarga 5-6: un objetivo a 9 m hace Sabidur\u00eda CD 15 o queda Aturdido 1 round (calma forzada)"]]),
    pageBreak(),

    h2("11.1bis La Guardia de \u00c1mbar \u2014 Bestiario"),
    p("Facci\u00f3n al servicio de Ozyr (ver Cap. 12 secreto, secci\u00f3n 12.12, para lore completo y motivaci\u00f3n). Estos son enemigos recurrentes, no de una sola zona \u2014 usalos en Neverwinter y en el camino, seg\u00fan el plan de encuentros."),
    pEmpty(80),
    ...stat("Ilvara Thorne, \"La Curadora\"", "CR 9", "L\u00edder de la Guardia de \u00c1mbar. Erudita-coleccionista fr\u00eda y meticulosa, reclutada por Ozyr tras estudiar estos objetos por curiosidad genuina. Trata a sus tenientes como colegas, no subordinados.",
      [["CA / PG / Vel","16 / 175 / 9 m"],
       ["Atributos","FUE +1, DES +3, CON +3, INT +4, SAB +3, CAR +2"],
       ["Resist. / Inmun.","Resistente a da\u00f1o ps\u00edquico; Inmune a ser Encantada o Asustada"],
       ["Sentidos / Idiomas","Percepci\u00f3n pasiva 16 / Com\u00fan, \u00c9lfico, Infernal"]],
      [["Multiataque","2 golpes con su bast\u00f3n-daga, +7 al impacto, 1d8+3 cada uno"],
       ["Leer el Eco (acci\u00f3n, 1/d\u00eda)","Usa El Ojo sin P\u00e1rpado para ubicar aproximadamente cualquier \u00edtem de Guardi\u00e1n antiguo en la regi\u00f3n"],
       ["Golpe de Certeza (recarga 5-6)","Un ataque que ignora resistencias, +9 al impacto, 3d8 de da\u00f1o ps\u00edquico"],
       ["Coleccionista Fr\u00eda (rasgo)","Inmune a efectos que dependan de miedo o desesperaci\u00f3n \u2014 no le teme a nada de esto"],
       ["Acciones legendarias (2 por ronda, si pelea sola)","Reposicionar (se mueve sin provocar ataque de oportunidad) \u2014 Orden Fr\u00eda (un mercenario aliado cercano gana un ataque extra)"]]),
    secretBox("Si la matan, El Ojo sin P\u00e1rpado (ver Cap. 12, secci\u00f3n 12.11) queda como loot: quien se lo quede hereda la habilidad de rastreo, y tambi\u00e9n el costo de memoria que implica usarla."),
    pEmpty(80),
    ...stat("Sable Wren, \"El Rastro\"", "CR 5", "Explorador/p\u00edcaro, experto en disfraces. Evita el combate directo \u2014 prioriza seguir al grupo sin ser visto y reportar. Si lo acorralan, pelea sucio: trampas, humo, distancia.",
      [["CA / PG / Vel","15 / 110 / 12 m"],
       ["Atributos","FUE +0, DES +4, CON +2, INT +2, SAB +2, CAR +1"],
       ["Resist. / Inmun.","Ninguna"],
       ["Sentidos / Idiomas","Percepci\u00f3n pasiva 15 / Com\u00fan"]],
      [["Multiataque","2 dagas arrojadizas, +6 al impacto, 1d4+3 cada una"],
       ["Bomba de Humo (acci\u00f3n, 1/combate)","Oscuridad en 3 m de radio"],
       ["Ventaja por Sigilo (rasgo)","Si ataca desde ocultamiento, 2d6 de da\u00f1o extra"]]),
    pEmpty(80),
    ...stat("Grendal Ashwood, \"El Cincel\"", "CR 7", "El que de verdad intenta arrancar los \u00edtems a la fuerza. Grandote, directo, casi sin di\u00e1logo. Ejecuta la Extracci\u00f3n Forzada si el grupo se lo permite.",
      [["CA / PG / Vel","16 / 140 / 9 m"],
       ["Atributos","FUE +5, DES +1, CON +4, INT +0, SAB +1, CAR +0"],
       ["Resist. / Inmun.","Ninguna"],
       ["Sentidos / Idiomas","Percepci\u00f3n pasiva 11 / Com\u00fan"]],
      [["Multiataque","2 golpes de maza pesada, +8 al impacto, 2d6+4 cada uno"],
       ["Presa de Extracci\u00f3n (acci\u00f3n)","Si ya tiene agarrado al objetivo, intenta arrancarle un \u00edtem simbi\u00f3tico directamente (usa las reglas de Extracci\u00f3n Forzada del objeto, Cap. 12 secci\u00f3n 12.11)"],
       ["Aguante Bruto (rasgo)","Ventaja en salvaciones de Constituci\u00f3n"]]),
    pEmpty(80),
    ...stat("Perpetua Voss, \"La Devota\"", "CR 6", "Infiltrada dentro de Los Sin-Color hace tiempo, pasando por una verdadera creyente. Reporta cualquier actividad ritual que huela a estos \u00edtems. Prefiere manipular antes que pelear.",
      [["CA / PG / Vel","14 / 120 / 9 m"],
       ["Atributos","FUE +0, DES +1, CON +2, INT +2, SAB +3, CAR +3"],
       ["Resist. / Inmun.","Ninguna"],
       ["Sentidos / Idiomas","Percepci\u00f3n pasiva 13 / Com\u00fan, Infernal"]],
      [["Conjuros","Sugesti\u00f3n, Silencio, Infligir Heridas (+6, 2d10+3 necr\u00f3tico)"],
       ["M\u00e1scara de Devoci\u00f3n (rasgo)","Ventaja en Enga\u00f1o mientras finge ser una Sin-Color genuina"],
       ["Palabra en la Sombra (reacci\u00f3n, 1/d\u00eda)","Impone Desventaja en el pr\u00f3ximo ataque contra ella o un aliado cercano"]]),
    pEmpty(80),
    ...stat("Buscador de \u00c1mbar", "CR 2", "Mercenario de a pie de la Guardia de \u00c1mbar. Van en grupos de 3-4.",
      [["CA / PG / Vel","13 / 65 / 9 m"],
       ["Atributos","FUE +2, DES +1, CON +1, INT +0, SAB +0, CAR +0"],
       ["Resist. / Inmun.","Ninguna"],
       ["Sentidos / Idiomas","Percepci\u00f3n pasiva 10 / Com\u00fan"]],
      [["Multiataque","Espada corta, +4 al impacto, 1d6+2 cortante"],
       ["Marca de \u00c1mbar (rasgo)","Al morir o retirarse, deja la marca de cera caracter\u00edstica de la facci\u00f3n \u2014 una pista reconocible para el grupo"]]),
    pageBreak(),

    h3("Emboscada de la Guardia de \u00c1mbar (camino a o desde Zona 4 \u2014 Bosque)"),
    p("Esta es la revancha de Grendal Ashwood despu\u00e9s de fallar el intento nocturno en Neverwinter (ver cap. 9). La v\u00eda sutil ya se gast\u00f3, as\u00ed que ahora viene con refuerzos: Grendal Ashwood + 3 Buscadores de \u00c1mbar emboscan al grupo en un tramo aislado del camino, en terreno boscoso. El objetivo declarado es Hola \u2014 Grendal va directo a intentar la Presa de Extracci\u00f3n sobre ella apenas la tenga agarrada. Perpetua Voss no participa del combate (opera desde las sombras de Los Sin-Color), pero puede aparecer despu\u00e9s, en el pueblo m\u00e1s cercano, preguntando con preocupaci\u00f3n fingida por 'el incidente en el camino' para sondear cu\u00e1nto sabe el grupo."),
    pageBreak(),

    // ============ ACTO I ENCUENTROS DE CAMINO ============
    h2("11.2 Encuentros de Camino (Acto I y entre zonas)"),
    p("Encuentros cortos para los viajes entre zonas. \u00datiles para subir la tensi\u00f3n o premiar la exploraci\u00f3n sin desviarse de la trama."),
    pEmpty(100),

    h3("La Manada de la Niebla"),
    p("En cualquier camino entre zonas, el grupo se cruza con 2-4 Bestias de la Niebla (CR 2 c/u) merodeando alrededor de los restos de una caravana. Las bestias no son el verdadero peligro emocional \u2014son v\u00edctimas\u2014 y un grupo compasivo puede intentar calmarlas (Trato con Animales CD 14 por bestia) en vez de matarlas."),
    pEmpty(60),
    infoTable([
      ["Elemento","Detalle"],
      ["Escala","2 bestias (nivel 5-6), 3 (nivel 7-8), 4 (nivel 9+)"],
      ["Twist opcional","Una de las bestias lleva todav\u00eda el collar de una mascota: calmarla en vez de matarla hace que siga al grupo como aliado menor temporal"],
      ["Loot","Entre los restos de la caravana: 2d6 \u00d7 10 po, una Poci\u00f3n de Curaci\u00f3n, y un cofre cerrado (Herramientas de Ladr\u00f3n CD 13) con 1d4 gemas (50 po c/u)"],
    ]),
    pEmpty(100),

    h3("Bandidos Oportunistas \u2014 y su Escondite"),
    p("Una banda (un Cabecilla CR 3 + 3-4 Saqueadores CR 1) tiende una emboscada en el camino o asalta un caser\u00edo. Si el grupo los vence o los sigue, llegan a su escondite: una cueva o granja abandonada de 3 habitaciones con el bot\u00edn robado de pueblos golpeados por la Niebla."),
    pEmpty(60),
    infoTable([
      ["Sala del escondite","Contenido"],
      ["1. La Entrada Vigilada","2 Saqueadores de guardia jugando a los dados. Sorpresa posible (Sigilo). Sobre la mesa: 40 po en monedas de la apuesta"],
      ["2. El Dormitorio Sucio","Catres, basura, y bajo una tabla suelta (Percepci\u00f3n CD 13) una bolsa con 120 po y un mapa que marca d\u00f3nde piensan asaltar despu\u00e9s (gancho de aventura)"],
      ["3. El Alijo","Cofre reforzado (Herramientas de Ladrón CD 15 o forzar). Dentro: el botín del pueblo (devolverlo da reputación), 200 po, una Daga +1 y 3 Pociones de Curación"],
    ]),
    pEmpty(100),

    h3("El Ritual en la Cripta Olvidada — Encuentro Especial (ver Cap. 12 secreto)"),
    warningBox("ESTE ENCUENTRO TIENE UNA CAPA OCULTA. Lo que sigue es la descripción para mostrar en mesa. La verdad completa —incluyendo de quién se trata, por qué vuelve, y las fichas completas de sus tres apariciones— está en el Cap. 12 (sección 12.9), apéndice secreto solo para el DM. NO reveles nada de eso acá. Usá este encuentro en cualquier camino entre la zona 2 y la zona 3 (o donde mejor te quede), idealmente lejos de cualquier pista o rumor previo."),
    pEmpty(80),
    p("El grupo, viajando o explorando por cualquier motivo no relacionado, encuentra la entrada a una cripta o sótano abandonado (una ruina vieja, una cueva con marcas de construcción antigua, lo que mejor encaje en tu camino). Adentro, sin esperarlos, hay un hechicero de mediana edad, piel pálida, a media invocación de un ritual menor — algo de bajo perfil, no necesita explicarse del todo. No lleva capucha. No hay nada en su descripción que debas conectar con ningún NPC anterior."),
    pEmpty(80),
    cdBox([
      ["Sigilo para acercarse sin que los note antes de actuar","14","Los nota a mitad de camino — pierde la sorpresa pero no escapa de inmediato"],
    ]),
    pEmpty(80),
    p("Al notarlos, su reacción es de sorpresa genuina —no los esperaba ahí— pero NO de pánico: responde frío, calculador, casi aburrido, y combate de inmediato para defender lo que estaba haciendo. Este detalle de personalidad es importante y deliberado (ver Cap. 12 para el porqué). Usá la ficha de 'Primera Aparición' de la sección 12.9.4 para las estadísticas completas."),
    pEmpty(80),
    p("Si lo derrotan o lo hacen huir, no suelta nombre ni explicación. Sí deja una pista pequeña y discreta entre sus cosas (un fragmento de libro de conjuros, un objeto con una marca familiar) que puede no significar nada para la mesa todavía — la revelación de quién es realmente llega después, por los medios descritos en la sección 12.9.5 del apéndice secreto. No la apresures."),
    pEmpty(100),

    h3("Saqueadores de la Risa (Zona 1 — Cuerda-Floja)"),
    p("Variante específica para el pueblo eufórico: una banda (Cabecilla CR 3 + 3 Saqueadores CR 1) descubrió que puede robarle a los aldeanos delante de sus narices, porque la alegría artificial los vuelve incapaces de notar nada malo. Es un conflicto con carga emocional: los aldeanos sonríen mientras los desvalijan. Su escondite es un sótano de 3 salas bajo la casa de cometas abandonada."),
    pEmpty(60),
    infoTable([
      ["Sala del sótano","Contenido"],
      ["1. El Trastero","2 Saqueadores empaquetando lo robado. Pilas de pertenencias de los aldeanos (las cometas de Sella, MS-1A, pueden estar aquí). Sorpresa posible"],
      ["2. La Mesa de Reparto","El Cabecilla cuenta el botín. Sobre la mesa: 250 po y una lista de 'casas fáciles' (ayuda a devolver lo robado a sus dueños)"],
      ["3. El Escondrijo","Tras un panel falso (Percepción CD 14): un Anillo de Saltos y 1d6 gemas (50 po c/u), más un objeto sentimental robado de Nira (devolverlo refuerza su confianza, conecta con MS-1C)"],
    ]),
    pageBreak(),

    // ============ DUNGEON AZUL ============
    h2("11.3 DUNGEON — Las Criptas Anegadas (Zona 2 / Escama Azul)"),
    p("Este es el camino expandido a la Escama Azul. Reemplaza el acceso 'f\u00e1cil' del Pantano por una verdadera exploraci\u00f3n. Es totalmente compatible con la escena de la Vieja Ra\u00edz (Cap\u00edtulo 5): cuando el grupo libera (o disipa) a la Vieja Ra\u00edz, su duelo deja de sellar una escalera de piedra oculta bajo el \u00c1rbol de los Cuellos. La Escama Azul no estaba en el \u00e1rbol \u2014se hundi\u00f3, hace generaciones, hasta la tumba m\u00e1s honda de Grauwater. Hay que bajar a buscarla."),
    pEmpty(80),
    warningBox("VERSI\u00d3N SIMPLE vs EXPANDIDA: si prefer\u00eds el acceso r\u00e1pido, liberar a la Vieja Ra\u00edz entrega la escama directamente (como en el Cap. 5). Si quer\u00e9s el dungeon, liberar a la Vieja Ra\u00edz abre la cripta y la escama est\u00e1 al fondo. Eleg\u00ed una de las dos."),
    pEmpty(80),
    secretBox("TENSI\u00d3N DE DISE\u00d1O: la party todav\u00eda NO tiene la respiraci\u00f3n acu\u00e1tica (esa es la recompensa de la Escama Azul, que est\u00e1 al fondo del dungeon). Por eso las salas inundadas obligan a gestionar el aliento (contener la respiraci\u00f3n = 1 + modificador de CON minutos; despu\u00e9s, salvaciones de Constituci\u00f3n para no empezar a ahogarse). Eso convierte el agua en un recurso estrat\u00e9gico, no en decoraci\u00f3n. Pociones de Respiraci\u00f3n Acu\u00e1tica que encuentren en el camino se vuelven valios\u00edsimas."),
    pEmpty(100),

    h3("Mapa general"),
    p("Seis \u00e1reas conectadas. El nivel del agua sube a medida que bajan, as\u00ed que las primeras salas est\u00e1n semiinundadas y las \u00faltimas, totalmente sumergidas. Hay un atajo (una compuerta) que un grupo observador puede usar para drenar parte del agua y facilitar el final."),
    pEmpty(80),

    h3("Área 1 — La Escalera Sumergida"),
    voiceBox("\"Donde antes flotaba el dolor de la Vieja Raíz, ahora hay un hueco oscuro en la raíz del árbol, y unos escalones de piedra que descienden hacia el agua negra. Cada escalón que baja está más sumergido que el anterior. Algo se mueve bajo la superficie.\""),
    p("Encuentro: 2 Anegados (CR 2) acechan bajo el agua (Ventaja para esconderse). Reto: una rueda de hierro oxidada en la pared (Fuerza CD 15, o Arcanos/Herramientas para destrabarla con maña) abre una compuerta que baja el nivel del agua de TODO el dungeon en un nivel, facilitando las salas siguientes. Loot: en una grieta (Percepción CD 13), una Poción de Respiración Acuática."),
    pEmpty(80),
    noteBox("OBJETO DEL VADO (1 de 5) — El Anzuelo de Hueso","Enterrado en el limo de los escalones hay un viejo anzuelo de hueso atado a un sedal podrido. Percepción CD 13 para notarlo entre el barro. Pertenece a la estatua del Pescador en el Área 5.","E8F8F8",C.tealDark),
    pEmpty(80),

    h3("Área 2 — El Salón de los Nombres"),
    p("Las paredes están cubiertas de nombres tallados: los muertos de Grauwater a lo largo de los siglos. Reto de puzzle (conecta con MS-2A): tres nichos sellados tienen cerraduras con un nombre incompleto. Hay que emparejar cada nombre con el de las cuerdas del Árbol de los Cuellos (Aldric Tresfondo, Yenna la Curandera, el niño sin nombre de los Hask). Resolverlo abre los nichos."),
    pEmpty(60),
    cdBox([
      ["Investigación para leer los nombres y notar el patrón","13","Ven nombres pero no la conexión con las cuerdas"],
      ["Historia o memoria de MS-2A para emparejarlos","Auto si hicieron MS-2A","Si no hicieron MS-2A: prueba y error, cada error suelta 1 Anegado"],
    ]),
    p("Loot de los nichos: ajuar funerario — 3d6 × 10 po en monedas antiguas, 2 gemas (100 po c/u) y un Amuleto del Pulmón Sereno (objeto mágico: 1 vez por día, respirás bajo el agua 10 minutos — utilísimo aquí mismo)."),
    pEmpty(80),
    noteBox("OBJETOS DEL VADO (2 y 3 de 5)","Dentro de los nichos, junto al ajuar: (2) un Barquito de Madera tallado a mano, juguete de un niño — está en el nicho del 'niño sin nombre de los Hask', se ve automáticamente al abrir los nichos. Pertenece a la estatua de la Madre. (3) un Frasco de Hierbas Secas con el sello de una sanadora — en el nicho de Yenna la Curandera, Investigación CD 12 para distinguirlo del resto del ajuar. Pertenece a la estatua de la Sanadora.","E8F8F8",C.tealDark),
    pEmpty(80),

    h3("Área 3 — La Cámara de las Ofrendas"),
    p("Una sala semiinundada llena de ofrendas que las familias dejaban por sus muertos. Encuentro: 4 Anegados (CR 2) emergen cuando el grupo toca el tesoro. Si drenaron el agua en el Área 1, los Anegados pelean en tierra (sin su ventaja de Arrastre) — recompensa por la exploración inteligente. Loot: 600 po en ofrendas, una Perla del Poder (devuelve un espacio de conjuro 1/día) escondida en una urna (Investigación CD 14)."),
    pEmpty(80),
    noteBox("OBJETO DEL VADO (4 de 5) — La Medalla Deslucida","Entre las ofrendas hay una medalla militar de bronce, ennegrecida por el agua. Investigación CD 13 para reconocerla bajo las otras ofrendas. Pertenece a la estatua del Soldado en el Área 5.","E8F8F8",C.tealDark),
    pEmpty(80),

    h3("Área 4 — El Pozo del Duelo"),
    voiceBox("\"Un pozo vertical inundado se hunde en la oscuridad. En el agua, una figura hecha de agua oscura revive, una y otra vez, el instante de ahogarse. Cada vez que 'muere', el agua del pozo tiembla.\""),
    p("Mini-jefe: la Pena Ahogada (CR 4). Recordá su rasgo 'Atada al dolor': el grupo puede vencerla con compasión (roleplay / Persuasión CD 15 hablándole del recuerdo) en lugar de solo a golpes — coherente con el tema de la zona. Vencerla (de cualquier forma) hace descender una plataforma que da acceso al fondo. Loot: en el lecho del pozo, 2 Pociones de Respiración Acuática y 300 po en monedas hundidas."),
    pEmpty(80),
    noteBox("OBJETO DEL VADO (5 de 5) — La Carta Sellada","Cuando la Pena Ahogada es vencida, deja caer un tubo de cuero impermeable con una carta nunca entregada dentro. Se obtiene automáticamente al derrotarla (de cualquier forma). Pertenece a la estatua de la Niña en el Área 5. Si el grupo la venció con compasión, la carta está intacta; si la mataron a golpes, está medio borrada (no cambia la mecánica, solo el tono).","E8F8F8",C.tealDark),
    pEmpty(80),

    h3("Área 5 — El Vado de los Recuerdos"),
    p("Una sala totalmente sumergida con cinco estatuas de dolientes, cada una con las manos extendidas, vacías. Reto sin combate: para abrir la puerta del fondo hay que poner en las manos de cada estatua el objeto que le falta. Los cinco objetos están repartidos por las áreas anteriores (ver los recuadros 'OBJETO DEL VADO' de las Áreas 1 a 4). Si el grupo exploró con cuidado, ya los tiene encima."),
    pEmpty(80),
    p("Qué estatua pide qué objeto (Perspicacia o Investigación CD 12 para deducir cada emparejamiento; las estatuas tienen pistas talladas — un ancla, una cuna, un caduceo, una espada, una pluma):"),
    pEmpty(60),
    infoTable([
      ["Estatua","Objeto que le falta","De dónde sale"],
      ["El Pescador (ancla tallada)","El Anzuelo de Hueso","Área 1, limo de los escalones (Percepción CD 13)"],
      ["La Madre (cuna tallada)","El Barquito de Madera","Área 2, nicho del niño Hask (automático al abrir nichos)"],
      ["La Sanadora (caduceo tallado)","El Frasco de Hierbas Secas","Área 2, nicho de Yenna (Investigación CD 12)"],
      ["El Soldado (espada tallada)","La Medalla Deslucida","Área 3, entre las ofrendas (Investigación CD 13)"],
      ["La Niña (pluma tallada)","La Carta Sellada","Área 4, la suelta la Pena Ahogada al ser vencida (automático)"],
    ], 2400, 2800, 4160),
    pEmpty(80),
    p("Al colocar el objeto correcto, la estatua cierra las manos con suavidad y una luz azul tenue la recorre. Con las cinco completas, la puerta del fondo se abre sola y el agua de la sala baja, dando paso al Área 6."),
    pEmpty(80),
    warningBox("LA PRISA SE CASTIGA: si el grupo intenta forzar la puerta sin completar las estatuas (o pone objetos en la estatua equivocada 3 veces), una corriente furiosa los arrastra de vuelta al Área 4: cada personaje hace Fuerza CD 14 o es empujado fuera de la sala y debe volver a entrar (perdiendo tiempo y aliento). Es el eco mecánico del tema de la zona: el duelo no se apura. Si les falta un objeto porque no lo encontraron, pueden volver a buscarlo — la sala espera."),
    pEmpty(80),
    secretBox("Si tu grupo es más de combate que de puzzle, podés bajar todas las CD de emparejamiento a 'automático' y dejar que el reto sea simplemente haber explorado bien para tener los 5 objetos. El corazón de la sala es el momento, no la dificultad de la tirada."),
    pEmpty(80),

    h3("\u00c1rea 6 \u2014 La Tumba Honda"),
    p("La c\u00e1mara m\u00e1s profunda, totalmente bajo el agua. En un sarc\u00f3fago de cristal descansa la Escama Azul, brillando d\u00e9bilmente. Jefe final del dungeon: cuando la toman, el guardi\u00e1n de la tumba despierta."),
    pEmpty(60),
    warningBox("JEFE SOLITARIO \u2014 AJUSTE YA APLICADO: el bloque de abajo ya incluye el 'Ajuste de Jefe Solitario' de la secci\u00f3n 11.0 (184 PG + 3 acciones legendarias) horneado como su versi\u00f3n est\u00e1ndar. No es opcional ni hay que sumar nada: esto es lo que el Sepulturero tiene de base, para que no se caiga en 2 rondas contra 6 'turnos' de party por asalto."),
    pEmpty(60),
    ...stat("El Sepulturero Anegado", "CR 6", "El primer enterrador de Grauwater, que se ahog\u00f3 cavando la \u00faltima tumba y nunca dej\u00f3 su puesto. No quiere hacer da\u00f1o: quiere que NADIE se lleve a 'sus' muertos. No-muerto.",
      [["CA / PG / Vel","14 / 184 / 9 m, nadar 12 m"],
       ["Atributos","FUE +4, DES +1, CON +4, INT +0, SAB +3, CAR +2"],
       ["Resist. / Inmun.","Resistente a da\u00f1o no m\u00e1gico, necr\u00f3tico; Inmune a veneno, encantado, agotamiento; Vulnerable a fuego (dif\u00edcil bajo el agua)"],
       ["Sentidos / Idiomas","Visi\u00f3n en la oscuridad 18 m; Percepci\u00f3n pasiva 15 / Com\u00fan"]],
      [["Multiataque","Una Pala sepulcral y un Agarre de la marea"],
       ["Pala sepulcral","+7 al impacto, 2d8+4 contundente"],
       ["Agarre de la marea (acci\u00f3n)","Una criatura a 3 m hace Fuerza CD 15 o es arrastrada 3 m y agarrada bajo el agua"],
       ["Marea creciente (recarga 6)","El agua de la sala se agita: todos hacen Destreza CD 15 o 4d6 contundente y son empujados 3 m"],
       ["Acciones legendarias (3 por ronda)","Al final del turno de otro personaje, el Sepulturero puede usar una de las siguientes (no puede repetir la misma dos veces seguidas). Recupera las 3 al empezar su propio turno"],
       ["\u2014 Palazo","Un ataque adicional de Pala sepulcral (+7, 2d8+4 contundente)"],
       ["\u2014 Llamar a los ahogados","Convoca a 1 Anegado desde el agua de la sala (m\u00e1x. 3 invocados por combate). Aparece adyacente al Sepulturero y act\u00faa en la siguiente iniciativa"],
       ["\u2014 Marea defensiva","El agua se arremolina a su alrededor: el pr\u00f3ximo ataque que reciba antes de su siguiente turno tiene Desventaja"],
       ["Descansad ya (rasgo)","Si el grupo le muestra que los muertos de Grauwater est\u00e1n en paz (mencionar la liberaci\u00f3n de la Vieja Ra\u00edz, o haber resuelto el Vado del \u00c1rea 5), el Sepulturero baja la pala: deja de atacar y entrega la escama. V\u00eda pac\u00edfica al jefe final"]]),
    p("Loot final: la Escama Azul + el tesoro acumulado de la tumba: 1.000 po en gemas y monedas, una Capa de la Mantarraya (nadar 18 m, respirar bajo el agua, mientras la lleves puesta) y, si vencieron al Sepulturero con compasi\u00f3n, su pala se vuelve un objeto m\u00e1gico: Pala del Descanso (+1, y 1/d\u00eda pod\u00e9s lanzar Hablar con los Muertos)."),
    pageBreak(),

    // ============ DUNGEON HOTENOW (opcional) ============
    h2("11.4 DUNGEON OPCIONAL — Las Galerías Profundas (Zona 3 / Hotenow)"),
    p("El ramal sellado del mapa de túneles de Rhen (MS-3A). NO es necesario para conseguir la Escama Roja —es un dungeon-bonus de saqueo para grupos que quieran más exploración y tesoro. Una antigua bóveda-fragua enana, sellada hace décadas cuando los enanos huyeron de una infestación de criaturas de fuego."),
    pEmpty(80),

    h3("Área 1 — La Puerta Sellada"),
    p("Una puerta de piedra con una advertencia grabada en enano: 'Lo que arde aquí dentro, que aquí se quede.' Abrirla requiere Fuerza CD 17 (entre varios) o resolver el cierre enano (Herramientas / Arcanos CD 15). Al abrir, sale una ráfaga de calor."),
    pEmpty(80),
    p("Encuentro: el ruido de abrir la puerta (sea con fuerza o con maña) despierta a 2 Brasas Iracundas (CR 3) que quedaron atrapadas en esta antesala desde que los enanos sellaron la bóveda hace décadas. No es un combate duro, pero anticipa el patrón de la siguiente sala. Si el grupo abre la puerta con cuidado extremo (Sigilo CD 15 además de la tirada de apertura), puede evitar despertarlas y entrar sin combate."),
    pEmpty(80),
    p("Loot: las Brasas custodiaban, sin saberlo, un nido de cenizas con restos del último grupo de mineros enanos que no llegó a salir — entre los huesos y el metal fundido, una bolsa de cuero resistente al fuego con 80 po y un mapa rudimentario que marca la ubicación aproximada de las otras tres áreas del dungeon (si el grupo no tenía ya el mapa completo de Rhen, esto cumple la misma función)."),
    pEmpty(80),

    h3("Área 2 — La Galería de Brasas"),
    p("Encuentro: 3 Brasas Iracundas (CR 3) anidan entre estalactitas de obsidiana. Hazard: cristales rojos explosivos en las paredes (como en la superficie). Pelear con cuidado de no detonarlos es parte del reto. Loot: entre las cenizas, 1d6 gemas de fuego (75 po c/u)."),
    pEmpty(80),

    h3("Área 3 — El Taller Olvidado"),
    p("Una fragua enana intacta, congelada en el tiempo: el fuelle reseco, el yunque frío, las herramientas colgadas con polvo de décadas. Si el grupo reactiva la fragua, puede usarla. El puzzle son 3 pasos en orden — cada uno es una tirada distinta y cada paso habilita el siguiente."),
    pEmpty(60),
    bullet("PASO 1 — Limpiar el conducto del fuelle: el fuelle de cuero está agrietado y el conducto, tapado con ceniza endurecida. Herramientas de Artesano (herrero) CD 13, o Destreza CD 14 con improvisación. Fallo: el fuelle suelta una nube de ceniza caliente (1d4 fuego, Destreza CD 11 para evitar) y hay que reintentar."),
    bullet("PASO 2 — Reencender la fragua: la fragua necesita una chispa intensa. Se puede con magia de fuego (automático), con pedernal y buena maña (Supervivencia CD 13), o llevando una Brasa Iracunda viva del Área 2 hasta el hogar (sin tirada, pero hay que cargarla — Arcanos CD 12 para manipularla sin quemarse). El fuego prende y la fragua ruge por primera vez en décadas."),
    bullet("PASO 3 — Templar el yunque: el yunque enano lleva tanto frío que es quebradizo. Hay que calentarlo gradualmente y asentarlo (Fuerza CD 13 para manejar el ritmo del martillo, o Herramientas de Artesano CD 12). Con éxito, el yunque 'despierta' y resuena con una nota limpia."),
    pEmpty(80),
    p("Recompensa por reactivar la fragua: el grupo puede forjar UNA mejora gratuita aquí mismo (necesita ~1 hora y materiales que hay en el taller): darle Resistencia al Fuego permanente a una pieza de armadura, O convertir un arma común en un arma +1. Solo una pieza — elijan bien. Loot adicional: un Manto de Resistencia al Fuego colgado de un perchero, 400 po en lingotes de hierro estelar, y un juego de Herramientas de Herrero de calidad enana (ventaja en futuras tiradas de herrería)."),
    pEmpty(80),
    secretBox("HALLAZGO OCULTO — EL BRAZAL SIN MIEDO: Investigación CD 15 (aparte de las tiradas de la fragua) nota, colgado detrás de las herramientas de herrero, un brazal de hueso pulido que no encaja con el resto del taller — no es trabajo enano. Es un fragmento de Guardián antiguo (ficha completa en Cap. 12, sección 12.11). No hay explicación de cómo llegó ahí; ni el diario del enano lo menciona. Un cabo suelto deliberado."),
    pEmpty(80),
    secretBox("Conexión opcional con Hotenow: si Korrund sigue vivo y en paz (resolvieron bien su arco), reactivar esta fragua le emociona — puede venir a verla y ofrecerse a forjar algo mejor para el grupo (a criterio del DM, un objeto raro). El viejo gigante reconoce el trabajo enano y lo respeta."),
    pEmpty(80),

    h3("Área 4 — La Veta Profunda"),
    voiceBox("\"La cámara final es un horno natural, y sus paredes están cubiertas de los mismos cristales rojos que el grupo ya vio en la superficie (sección 6.3) — más pequeños aquí, más numerosos, latiendo con un brillo parejo como un corazón colectivo. Pero al fondo, clavado en la roca como una espada en una losa, hay UNO solo, del tamaño de un torso, que no late: arde. Su luz no parpadea — es constante, casi blanca en el centro.\""),
    p("Jefe: la Salamandra del Furor (CR 5, ficha en sección 11.1) custodia el tesoro enano, enroscada justo debajo del cristal grande. Los cristales pequeños de las paredes funcionan igual que los de la Sala de Cristales de Hotenow (sección 6.3): tocarlos da 1d4 de daño de fuego y una visión flash de 6 segundos."),
    pEmpty(80),
    noteBox("EL CRISTAL GRANDE — EFECTO RELACIONADO PERO DISTINTO","Mientras los cristales pequeños guardan FRAGMENTOS sueltos del dolor de Korrund (visiones breves, pasivas, solo al tocarlos), el cristal grande es donde toda esa ira que nunca encontró salida se concentró sin freno durante años. No da una visión al tocarlo: libera una EXPLOSIÓN DE FURIA CONCENTRADA si recibe daño o se rompe (a propósito o en medio del combate, si la Salamandra empuja a alguien contra él). Cuando esto pasa, todas las criaturas en 6 m hacen Constitución CD 16: con fallo, 4d8 de fuego y Desventaja en su próxima tirada de ataque; con éxito, mitad y sin penalización. La Salamandra, si está cerca, en cambio se CURA 2d8 PG (se alimenta de esa misma ira) — así que dejarlo intacto durante el combate, o atraerla lejos antes de romperlo, es una decisión táctica real.","FFF8E7",C.goldDeep),
    pEmpty(80),
    p("Si el grupo rompe el cristal grande DESPUÉS de vencer a la Salamandra (sin presión de combate), pueden hacerlo con cuidado: Destreza CD 13 para no estar demasiado cerca cuando estalla. Dentro, encuentran un fragmento de memoria mucho más nítido que cualquiera de los chicos: la imagen completa y clara de Korrund forjando el pendiente para Brynna. Si el grupo todavía no encontró el pendiente perdido (MS-3B) o no llegó a la decisión moral de Korrund (sección 6.5), esto cuenta como pista válida y automática para habilitar las Opciones A o C."),
    pEmpty(80),
    p("Loot final: 1.500 po en gemas y oro fundido en lingotes, un Martillo de Brasa (martillo de guerra +1, +1d6 fuego), y el diario de un enano que menciona —sin saberlo— al 'anciano del libro azul' que pasó por Hotenow (pista extra del Coleccionista)."),
    pageBreak(),

    // ============ DUNGEON VERDE ============
    h2("11.5 DUNGEON \u2014 Las Ra\u00edces Hondas (Zona 4 / Escama Verde)"),
    p("El camino expandido a la Escama Verde. El mecanismo de la superficie (Cap. 7, secci\u00f3n 7.6) es solo la tapa: el verdadero coraz\u00f3n del bosque late en las cavernas de ra\u00edces bajo el \u00c1rbol Central. Para darle cuerda de verdad \u2014y liberar la escama\u2014 hay que descender. Es tambi\u00e9n de donde salieron los Centinelas: aqu\u00ed est\u00e1 su cripta de origen."),
    pEmpty(80),
    warningBox("VERSI\u00d3N SIMPLE vs EXPANDIDA: si prefer\u00eds el acceso r\u00e1pido, el puzzle de superficie de 7.6 sigue funcionando para conseguir la escama. Si quer\u00e9s el dungeon, el mecanismo de superficie est\u00e1 'atascado' y obliga a bajar a las Ra\u00edces Hondas para arreglarlo desde dentro. Eleg\u00ed una de las dos."),
    pEmpty(80),
    secretBox("TEMA MEC\u00c1NICO: este dungeon es sobre el movimiento y la quietud (la emoci\u00f3n de la zona es la Calma vuelta par\u00e1lisis). Varias salas penalizan moverse r\u00e1pido o premian moverse en el momento justo. El P\u00edcaro del DM brilla aqu\u00ed. Sin la Escama Verde a\u00fan, el grupo no tiene la Ventaja en Sigilo \u2014la consiguen al final, como recompensa."),
    pEmpty(100),

    h3("Área 1 — La Raíz Hueca"),
    p("Se entra por una raíz hueca del Árbol Central, descendiendo a una caverna iluminada por hongos azules. Reto suave: la bajada es resbaladiza (Atletismo o Acrobacias CD 12; fallar = 1d6 de caída). Loot: nidos de criaturas pequeñas con 1d4 gemas brillantes (50 po c/u)."),
    pEmpty(80),
    noteBox("PISTA DEL MECANISMO (1 de 3)","Los hongos azules crecen siempre en racimos de UNO solo, y cada cierto rato brillan todos al unísono una vez. Quien lo observe (Naturaleza o Percepción CD 12) y lo anote tiene la primera cifra del puzzle del Área 5: la Raíz se gira 1 vez.","E8F8F8",C.tealDark),
    pEmpty(80),

    h3("Área 2 — El Salón Inmóvil"),
    voiceBox("\"La sala está llena de cosas detenidas a media caída: gotas de agua suspendidas, hojas congeladas en el aire, un pájaro feérico parado en pleno vuelo. El tiempo aquí no fluye —espera. En el techo, un péndulo de luz se balancea muy despacio, y todo en la sala parece 'tensarse' cada vez que pasa por el centro.\""),
    p("El salón es largo y hay que cruzarlo de un extremo al otro. Funciona por TRAMOS: el grupo avanza por tramos de seguridad (marcados por las estatuas congeladas que sirven de refugio). Hay que cruzar 4 TRAMOS en total para llegar a la puerta del fondo."),
    pEmpty(80),
    p("La regla del péndulo: el péndulo de luz tiene un ciclo. Cuando está en REPOSO (en los extremos de su recorrido, ~3 segundos), el tiempo de la sala 'duerme' y moverse es seguro. Cuando se BALANCEA (cruzando el centro), cualquier criatura que se esté moviendo activa la descarga temporal."),
    pEmpty(60),
    infoTable([
      ["Tirada / Desafío","CD","Consecuencia si falla"],
      ["Percepción o Perspicacia para leer el ritmo del péndulo (1 vez, al entrar)","12","Sin leer el ritmo, todas las CD de cruce de abajo suben en +2 (cruzan a ciegas)"],
      ["Cada tramo: avanzar en el momento justo (Acrobacias o Destreza, o Sigilo si el Pícaro lidera)","13","Descarga temporal: 3d6 de fuerza y el personaje queda 'congelado' (pierde su próximo turno). Quedarse quieto en un refugio es siempre seguro: no obliga a tirar"],
      ["Alternativa lenta y segura: esperar el reposo y avanzar sin correr (un tramo por turno, sin tirada)","Auto","Tarda más (4 turnos mínimo) y el ruido/tiempo puede despertar a los Acechantes"],
    ], 3200, 1200, 4960),
    pEmpty(80),
    p("Resumen: 4 cruces de tramo. El Pícaro del DM puede usar Sigilo en vez de Acrobacias y, si lidera, da Ventaja al resto en ese tramo. Encuentro opcional: 2 Acechantes de Hojaverde (CR 5) se descongelan y atacan si alguien falla dos cruces o si el grupo elige la vía lenta y tarda más de 4 turnos."),
    pEmpty(80),

    h3("Área 3 — La Cripta de los Centinelas"),
    voiceBox("\"La cripta es angosta y baja, tallada para lobos de piedra, no para gente. El único paso hacia el Área 4 cruza justo por el centro del suelo, donde generaciones de Centinelas marcharon en círculos de guardia — y el piso, desgastado por ese ritual repetido mil veces, está hundido en un patrón espiral que cede bajo el peso equivocado.\""),
    p("EL CRUCE (obligatorio, sin importar qué hagan con el Centinela dormido): el suelo en espiral tiene placas que activan un mecanismo de defensa antiguo si se pisan fuera de orden. Cruzar requiere seguir la espiral en sentido correcto (Percepción CD 13 para notar el patrón antes de pisar, o Destreza CD 14 para cruzar a las apuradas sin haberlo notado)."),
    pEmpty(60),
    infoTable([
      ["Tirada / Desafío","CD","Consecuencia si falla"],
      ["Percepción para notar el patrón espiral antes de cruzar","13","Cruzan a ciegas: usar la CD de Destreza de abajo sin el beneficio de saber por dónde ir"],
      ["Destreza para cruzar siguiendo el patrón correcto (con Ventaja si notaron el patrón antes)","14","Una placa se hunde: 2d6 de daño contundente (una lanza de piedra sale del muro) y el personaje debe reintentar el cruce desde la mitad"],
      ["Cargar a alguien o algo pesado (golem incluido) sin que pise fuera de patrón","Igual CD, con Desventaja si quien carga no superó su propia tirada antes","El peso extra hace más probable activar una placa equivocada"],
    ], 3200, 1200, 4960),
    pEmpty(80),
    p("Hay tres pedestales en la cripta: dos vacíos (los Centinelas que despertaron arriba) y uno con un TERCER Centinela aún dormido. Esto SÍ es opcional: el grupo puede despertarlo y luchar (Centinela Despertado CR 4), o aprender aquí la 'orden de centinela' (Historia CD 14 leyendo los grabados) que les permite calmar a los Centinelas de la superficie sin pelear. Si lo ignoran del todo y solo cruzan la espiral, no pierden nada más que ese loot y esa opción pacífica con los Centinelas de arriba. Loot del Centinela/grabados (si interactúan): piedra feérica tallada (materiales de encantamiento, 300 po) y un Broche del Guardián (1/día, otorga +2 CA por 1 minuto como reacción)."),
    pEmpty(80),
    noteBox("PISTA DEL MECANISMO (2 de 3) — El orden","Entre los grabados de la cripta hay un friso que muestra el ciclo de una planta: primero la RAÍZ bebe, luego la SAVIA sube, luego la HOJA respira (Historia o Naturaleza CD 12). Ese es el orden de los engranajes del Área 5: Raíz → Savia → Hoja. La tercera pista (las vueltas de Savia y Hoja) está en el Salón Inmóvil del Área 2: el péndulo cumple su ciclo en DOS tiempos (Savia = 2) y hay TRES hojas congeladas en el aire (Hoja = 3).","E8F8F8",C.tealDark),
    pEmpty(80),

    h3("\u00c1rea 4 \u2014 El Jard\u00edn de Cristal"),
    p("Una caverna de una belleza imposible: flores de cristal que tintinean. Es una trampa de calma: quedarse a contemplarlas demasiado (Sabidur\u00eda CD 13 al entrar) hace que un personaje quiera 'descansar un momento' y pierda su primera acci\u00f3n en el pr\u00f3ximo combate. Encuentro: 1 Acechante de Hojaverde (CR 5) y 3 Gorrones (usar Saqueador CR 1 reskin fe\u00e9rico) emboscan desde los cristales. Loot: polen de cristal (vendible, 250 po) y una Flor de Cristal Eterna (foco m\u00e1gico, +1 a CD de salvaci\u00f3n de conjuros)."),
    pEmpty(80),

    h3("Área 5 — El Mecanismo Verdadero"),
    voiceBox("\"El corazón del bosque es una sala circular dominada por tres enormes engranajes de madera viva, cada uno con un símbolo grabado: una RAÍZ, una gota de SAVIA y una HOJA. En el centro, una palanca de hueso de ciervo. Los tres engranajes están detenidos, y la sala entera contiene el aliento.\""),
    p("EL PUZZLE: hay que hacer girar los tres engranajes (Raíz, Savia, Hoja) en el ORDEN correcto y la CANTIDAD correcta de vueltas. Es la cuerda del corazón del bosque. Girar el engranaje correcto requiere Fuerza CD 13 (o el golem de Hola lo hace sin tirada). El reto no es la fuerza: es saber el orden y las vueltas, que se deduce de tres pistas repartidas por el dungeon."),
    pEmpty(80),
    infoTable([
      ["Pista","Dónde estaba","Qué revela"],
      ["El orden","Cripta de los Centinelas (Área 3): los grabados muestran el ciclo de una planta — primero la raíz bebe, luego la savia sube, luego la hoja respira","Orden correcto: RAÍZ → SAVIA → HOJA"],
      ["Las vueltas de la Raíz","La Raíz Hueca (Área 1): los hongos azules crecen en racimos de UNO, brillando al unísono una vez","La Raíz se gira 1 vuelta"],
      ["Las vueltas de la Savia y la Hoja","El Salón Inmóvil (Área 2): el péndulo completa su ciclo en DOS tiempos; las hojas congeladas en el aire son TRES","La Savia se gira 2 vueltas; la Hoja, 3 vueltas"],
    ], 2800, 4200, 2360),
    pEmpty(80),
    p("LA SOLUCIÓN COMPLETA: girar la RAÍZ 1 vuelta, luego la SAVIA 2 vueltas, luego la HOJA 3 vueltas, y por último tirar de la palanca central. Si lo hacen bien, los tres engranajes encajan, el corazón del bosque late por primera vez en meses, y la Escama Verde se libera en el Área 6."),
    pEmpty(60),
    infoTable([
      ["Tirada / Desafío","CD","Consecuencia si falla"],
      ["Investigación o Naturaleza para juntar las tres pistas si el grupo no las anotó","15","Pueden resolverlo por prueba y error, pero cada error despierta al Guardián (ver abajo)"],
      ["Fuerza para girar cada engranaje (o el golem, sin tirada)","13","El engranaje se traba; reintentar cuesta el turno"],
    ], 3200, 1200, 4960),
    pEmpty(80),
    warningBox("EL ERROR DESPIERTA AL GUARDIÁN: cada vez que el grupo gira un engranaje en el orden equivocado o el número equivocado de vueltas, el Guardián Dormido (abajo) se agita y ataca durante 1 round antes de volver a aletargarse. Si acumulan 3 errores, el Guardián despierta del todo y empieza el combate completo. Recordá su rasgo: si completan el puzzle CORRECTAMENTE durante el combate (dividiendo acciones entre pelear y girar engranajes), el Guardián se vuelve a dormir en paz y la pelea termina sin necesidad de matarlo."),
    pEmpty(80),
    secretBox("Si tu grupo prefiere ir directo a las manos, pueden saltarse las pistas, despertar al Guardián a propósito, derrotarlo, y entonces girar los engranajes con calma (el orden correcto está grabado en el propio mecanismo, visible de cerca: Investigación CD 12 una vez que no hay presión). Las dos vías —puzzle elegante o pelea y luego puzzle— funcionan."),
    pEmpty(80),
    pEmpty(60),
    ...stat("El Guardi\u00e1n Dormido", "CR 7", "Un constructo de ra\u00edz y piedra fe\u00e9rica, el jardinero original del coraz\u00f3n del bosque. La par\u00e1lisis lo durmi\u00f3 a medias: pelea como son\u00e1mbulo, lento pero demoledor. No es malvado \u2014defiende el mecanismo de quien lo manipula mal.",
      [["CA / PG / Vel","17 / 136 / 9 m"],
       ["Atributos","FUE +6, DES -1, CON +5, INT +0, SAB +2, CAR +0"],
       ["Resist. / Inmun.","Resistente a da\u00f1o no m\u00e1gico; Inmune a ps\u00edquico, encantado, asustado; Vulnerable a fuego"],
       ["Sentidos / Idiomas","Visi\u00f3n en la oscuridad 18 m; Percepci\u00f3n pasiva 12 / Silvano"]],
      [["Multiataque","2 Pu\u00f1os de ra\u00edz"],
       ["Pu\u00f1o de ra\u00edz","+9 al impacto, 2d10+6 contundente"],
       ["Zarcillos (acci\u00f3n, recarga 5-6)","Ra\u00edces brotan en un \u00e1rea de 6 m: Destreza CD 16 o quedar Apresado (escape CD 16)"],
       ["Son\u00e1mbulo (rasgo)","Act\u00faa siempre al final de la iniciativa (lento). Pero la primera vez que cae por debajo de la mitad de PG, 'despierta' del todo: pierde este rasgo y gana una acci\u00f3n adicional por turno el resto del combate"],
       ["Se lo puede dormir de nuevo (rasgo)","Si el grupo completa el puzzle del mecanismo CORRECTAMENTE mientras pelea (acciones divididas), el Guardi\u00e1n vuelve a dormirse en paz y la pelea termina. Premia hacer las dos cosas a la vez"]]),
    pEmpty(60),

    h3("\u00c1rea 6 \u2014 El Recuerdo del Bosque"),
    p("Al activar el mecanismo, una c\u00e1mara final se ilumina: la Escama Verde flota sobre el primer engranaje. Loot final: la Escama Verde + el tesoro fe\u00e9rico que la Corte dej\u00f3: 1.200 po en gemas vivas (laten suavemente), unas Botas del Paso Persistente (ignoras terreno dif\u00edcil; 1/d\u00eda, Paso Brumoso/Misty Step) y, si calmaron a los Centinelas en vez de destruirlos, la Reina Espina les env\u00eda como agradecimiento una Bellota de la Corte (planta y crece un refugio fe\u00e9rico seguro, 1 uso)."),
    pageBreak(),

    // ============ ACTO III ============
    h2("11.6 Acto III \u2014 Conflictos del Plano del Archivo"),

    h3("Los Custodios de las Salas"),
    p("Cada una de las cinco salas del Archivo (Cap. 8) tiene un Custodio del Archivo (CR 6) dormido, con la variante emocional de su sala. Se activan SOLO si el grupo manipula o intenta robar los frascos (lo que conecta con las 'desventajas' de cada sala). Un grupo cauto puede atravesar el Archivo sin despertarlos; un grupo saqueador tendr\u00e1 hasta cinco peleas. Loot por Custodio: al caer, su porcelana se rompe y revela un n\u00facleo de cristal emocional (200 po c/u) y libera la emoci\u00f3n de un frasco de vuelta al mundo (buena acci\u00f3n)."),
    pEmpty(80),
    warningBox("No conviene activar los cinco a la vez. Pensalos como peligros de sala: el grupo decide cu\u00e1nto riesgo corre por cu\u00e1nto loot. Si quer\u00e9s un pico de tensi\u00f3n, hac\u00e9 que entrar en combate en una sala alerte a Mnem\u00f3s en la Sala 5 (pierden la sorpresa del Final A)."),
    pEmpty(80),

    h3("La Huida del Archivo (solo Final A)"),
    p("Si el grupo derrota a Mnem\u00f3s en combate, el Archivo colapsa. En vez de un simple 'tienen 10 minutos', hac\u00e9 una secuencia de escape con peligros activos por round: estantes que caen (Destreza CD 14, 3d6), frascos que estallan liberando emociones puras (efecto aleatorio: tabla abajo), y pasillos que se cierran (Atletismo/Acrobacias CD 13). Loot de \u00faltimo momento: en la huida pueden agarrar 1d4 frascos sellados (cada uno, una emoci\u00f3n concentrada vendible o usable narrativamente) y el bast\u00f3n personal de Mnem\u00f3s (foco arcano, +1)."),
    pEmpty(60),
    infoTable([
      ["d6","Frasco que estalla cerca durante la huida"],
      ["1","Alegr\u00eda: el personaje r\u00ede y gana 1d8 PG temporales"],
      ["2","Tristeza: Desventaja en el pr\u00f3ximo chequeo de Destreza (sin l\u00e1grimas no se ve bien)"],
      ["3","Ira: +1d6 al pr\u00f3ximo ataque, pero debe atacar a algo este round"],
      ["4","Calma: pierde la reacci\u00f3n este round (demasiado en paz)"],
      ["5","Miedo: Sabidur\u00eda CD 13 o se mueve 6 m hacia la salida sin querer (\u00a1\u00fatil!)"],
      ["6","Asombro: el personaje ve por un instante todo el Archivo y nota una salida m\u00e1s r\u00e1pida (-1 round de huida para todos)"],
    ]),
    pageBreak(),

    // ============ ÍNDICE ============
    h2("11.7 Índice de Encuentros de Combate"),
    p("Tabla de referencia rápida de todo el combate de la campaña, ordenado por momento. CR sugerido asume la party con golem y quimera. PG ya recalibrados — ver sección 11.0 y 11.1."),
    pEmpty(80),
    infoTable([
      ["Encuentro","Ubicación","CR / PG","Loot principal"],
      ["Sombras de Duda","Cualquier zona (navegación)","Variable","—"],
      ["Manada de la Niebla","Caminos entre zonas","2-4 × CR 2 (68 PG c/u)","Oro, poción, gemas"],
      ["Bandidos + Escondite","Acto I / caminos","CR 3 (88) + esbirros (42)","Daga +1, pociones, 360 po"],
      ["El Hechicero de la Cripta (ver Cap. 12 secreto)","Camino entre zona 2 y 3","CR efectivo ~8 (115 PG)","Variable — ver 12.9.4"],
      ["Saqueadores de la Risa","Zona 1 (Amarilla)","CR 3 (88) + esbirros","Botín del pueblo, objeto menor"],
      ["Anegados","Zona 2 (Criptas)","CR 2 c/u (72 PG)","Ofrendas, gemas"],
      ["Pena Ahogada","Zona 2 (Criptas, área 4)","CR 4 (98 PG)","Pociones de respiración"],
      ["Sepulturero Anegado","Zona 2 (jefe Criptas)","CR 6 (184 PG, ver 11.3)","Escama Azul, Capa Mantarraya, 1000 po"],
      ["Brasas / Salamandra","Zona 3 (Galerías, opcional)","CR 3 (78) / CR 5 (120→175 con ajuste)","Martillo de Brasa, 1500 po"],
      ["Centinelas Despertados","Zona 4 (bosque)","CR 4 c/u (100 PG)","Piedra feérica"],
      ["Acechantes de Hojaverde","Zona 4 (Raíces / Hadas)","CR 5 c/u (98 PG)","Polen, foco de cristal"],
      ["Guardián Dormido","Zona 4 (jefe Raíces)","CR 7 (136→176 con ajuste)","Escama Verde, Botas del Paso, 1200 po"],
      ["Custodios del Archivo","Acto III (5 salas)","CR 6 c/u (115 PG)","Núcleos de cristal"],
      ["Mnemós","Acto III (Final A)","CR 14 (190 PG)","Objeto raro, bastón +1, tesoro"],
      ["El Eco del Archivo","Acto III (tras Final B/C, sección 8.9)","CR 14 (210 PG)","Sin loot material — cierre narrativo, Mnemós ayuda en combate"],
      ["Zombis de Karak Dûm","Misión Greyskull (Karak Dûm, Área 1)","CR 1/4 c/u × 4","—"],
      ["Umber Hulks de Karak Dûm","Misión Greyskull (Karak Dûm, Área 2)","CR 5 c/u × 2","Notas de Mira (pista del Área 3)"],
      ["Specters del Gran Derrumbe","Misión Greyskull (Karak Dûm, Área 3)","CR 1 c/u × 3","— (se disuelven; vía pacífica disponible con Angelus)"],
      ["Sombra Anclada","Misión Greyskull (Karak Dûm, Área 4)","CR 5 (78 PG)","400 po en monedas enanas antiguas"],
    ], 2400, 2100, 2200, 3660),
    pEmpty(80),
    secretBox("Si tu grupo prefiere más rol que combate en una sesión dada, recordá que casi todos estos encuentros tienen una vía alternativa (calmar, hablar, resolver un puzzle). El combate está disponible, no obligado — salvo el clímax con Mnemós, que igual ofrece los Finales B y C sin pelear, y El Eco del Archivo, pensado específicamente para que esos finales pacíficos no se queden sin un cierre de combate satisfactorio si tu mesa lo quiere."),
  ];
}
module.exports = { cap11 };