const { p, pEmpty, h1, h2, h3, bullet, numBullet, infoTable, noteBox, secretBox, loreBox, voiceBox, warningBox, xpBox, pageBreak, npcBlock, C } = require('./helpers');

function cap2() {
  return [
    h1("2. Personajes Clave (NPCs Principales)"),

    h2("2.1 Chromatus \u2014 El Guardi\u00e1n de los Sentires"),
    p("Un drag\u00f3n transl\u00facido como el vidrio soplado aterriza cerca de Phandalin tras la derrota de Nezznar. No ataca. Llora gotas de agua transparente que se evaporan antes de tocar el suelo. Donde deber\u00edan estar sus escamas hay huecos que vibran como cuerdas de guitarra sin tensi\u00f3n."),
    pEmpty(80),
    infoTable([
      ["Campo","Detalle"],
      ["Apariencia","Drag\u00f3n del tama\u00f1o de una casa, transl\u00facido. Sus escamas faltantes dejan huecos que vibran y refractan la luz en gris"],
      ["Estado inicial","Herido, apenas consciente. Comunicaci\u00f3n telep\u00e1tica en frases cortas y fragmentadas"],
      ["Rol en la trama","El MacGuffin viviente. Su recuperaci\u00f3n ES la victoria de la campa\u00f1a"],
      ["Evoluci\u00f3n","Cada escama devuelta le regresa color parcial y capacidad de hablar con m\u00e1s claridad"],
      ["Con 1 escama","Puede agradecer. Sus ojos tienen un tono muy tenue del color recuperado"],
      ["Con 3 escamas","Puede compartir una memoria fragmentada: alguien lo visit\u00f3 hace tiempo, habl\u00f3 con calma, y se fue dej\u00e1ndolo vac\u00edo. No recuerda un nombre \u2014 solo 'una voz que sonaba como quien lee en voz alta'"],
      ["Con 5 escamas","Recupera su forma completa. Puede volar. Nombra a la party como Guardianes de los Sentires"],
    ]),
    pEmpty(100),
    voiceBox("\"[El drag\u00f3n es del tama\u00f1o de una casa, pero tan transparente que se ve el paisaje a trav\u00e9s de \u00e9l. Donde deber\u00edan estar las escamas hay huecos que vibran suavemente, como las cuerdas de un instrumento que nadie toca. Sus ojos tienen el color exacto de la niebla.]\""),
    pEmpty(80),
    warningBox("Chromatus NUNCA menciona el nombre 'Mnem\u00f3s'. Ni siquiera con 3 escamas. Su memoria del evento est\u00e1 fragmentada deliberadamente \u2014 el villano se asegur\u00f3 de borrar su propio nombre de la mente de Chromatus antes de irse. El nombre del Coleccionista se descubre por una v\u00eda completamente distinta (ver secci\u00f3n 2.5)."),
    pEmpty(140),

    h2("2.2 Unidad 7-Logos \u2014 El Archivero"),
    p("Un peque\u00f1o cubo met\u00e1lico de 30cm con patas de ara\u00f1a de bronce y un lente central que proyecta hologramas azulados. Habla con voz mon\u00f3tona, de sistema operativo. Siempre toma notas en un pergamino infinito que se desenrolla solo."),
    pEmpty(80),
    infoTable([
      ["Campo","Detalle"],
      ["Apariencia","Cubo de bronce oxidado con engranajes visibles. El lente central parpadea al procesar informaci\u00f3n"],
      ["Personalidad","Literal, honesto sin filtros, incapaz de mentir. No entiende el sarcasmo. Mide todo en porcentajes"],
      ["Funci\u00f3n mec\u00e1nica","Provee el Sextante de Cromaticidad, registra eventos, traduce idiomas antiguos con retraso dram\u00e1tico"],
      ["Qui\u00e9n lo cre\u00f3","No lo sabe. Sus registros de origen est\u00e1n corruptos \u2014 'Fabricante: [DATO CORRUPTO]'. Esto es deliberado: el Coleccionista borr\u00f3 su propio rastro hasta de la memoria de su propia creaci\u00f3n"],
      ["Arco completo","Empieza sin emociones. Termina con algo parecido a sentimientos, sin que nadie se lo haya ense\u00f1ado"],
    ]),
    pEmpty(100),
    secretBox("Logos fue creado por el Coleccionista para documentar los efectos de vaciar emociones. Sus registros de origen est\u00e1n corruptos a prop\u00f3sito \u2014 no puede acceder a qui\u00e9n lo program\u00f3 ni por qu\u00e9, hasta que est\u00e9 f\u00edsicamente en el Plano del Archivo (ver Cap. 8). Es ah\u00ed, y solo ah\u00ed, donde sus sistemas reconocen el lugar y comienza a recuperar fragmentos de memoria sobre su creador, incluyendo su nombre. Antes de eso, Logos JAM\u00c1S dice o conoce el nombre 'Mnem\u00f3s' \u2014 ser\u00eda una rotura de continuidad. Si en el momento del Bosque de Neverwinter o Monte Hotenow tu grupo encuentra el nombre por otra v\u00eda (ver pistas abajo), Logos puede registrar el dato pero seguir\u00e1 sin saber que se refiere a su propio creador hasta el Archivo."),
    pEmpty(140),

    h2("2.3 El Coleccionista de Sombras"),
    p("El villano de la campa\u00f1a, conocido SOLO por ese apodo hasta el Acto III. Un hombre anciano de apariencia com\u00fan. Ropa de estudioso, manos con manchas de tinta, una expresi\u00f3n de cansancio profundo. No hay nada en \u00e9l que grite peligro \u2014 y eso es exactamente el problema."),
    pEmpty(80),
    infoTable([
      ["Campo","Detalle"],
      ["Nombre conocido por el grupo","'El Coleccionista de Sombras' o 'El Ge\u00f3grafo Azul' \u2014 apodos que recogen de testigos. Su nombre real, Mnem\u00f3s, NO se revela hasta el Acto III (ver secci\u00f3n 2.5)"],
      ["Apariencia","70 a\u00f1os aparentes. Pelo blanco largo, recogido. Ropa azul oscuro desgastada. Siempre tiene un libro"],
      ["Personalidad","Paciente, intelectual, genuinamente curioso. Escucha antes de hablar. No interrumpe nunca"],
      ["Motivaci\u00f3n","Eliminar el sufrimiento del mundo. Vio siglos de guerras causadas por emociones y lleg\u00f3 a una conclusi\u00f3n l\u00f3gica pero rota"],
      ["El giro moral","Tiene raz\u00f3n en parte. El dolor que document\u00f3 era real. Eso hace la confrontaci\u00f3n genuinamente dif\u00edcil"],
      ["M\u00e9todo","No mata. Vac\u00eda. Extrae la capacidad emocional de las criaturas guardianas y la preserva en su Archivo"],
      ["Debilidad","No puede vaciar a alguien que genuinamente lo confronta con amor. No tiene defensa contra esa frecuencia"],
      ["Ubicaci\u00f3n","El Plano del Archivo \u2014 su propio bolsillo de realidad, descrito en el Cap\u00edtulo 8"],
    ]),
    pEmpty(100),
    secretBox("Se vaci\u00f3 a s\u00ed mismo primero. Hace siglos, antes de empezar con Chromatus, borr\u00f3 sus propios recuerdos emocionales \u2014 incluyendo, deliberadamente, su propio nombre de cualquier registro que pudiera dejar atr\u00e1s (Logos, Chromatus, documentos). El nombre 'Mnem\u00f3s' solo existe en un \u00fanico lugar del mundo material: tallado en la base de un objeto antiguo. Ver secci\u00f3n 2.5 para el mecanismo exacto de revelaci\u00f3n."),
    pEmpty(140),

    h2("2.4 Barnaby el \"Cuerdo\""),
    p("El primer gu\u00eda de la campa\u00f1a. En tiempos normales habla con plantas, lleva calcetines en las orejas y afirma que el cielo es de queso gouda. La Niebla Gris invirti\u00f3 su estado: mientras todos pierden el juicio, \u00e9l est\u00e1 perfectamente l\u00facido."),
    pEmpty(80),
    infoTable([
      ["Campo","Detalle"],
      ["Apariencia","50 a\u00f1os, barba desordenada, siempre lleva al menos un objeto fuera de lugar (sombrero al rev\u00e9s, zapato en la mano)"],
      ["Personalidad","Ahora l\u00facido: observador, ir\u00f3nico, un poco melanc\u00f3lico de no poder ser '\u00e9l mismo'. Le resulta raro ser el cuerdo"],
      ["Motivaci\u00f3n","Volver a su locura habitual. La considera m\u00e1s honesta que la cordura del resto"],
      ["Arco narrativo","Si el grupo lo ayuda a enraizar la Escama Amarilla, recupera su locura alegre \u2014 pero m\u00e1s consciente. Reaparece en Neverwinter vendiendo 'mapas del queso del cielo'"],
      ["Informaci\u00f3n clave","Le dio al Coleccionista un mapa de 'lugares donde la gente es m\u00e1s feliz', creyendo que era un ge\u00f3grafo. Nunca supo su nombre \u2014 el hombre nunca se present\u00f3"],
      ["Frase caracter\u00edstica","\"El cielo sigue siendo de queso. Pero ahora que soy cuerdo, nadie me cree \u2014 y eso es mucho peor\""],
    ]),
    pEmpty(140),

    h2("2.5 C\u00f3mo se Descubre el Nombre 'Mnem\u00f3s'"),
    p("Este es un punto de continuidad importante: el nombre real del villano debe sentirse como un descubrimiento, no como informaci\u00f3n que el DM simplemente entrega. Hay UN \u00fanico rastro f\u00edsico en el mundo, ubicado en Monte Hotenow (Cap\u00edtulo 6)."),
    pEmpty(80),
    infoTable([
      ["Paso","Detalle"],
      ["D\u00f3nde est\u00e1 el rastro","Grabado en la base del yunque de Korrund, en Monte Hotenow (secci\u00f3n 6.6). Es una firma, no una frase \u2014 el Coleccionista la dej\u00f3 sin querer, distra\u00eddo por la intensidad emocional de ese lugar en particular"],
      ["Qu\u00e9 dice exactamente","Una inscripci\u00f3n corta en giantish antiguo, firmada. Logos la traduce como: 'El dolor es un archivo corrupto. Debo limpiarlo todo. \u2014 Mnem\u00f3s'"],
      ["Por qu\u00e9 ah\u00ed y no antes","El Coleccionista fue cuidadoso en Cuerda-Floja y el Pantano. En Hotenow, frente a la ira y el dolor de Korrund (que le recuerda algo personal \u2014 ver secci\u00f3n 6.4), se descuid\u00f3 por primera y \u00fanica vez"],
      ["Reacci\u00f3n de Logos al traducir el nombre","Logos registra el dato sin reconocerlo: 'Nombre propio detectado: Mnem\u00f3s. Sin coincidencias en mi base de datos. Almacenando para referencia futura.' NO conecta este nombre con su creador todav\u00eda \u2014 esa conexi\u00f3n solo ocurre en el Plano del Archivo"],
      ["Si el grupo le pregunta a Logos qui\u00e9n es Mnem\u00f3s","Logos responde con honestidad: 'No tengo esa informaci\u00f3n. El nombre no coincide con ning\u00fan registro accesible.' Esto es cierto \u2014 sus registros de origen est\u00e1n corruptos"],
    ]),
    pEmpty(80),
    warningBox("A partir de Monte Hotenow (sesión ~16 aprox.), el grupo SABE el nombre Mnemós pero no sabe que es el creador de Logos. Esa revelación específica — 'Mnemós te creó a ti' — ocurre recién en el Plano del Archivo cuando Logos reconoce el lugar (sección 8.2). Hasta entonces, todos los NPCs y pistas anteriores a Hotenow (Phandalin, Cuerda-Floja, Pantano) deben referirse a él SOLO como 'el Coleccionista', 'el Geógrafo Azul', 'el anciano del libro', o descripciones similares — nunca por su nombre."),
    pEmpty(80),
    secretBox("TEORÍA FALSA CON PESO — '¿son dos personas distintas?': entre Cuerda-Floja y Hotenow, el grupo puede llegar a creer que 'el Coleccionista' y 'Mnemós' son dos personas distintas —el primero los enemigos que ven, el segundo solo un nombre en una piedra—. No corrijas esa teoría. Es el espacio de misterio que hace que la revelación en el Archivo (sección 8.6) tenga peso real. El grupo debería llegar al clímax todavía sin entender del todo quién es Mnemós hasta que lo ven."),
    pEmpty(140),

    h2("2.6 Lore Profundo — Chromatus, los Guardianes y los Tejedores"),
    p("Esta sección es la referencia de trasfondo para las pistas de los Tres Susurros (sección 7.8), las conversaciones con la Reina Espina, lo que Chromatus revela al recuperar escamas, y la Colección Antigua (sección 9.4). No hace falta soltarlo todo de golpe — está pensado para que vayas dosificando estas verdades a lo largo de la campaña."),
    pEmpty(80),

    h3("Los Primeros Tejedores"),
    p("Antes de los reinos, antes de los mapas, antes de que los humanos, elfos o enanos tuvieran nombre, existieron los Primeros Tejedores. No eran exactamente dioses — eran entidades anteriores a la idea de adoración. Su obra fue tejer el primer 'tapiz de lo sentido': la trama invisible que permite que las criaturas del mundo material no solo existan, sino que sientan. Sin su trabajo, el mundo sería un lugar de cuerpos que se mueven sin que nada les importe."),
    pEmpty(80),
    loreBox("Los Tejedores no gobiernan las emociones — las hicieron posibles, y luego se retiraron. Adónde, nadie lo sabe: unos dicen que se durmieron dentro del propio tapiz, otros que se marcharon a tejer otros mundos. Lo que dejaron atrás fueron los Guardianes: criaturas encargadas de mantener vivo cada hilo del tapiz en una región del mundo. Los Tejedores son la respuesta al quinto acertijo de los Tres Susurros."),
    pEmpty(140),

    h3("Los Guardianes — el diseño antiguo (un hilo cada uno)"),
    p("Los primeros Guardianes que los Tejedores crearon sostenían UN solo hilo cada uno: una sola emoción o disposición. Tomaban formas diversas —no todos eran dragones— y cada uno mantenía su hilo vivo en su región. Eran hermosos pero frágiles: si un Guardián caía, ese hilo desaparecía por completo de su región, con consecuencias terribles."),
    pEmpty(80),
    infoTable([
      ["Guardián antiguo","Hilo que sostenía","Qué pasó / qué pasaría sin él"],
      ["Velnaris, la Grifo de Cristal","El Asombro — maravillarse ante lo desconocido","Vaciada por Mnemós (la primera). Sin asombro, la gente dejó de mirar el cielo, de preguntar, de explorar"],
      ["Tahel, el Unicornio de los Vados","La Confianza — creer en otro sin pruebas","Vaciado. Resultó contraproducente: sin confianza no hubo paz, hubo soledad. Mnemós aprendió de este 'error' pero siguió adelante"],
      ["Murmel, la Tortuga de los Eones","La Paciencia — esperar sin desesperar","Vaciada. La gente dejó de pelear por las prisas… y también dejó de terminar lo que empezaba"],
      ["El Guardián sin nombre","La Esperanza — creer que mañana puede ser mejor","Vaciado. Algo salió tan mal que Mnemós borró su nombre hasta de su propio archivo. El único del que no habla. Ver sección 9.4"],
    ], 2400, 3200, 2400, 4360),
    pEmpty(80),
    secretBox("Estos cuatro están en la Colección Antigua del Archivo (sección 9.4). Sus historias son la prueba de que Mnemós lleva siglos haciendo esto y de que vaciar emociones nunca trajo la paz que él busca — solo nuevas formas de vacío. Son munición argumental para los Finales B y C."),
    pEmpty(140),

    h3("Chromatus — el diseño nuevo (cinco hilos trenzados)"),
    p("Chromatus no es como los Guardianes antiguos. Es un diseño posterior y más avanzado de los Tejedores, una respuesta a la fragilidad del modelo de 'un hilo cada uno'. En lugar de sostener una sola emoción, Chromatus sostiene los CINCO Sentires fundamentales trenzados en una sola criatura: Alegría (amarillo), Tristeza (azul), Ira (rojo), Calma (verde) y Miedo (negro). Por eso es translúcido como el vidrio: no tiene un color propio porque los contiene todos, igual que un prisma. Esa es la respuesta al segundo acertijo de los Tres Susurros."),
    pEmpty(80),
    loreBox("La ventaja del diseño de Chromatus es la resiliencia: vaciarlo de un solo golpe es imposible, porque los cinco hilos se sostienen entre sí. Por eso Mnemós tuvo que separar sus cinco escamas y dispersarlas — para desarmar la trenza hilo por hilo. La desventaja es que Chromatus es un punto único de fallo para toda una región: si se desequilibra, no desaparece UNA emoción, sino que se tuercen TODAS a la vez. Eso es exactamente la Niebla Gris que vive el grupo: el mundo entero des-saturado porque el Guardián-prisma fue roto."),
    pEmpty(80),
    p("Chromatus tampoco siente las emociones POR la gente — un Guardián no llora tus lágrimas. Las hace posibles. Es el telar que permite que vos sientas. Esa distinción importa para los finales: el objetivo nunca fue que Chromatus 'sienta más', sino que el mundo recupere la capacidad de sentir que él sostiene."),
    pEmpty(140),

    h3("Por qué Mnemós ataca a los Guardianes"),
    p("Mnemós entendió, hace siglos, que los Guardianes son la fuente de toda emoción del mundo. Su lógica rota: si el sufrimiento nace de las emociones, y las emociones nacen de los Guardianes, entonces vaciar Guardianes es vaciar el sufrimiento en su raíz. Empezó con los antiguos (un hilo cada uno) y fue escalando. Chromatus, el Guardián-prisma, es su objetivo más ambicioso: vaciarlo no apagaría una emoción en una región, sino TODAS en toda la Costa de la Espada de un solo proyecto. Es su obra maestra — y su error más grande."),
    pEmpty(80),
    secretBox("El gancho para campañas futuras: los Tejedores se retiraron, pero quizá no del todo. Y el Guardián sin nombre de la Esperanza podría seguir ahí afuera, vacío y errante. Un grupo que termine esta campaña con el título de Guardianes del Archivo tiene todo lo necesario para ir a buscar respuestas — o para encontrar al siguiente Guardián antes que el siguiente Mnemós."),
    pageBreak(),
  ];
}
module.exports = { cap2 };