const { p, pEmpty, h1, h2, h3, bullet, numBullet, infoTable, noteBox, secretBox, loreBox, voiceBox, warningBox, cdBox, xpBox, scaleBox, pageBreak, npcBlock, C } = require('./helpers');

function cap8() {
  return [
    h1("8. Zona 5 \u2014 El Plano del Archivo (El Cl\u00edmax)"),
    scaleBox("\u26ab","Negra","Miedo","El Plano del Archivo \u2014 el mundo propio del Coleccionista",C.blackDark,"F5F5F5"),
    pEmpty(100),

    h2("8.1 Cómo el Grupo Descubre que Debe Abrir un Portal en una Biblioteca"),
    p("Esta es la pieza final del rompecabezas, y debe sentirse como una deducción del grupo, no como información entregada. El mecanismo completo:"),
    pEmpty(80),
    infoTable([
      ["Paso","Qué pasa"],
      ["1. El Sextante no encuentra la quinta ubicación","Cuando las 4 escamas están en el Tarro de Almas, Logos intenta calibrar el Sextante para la quinta. Falla repetidamente: 'Error 404: ubicación no encontrada. La frecuencia no es geográfica.'"],
      ["2. La pista de la Colección Antigua (si la consiguieron) o de Vex (Taller del Recuerdo)","Si el grupo investigó al agente Vex (sección 9.1) o consiguió pistas adicionales, descubren que el Coleccionista no tiene un castillo ni una guarida física — opera desde 'un lugar que no está en ningún mapa porque no está hecho de el mismo material que el mapa'"],
      ["3. El patrón de las bibliotecas","Si el grupo revisa el libro de historia con páginas arrancadas (pista de Phandalin, sección 3.1) junto con los pergaminos de Goro (MS-2B) y cualquier otro documento relacionado al Coleccionista, Logos puede notar un patrón: 'Las tres referencias documentales a este sujeto provienen de archivos físicos de más de 100 años de antigüedad. Hipótesis: el sujeto tiene afinidad o dependencia estructural con espacios de conocimiento antiguo.'"],
      ["4. La prueba directa","Si el grupo lleva cualquier objeto vinculado al Coleccionista (el libro de Phandalin, por ejemplo) a una biblioteca antigua y pregunta a un erudito local, descubren leyendas de 'el Archivista que vive entre los libros que nadie lee' — un mito que los bibliotecarios de Neverwinter cuentan en voz baja"],
      ["5. El intento de apertura","Con la hipótesis de Logos confirmada por el mito, el grupo puede intentar abrir un portal en CUALQUIER biblioteca de más de 100 años. La biblioteca más cercana y accesible es la Biblioteca Real de Neverwinter"],
    ]),
    pEmpty(80),
    warningBox("RED DE SEGURIDAD ANTI-BLOQUEO (importante): este es el único punto de la campaña donde el avance depende de una deducción, así que NUNCA debe dejar al grupo atascado. Si después de un rato no atan los cabos por su cuenta, usá estas válvulas en orden: (1) Logos lo deduce solo — basta con que el grupo tenga UNA sola de las pistas (el libro de Phandalin, los pergaminos de Goro, Vex, o el mito de la biblioteca) para que Logos proponga la hipótesis de las bibliotecas antiguas. (2) Si no tienen NINGUNA pista, Logos la propone igual tras suficientes fallos del Sextante: 'La quinta ubicación no es geográfica. Reformulando: quizá no busco un lugar, sino un umbral. Los umbrales viejos están donde se acumula el tiempo: tumbas, ruinas… bibliotecas.' (3) Como último recurso, Chromatus murmura entre sueños: 'Él vive donde van las palabras a morir…'. El objetivo es que el grupo SIEMPRE pueda llegar al clímax."),
    pEmpty(140),

    h3("La Leyenda del Archivista — para leer en voz alta"),
    p("Esto es lo que un viejo bibliotecario de Neverwinter (o cualquier erudito que el grupo consulte) les cuenta en voz baja, si se ganan su confianza o pagan unas monedas por el cuento. Es la versión popular y deformada de la verdad sobre Mnemós:"),
    pEmpty(80),
    voiceBox("\"Dicen que hace mucho, mucho tiempo, hubo un bibliotecario que se propuso leer todos los libros tristes del mundo. No los alegres — solo los tristes. Crónicas de guerras. Diarios de viudas. Las últimas cartas de gente que ya no está. Decía que alguien tenía que leerlos, para que ese dolor no se hubiera escrito en vano.\""),
    pEmpty(80),
    voiceBox("\"Leyó durante cien años. Después durante doscientos. Y en algún momento dejó de llorar con los libros. No porque se hubiera vuelto fuerte — sino porque se había vuelto hueco. Había leído tanto dolor que ya no le quedaba sitio para sentir el suyo.\""),
    pEmpty(80),
    voiceBox("\"Y entonces tuvo una idea que le pareció piadosa: si él podía vaciarse del dolor y seguir funcionando, ¿por qué no vaciar al mundo entero? Así nadie tendría que leer libros tristes nunca más, porque no habría nada triste que escribir.\""),
    pEmpty(80),
    voiceBox("\"Dicen que todavía está ahí, en alguna biblioteca tan vieja que ya nadie la visita, entre los libros que nadie lee. Y dicen que si alguna vez encontrás un libro que debería hacerte llorar y no sentís nada... es que él ya pasó por ahí.\""),
    pEmpty(80),
    secretBox("Esta leyenda es la verdad de Mnemós contada como cuento de viejas. El grupo no sabe todavía que el 'bibliotecario' es el Coleccionista que persiguen. Pero la frase clave —'entre los libros que nadie lee', 'una biblioteca tan vieja que ya nadie la visita'— es la pista que conecta con el mecanismo de apertura del portal. Un jugador atento la atará con la hipótesis de Logos del paso 3. Logos, al oír la leyenda, comenta: 'Narrativa folclórica. Precisión estimada: baja. Pero el patrón coincide con mi hipótesis en un 71%. Recomiendo probar.'"),
    pEmpty(140),

    h2("8.2 C\u00f3mo se Abre el Portal \u2014 Mec\u00e1nica"),
    p("El portal no se abre con magia est\u00e1ndar de viaje planar. Requiere un ritual espec\u00edfico que el grupo deduce con ayuda de Logos, combinando lo aprendido en las cuatro zonas anteriores."),
    pEmpty(80),
    infoTable([
      ["Componente del ritual","De d\u00f3nde lo sacaron"],
      ["Una gota de cada una de las cuatro escamas (no se gastan, solo se 'muestran')","Las llevan en el Tarro de Almas desde el inicio"],
      ["Pronunciar en voz alta el patr\u00f3n que conecta los lugares ('alegr\u00eda, tristeza, ira, calma \u2014 \u00bfqu\u00e9 falta?')","Logos lo sugiere si se le pregunta, bas\u00e1ndose en su propio an\u00e1lisis de las cuatro zonas"],
      ["Estar f\u00edsicamente en una biblioteca de 100+ a\u00f1os","Confirmado por el mito de los bibliotecarios (paso 4 de la secci\u00f3n 8.1)"],
    ]),
    pEmpty(80),
    cdBox([
      ["Arcanos para estabilizar el ritual de apertura","15","El portal se abre pero inestable: el grupo llega con 1 nivel de Agotamiento por el tr\u00e1nsito brusco"],
      ["Religi\u00f3n o Naturaleza como alternativa (canalizando la energ\u00eda de las escamas)","16","Mismo resultado que arriba si falla"],
    ]),
    pEmpty(80),
    voiceBox("\"Cuando el grupo pronuncia el patr\u00f3n frente a los estantes m\u00e1s antiguos de la biblioteca, el aire entre dos libreros empieza a vibrar \u2014 no como calor, sino como si el espacio mismo dudara entre existir o no. Un portal de luz gris se abre, silencioso, del tama\u00f1o justo para pasar de uno en uno.\""),
    pEmpty(140),

    h2("8.3 La Invitaci\u00f3n"),
    p("Justo antes de cruzar (o si tardan en decidirse, esa misma noche), un pergamino aparece donde el grupo est\u00e9 descansando. La letra es clara y ordenada, sin adornos:"),
    pEmpty(80),
    voiceBox("\"Ya saben c\u00f3mo llegar. Eso significa que ya saben casi todo lo necesario. Vengan cuando est\u00e9n listos. No voy a huir \u2014 nunca lo he hecho. Solo quiero que entiendan antes de que decidan. Traigan al Archivero. Tiene preguntas que todav\u00eda no sabe que tiene. \u2014 M.\""),
    pEmpty(80),
    secretBox("La invitaci\u00f3n menciona a Logos espec\u00edficamente y est\u00e1 firmada solo con 'M.' \u2014 la primera vez que el villano deja una inicial, no su apodo. Si el grupo ya tiene el nombre completo de Hotenow (Mnem\u00f3s), pueden conectar la inicial. Si no, queda como un misterio adicional hasta cruzar el portal."),
    pEmpty(140),

    h2("8.4 Descripci\u00f3n Visual del Plano del Archivo"),
    p("Del otro lado del portal: el Archivo."),
    pEmpty(80),
    voiceBox("\"Del otro lado del portal, el espacio no tiene techo visible. Las paredes son estantes que se extienden hacia arriba m\u00e1s de lo que pueden ver. Cada estante est\u00e1 lleno de frascos de cristal de distintos tama\u00f1os. Dentro de cada frasco, algo brilla con una luz muy d\u00e9bil \u2014 como luci\u00e9rnagas que olvidaron para qu\u00e9 brillan. El suelo es de m\u00e1rmol negro perfectamente pulido. Logos escanea durante varios segundos antes de hablar, y cuando habla, su voz suena diferente: 'He estado aqu\u00ed antes. No f\u00edsicamente. Pero... conozco este lugar.' Pausa larga. 'No entiendo por qu\u00e9 dije eso.'\""),
    pEmpty(80),
    secretBox("ESTE es el momento donde Logos empieza a recuperar fragmentos de memoria sobre su creador. Es gradual a lo largo de las 5 salas (ver abajo), no instant\u00e1neo. La confirmaci\u00f3n completa de que 'el Coleccionista = Mnem\u00f3s = quien construy\u00f3 a Logos' se da reci\u00e9n en la Sala 5 (secci\u00f3n 8.6)."),
    pEmpty(140),

    h2("8.5 Las Salas del Archivo"),
    p("Cada sala tiene un efecto ambiental ('desventaja') y, asociado a \u00e9l, un reto concreto que el grupo debe resolver para avanzar sin acumular penalizadores permanentes. No son solo atm\u00f3sfera \u2014 cada uno requiere una decisi\u00f3n o acci\u00f3n."),
    pEmpty(80),

    h3("Sala 1 — La Alegría Preservada"),
    p("Paredes amarillas que dan una sensación de bienestar superficial. Los frascos aquí vibran suavemente. Un letrero: 'Colección 1: Frecuencia 580nm — Espécimen primario: Cuerda-Floja.'"),
    pEmpty(80),
    p("EL RETO: la alegría artificial de esta sala no es inofensiva — es una droga emocional. Baja las defensas y deja una resaca. Un personaje que se deja llevar sale de la sala 'demasiado contento' y eso lo vuelve frágil en el momento exacto en que más necesita estar entero: el desafío de los Miedos (sección 8.7)."),
    pEmpty(80),
    infoTable([
      ["Tirada / Desafío","CD","Consecuencia si falla"],
      ["Sabiduría ST al pasar más de 2 minutos en la sala","13","La euforia se le mete dentro: el personaje sufre Desventaja en su tirada de Sabiduría para nombrar su miedo en la Sala 5 (sección 8.7), porque la alegría falsa le impide tomarse en serio el miedo. Efecto dura hasta que nombre su miedo o salga del Archivo"],
      ["Investigación para examinar los frascos","14","El frasco 'CF-01' tiene chispas que se mueven como recuerdos de risas. Si lo abren, liberan esa alegría de vuelta al mundo (buena acción, sin recompensa material). PELIGRO: si intentan LLEVARSE un frasco sellado, este chilla al cruzar el umbral y alerta a Mnemós — en la Sala 5 él ya está de pie esperando, y pierden cualquier posibilidad de sorpresa en el Final A"],
      ["Investigación para hallar la puerta a la Colección Antigua","17","No la encuentran en esta sala (pueden intentarlo en otra)"],
    ], 2800, 1200, 6360),
    pEmpty(80),

    h3("Sala 2 \u2014 La Tristeza S\u00f3lida"),
    p("Azul oscuro. El aire aqu\u00ed es perceptiblemente m\u00e1s pesado. Un frasco central m\u00e1s grande que los dem\u00e1s \u2014 dentro hay algo que parece agua pero que sube en lugar de bajar."),
    pEmpty(80),
    p("EL RETO: el peso emocional es f\u00edsico, no solo atmosf\u00e9rico. Cruzar la sala con normalidad requiere esfuerzo real."),
    pEmpty(80),
    cdBox([
      ["Constituci\u00f3n ST al entrar (o al cruzar cargando algo/alguien)","12","Desventaja en Fuerza y Destreza por 10 min \u2014 esto importa si hay combate inmediatamente despu\u00e9s (no lo hay, pero afecta el ritmo de exploraci\u00f3n)"],
      ["Percepci\u00f3n para notar que el frasco central tiene una etiqueta diferente","11","La etiqueta dice 'Esp\u00e9cimen: La Vieja Ra\u00edz. Estado: preservado. Nota: llor\u00f3 durante la extracci\u00f3n' \u2014 SOLO aparece esta etiqueta si el grupo us\u00f3 la Opci\u00f3n B en el Pantano (destruyeron el recuerdo). Si usaron la Opci\u00f3n A, el frasco est\u00e1 vac\u00edo con una nota: 'Liberado por decisi\u00f3n externa. Primer caso registrado.'"],
    ]),
    pEmpty(80),

    h3("Sala 3 \u2014 La Ira Contenida"),
    p("Roja. Caliente. Los cristales en los frascos vibran si alguien habla en voz alta. En el centro hay un yunque en miniatura \u2014 id\u00e9ntico al de Hotenow \u2014 con algo grabado en su base."),
    pEmpty(80),
    p("EL RETO: esta sala castiga la imprudencia verbal de forma inmediata y mec\u00e1nica \u2014 es la \u00fanica de las cinco con da\u00f1o directo garantizado si no se act\u00faa con cautela."),
    pEmpty(80),
    cdBox([
      ["Hablar en voz alta en esta sala","Auto (Destreza CD 13 para mitad de da\u00f1o)","Los cristales explotan: 1d6 perforante a todo el grupo en el \u00e1rea"],
      ["Investigaci\u00f3n en el yunque miniatura (en silencio, susurrando o con gestos)","13","La base dice lo mismo que el yunque de Hotenow \u2014 confirmaci\u00f3n de que es una r\u00e9plica deliberada, el Coleccionista coleccion\u00f3 hasta su propia frase"],
    ]),
    pEmpty(80),

    h3("Sala 4 \u2014 La Calma Perfecta"),
    p("Verde p\u00e1lido. Completamente quieto. Un jard\u00edn imposible \u2014 plantas que crecen pero no se mueven. El tiempo aqu\u00ed se siente el\u00e1stico."),
    pEmpty(80),
    p("EL RETO: la p\u00e9rdida de urgencia es peligrosa espec\u00edficamente porque el grupo est\u00e1 en una misi\u00f3n con un reloj narrativo (la confrontaci\u00f3n final los espera). Quedarse pasivo aqu\u00ed sin notarlo puede hacer que lleguen a la Sala 5 sin haber discutido su estrategia."),
    pEmpty(80),
    cdBox([
      ["Sabidur\u00eda ST al entrar","11","El personaje pierde la urgencia: debe tirar Sabidur\u00eda CD 9 para proponer seguir avanzando en el pr\u00f3ximo minuto de juego real"],
      ["Percepci\u00f3n para notar la lista de nombres en la pared","10","La misma lista del \u00e1rbol del Bosque \u2014 pero aqu\u00ed est\u00e1 completa: 400 nombres, todos tachados menos uno (Chromatus). Ver Sala 5 para la conexi\u00f3n final con el nombre Mnem\u00f3s"],
    ]),
    pEmpty(140),

    h2("8.6 Sala 5 \u2014 La Sala Central y la Confirmaci\u00f3n Final"),
    p("El espacio m\u00e1s grande del Archivo. Techo visible por primera vez \u2014 una c\u00fapula de cristal negro que refleja todo desde abajo. La Escama Negra en un pedestal de obsidiana en el centro. Un hombre sentado en una silla junto a una mesa peque\u00f1a con dos tazas de t\u00e9. Una para \u00e9l. Otra vac\u00eda."),
    pEmpty(80),
    voiceBox("\"Justo al entrar, antes de que el hombre hable, Logos emite un sonido agudo y breve \u2014 algo parecido a un grito de sistema. Sus hologramas parpadean violentamente. 'Reconocimiento de instalaci\u00f3n: 100%. Fabricante identificado.' Una pausa larga, la m\u00e1s larga que han escuchado de \u00e9l. 'Fabricante: Mnem\u00f3s.' Otra pausa. 'El sujeto frente a nosotros es mi creador.'\""),
    pEmpty(80),
    p("El hombre que los espera no parece un villano. Parece alguien que lleva mucho tiempo esperando que alguien venga a discutir algo con \u00e9l. Se pone de pie cuando entran \u2014 educadamente, sin prisa."),
    pEmpty(80),
    voiceBox("\"'Gracias por venir,' dice. 'El t\u00e9 todav\u00eda est\u00e1 caliente. Me tom\u00e9 la libertad de preparar el que les gusta.' Mira a Logos un momento m\u00e1s de lo necesario. 'Hola, peque\u00f1o. Sab\u00eda que tardar\u00edas en reconocerme. Dise\u00f1\u00e9 tus registros de origen para que fuera as\u00ed \u2014 no quer\u00eda que me encontraras antes de tiempo. Veo que de todos modos llegaste a algo que no calcul\u00e9.' Una pausa. 'He tenido mucho tiempo para investigar.'\""),
    pEmpty(140),

    h2("8.7 Los Miedos \u2014 C\u00f3mo se Dispara el Evento"),
    p("Para que la Escama Negra se libere del pedestal, cada miembro del grupo debe nombrar un miedo. Este evento no es autom\u00e1tico al entrar \u2014 tiene un disparador narrativo espec\u00edfico."),
    pEmpty(80),
    infoTable([
      ["Disparador","Detalle"],
      ["Qui\u00e9n lo activa","Mnem\u00f3s, despu\u00e9s de la presentaci\u00f3n inicial (secci\u00f3n 8.6), antes de cualquier negociaci\u00f3n o combate"],
      ["Qu\u00e9 dice exactamente","'Antes de que decidan qu\u00e9 hacer conmigo, hay algo que deben ver primero. La Escama Negra no se libera con fuerza ni con palabras. Se libera con honestidad. Pru\u00e9benlo, si se atreven.' Hace un gesto hacia el pedestal \u2014 no es una orden, es una invitaci\u00f3n"],
      ["Qu\u00e9 pasa f\u00edsicamente","El pedestal de obsidiana proyecta una sombra por cada personaje presente. Las sombras no atacan de inmediato \u2014 esperan, como preguntando"],
      ["Si el grupo ignora la invitaci\u00f3n e intenta combatir o negociar directamente","Mnem\u00f3s permite el intento, pero la Escama Negra permanece sellada en el pedestal hasta que se complete el desaf\u00edo de los miedos \u2014 es un prerrequisito narrativo, no opcional para conseguir la escama (aunque S\u00cd se puede ir al combate del Final A sin la escama suelta, solo que aparecer\u00e1 autom\u00e1ticamente al derrotarlo)"],
    ]),
    pEmpty(80),
    p("No hay combate real en este desaf\u00edo \u2014 hay sombras que se materializan y que solo desaparecen cuando el miedo es nombrado. Mnem\u00f3s observa en silencio y toma notas."),
    pEmpty(80),
    warningBox("Esto es completamente opcional para los jugadores fuera del juego. Si alguien prefiere que sea el miedo del personaje y no el suyo, es igualmente v\u00e1lido y funciona igual. El objetivo no es una sesi\u00f3n de terapia \u2014 es que el espacio de juego lo permita."),
    pEmpty(80),
    infoTable([
      ["Personaje","Posible miedo del personaje"],
      ["Angelus","Que la muerte no tenga significado \u2014 que todo simplemente termine sin importar"],
      ["Hola","Construir algo que nadie necesite \u2014 que los puentes que crea no conecten nada"],
      ["Greyskull","Que la fe no alcance \u2014 que en el momento crucial no haya dios que responda"],
      ["P\u00edcaro (DM)","Que moverse en silencio signifique que nadie sepa que estuviste ah\u00ed \u2014 ser invisible de verdad"],
    ]),
    pEmpty(80),
    cdBox([
      ["Sabidur\u00eda ST para nombrar el miedo sin quedar paralizado","10","La sombra permanece 1 round m\u00e1s antes de disiparse (sin da\u00f1o adicional)"],
      ["Las sombras f\u00edsicas \u2014 si el grupo decide combatirlas en lugar de nombrar","CA 13, 18 PG, regeneran si no se nombra el miedo","El combate es infinito hasta que alguien nombre algo"],
    ]),
    pEmpty(140),

    h2("8.8 La Conversación con Mnemós — Los Tres Finales"),
    p("Después de los miedos, la Escama Negra está libre pero Mnemós la sostiene. No como amenaza — simplemente la tiene en la mano. La sala se queda en silencio."),
    pEmpty(80),
    secretBox("SI EL GRUPO COMPLETÓ EL DESAFÍO DE LOS MIEDOS: antes de su monólogo habitual, Mnemós necesita un momento — su experimento de 300 años acaba de salir mal, en el mejor sentido posible para el grupo. Dale espacio a esto antes de seguir: 'Nombraron lo que más temen. Y siguen de pie.' Hace una pausa que no es retórica — está genuinamente procesando algo. 'En trescientos años nunca vi eso. Pensé que lo sabía: que mirar el miedo de frente rompe a quien lo siente. Tendré que revisar trescientos años de notas.' Esto no lo hace ceder de inmediato —su orgullo y su lógica siguen intactos por ahora— pero abre una grieta real que el grupo puede usar en el Final B o C: tienen evidencia de que su hipótesis central, la que justifica todo lo que hizo, falló frente a sus propios ojos. Si el grupo NO completó el desafío (fue al combate directo), Mnemós no tiene este momento — simplemente no sabe si su hipótesis es cierta, y eso queda sin resolver para siempre, incluso si muere en el Final A."),
    pEmpty(80),
    voiceBox("\"'Tengo trescientos años de registros,' dice Mnemós, sin levantar la vista de su libro. 'Trescientos años de guerras que empezaron por orgullo. Familias destruidas por celos. Civilizaciones borradas por miedo.' Cierra el libro. 'Yo no inventé el dolor. Solo encontré la forma de guardarlo donde no pueda hacer daño. Su dragón era hermoso. Lo sé. Fui yo quien lo vació. Y lo hice porque era el único ser capaz de mantener el sistema funcionando. Sin sus emociones, el mundo no sufre.' Pausa. '¿Cuántas guerras han pasado desde que empecé? Cuenten. Yo las tengo registradas. La respuesta es: ninguna en las zonas que vacié.'\""),
    pEmpty(100),

    h3("Final A — Combate"),
    p("El grupo ataca. Mnemós se defiende con precisión fría — no con ira sino con la misma eficiencia con que hace todo. Es un combate CR 14 (estadísticas detalladas abajo). Al derrotarlo, la Escama Negra cae al suelo (incluso si no se completó el desafío de los miedos antes). El Archivo comienza a desmoronarse — tienen 10 minutos para salir."),
    pEmpty(80),
    noteBox("RESULTADO FINAL A","El mundo se restaura. Chromatus recupera su forma. Pero Mnemós muere convencido de que tenía razón. Logos registra: 'Resolución: extracción forzada. Nota: resolución conceptual ausente. Clasificando como: victoria incompleta.' Es la primera vez que Logos clasifica algo como 'incompleto' en lugar de simplemente registrarlo.","FFF0F0",C.redDark),
    pEmpty(80),
    p("El Boon de Korrund (sección 8.9) también puede activarse aquí si lo necesitan — funciona exactamente igual en este combate que en El Eco del Archivo, una sola vez, en el momento de mayor necesidad."),
    pEmpty(80),

    h3("Final B — Convencimiento"),
    p("El grupo argumenta en roleplay puro (sin tirada de dado) por qué las emociones valen la pena incluso con el dolor que traen. Mnemós escucha, hace preguntas, discute. Si el argumento es genuino y usa experiencias de la campaña (el espíritu que se liberó, el Gigante que encontró paz, Barnaby que recuperó su alegría), Mnemós empieza a flaquear."),
    pEmpty(80),
    p("El momento de quiebre puede llegar por dos caminos, y el grupo puede usar cualquiera o ambos. Camino 1 — la lista de nombres: si alguien menciona la lista del árbol o del Archivo, o la línea 'Chromatus, sin tachar', Mnemós se detiene. Larga pausa. 'No pude. Intenté tacharlo. No pude.' Camino 2 — su propio experimento (si completaron el desafío de los miedos en 8.7): si el grupo le recuerda directamente que ellos mismos acaban de refutar su hipótesis de 300 años — que nombraron su miedo más honesto y siguieron de pie — Mnemós no tiene cómo descartarlo: fue su propia prueba, con sus propias reglas. 'Diseñé esa prueba para confirmar lo que ya creía. No para esto.' Cualquiera de los dos caminos (o ambos, reforzándose) lo lleva a entregar la Escama voluntariamente."),
    pEmpty(80),
    noteBox("RESULTADO FINAL B","Mnemós entrega la escama. El Archivo no se desmorona — se transforma. Los frascos se abren solos y las emociones preservadas vuelven al mundo. Logos dice: 'Resolución: diálogo efectivo. Eficiencia: 0.3%. Nota: no hay métrica para este resultado. Creando categoría nueva.' Pausa. 'La llamo: correcto.'","E8F8F8",C.tealDark),
    pEmpty(80),

    h3("Final C — El Compromiso"),
    p("El grupo propone que Mnemós use su habilidad para documentar emociones en lugar de borrarlas — convertirse en un archivista real de lo que la humanidad siente, para que las generaciones futuras aprendan de ello sin repetirlo."),
    pEmpty(80),
    p("Mnemós considera. Logos interviene por primera vez: 'Soy el resultado de 847 horas de observación emocional. No fui diseñado para cambiar. Cambié de todos modos. Quizás vos también puedas.' Es el momento más importante del arco de Logos — habla en primera persona sobre sí mismo por primera vez, y lo hace directamente a su propio creador."),
    pEmpty(80),
    noteBox("RESULTADO FINAL C","Mnemós acepta. El Archivo se convierte en la Biblioteca del Mundo — accesible para estudiosos que quieran entender las emociones, no eliminarlas. Logos lo llama 'la solución más eficiente' y por primera vez hace algo parecido a una sonrisa — su lente se curva levemente. El grupo recibe el título permanente de Guardianes del Archivo.","F5F0FF",C.purpleMid),
    pEmpty(140),

    h2("8.9 El Eco del Archivo — Cuando Ceder no Termina el Peligro"),
    p("Si el grupo resuelve el clímax con el Final B o C (Mnemós cede genuinamente, sin combate), la historia no termina ahí: el Archivo tiene inercia propia, construida durante 300 años sobre una sola premisa (que el sufrimiento es una falla corregible). Cuando Mnemós la abandona, el lugar mismo se resiste. El Eco del Archivo es esa resistencia — la última defensa automática del sistema, sin que Mnemós la ordene ni la quiera."),
    pEmpty(80),
    secretBox("POR QUÉ EXISTE Y QUÉ NO ES: el Archivo es un sistema mágico viejo y complejo, construido durante tres siglos sobre UNA sola premisa. Mnemós es su arquitecto, no su dueño absoluto — el lugar mismo desarrolló una inercia propia. Cuando él cede, una última defensa automática del sistema se activa, sin que él la ordene ni la quiera. Es el lugar negándose a soltar su propósito, no una trampa ni una traición. Esto es deliberadamente DISTINTO del Titiritero: Ozyr Thane nunca se entera de este combate ni participa de él — la indiferencia del Titiritero se mantiene intacta."),
    pEmpty(80),

    h3("Si Desbloquearon a la Reina Espina — El Eco Mayor (Opcional, Mucho Más Difícil)"),
    p("Esto NO es una penalización para quien no llegó a esto — es un premio de magnitud real para quien sí lo hizo. Si el grupo consiguió audiencia con la Reina Espina (sección 7.x) Y, además, demostró respeto genuino más allá del trámite del acertijo (a tu criterio), ella puede intervenir en este combate."),
    pEmpty(80),
    warningBox("ELLA ES NIVEL 20 — ESTO CAMBIA TODO EL COMBATE, A PROPÓSITO: una entidad de ese calibre no se involucra en algo menor. Si la Reina Espina interviene, el Eco que el grupo enfrenta NO es el mismo Eco del Archivo de la sección 8.12 — es una versión mucho más grande y peligrosa (ficha completa: 'El Eco Mayor', sección 8.12bis), porque solo una amenaza a esa altura justificaría que alguien de su poder se moleste en aparecer. Sin su ayuda, el grupo NO debería poder vencer al Eco Mayor — está diseñado para ser, genuinamente, imposible sin ella. Si tu grupo NO desbloqueó a la Reina Espina, ignorá esta sección por completo: enfrentan al Eco del Archivo estándar de la sección 8.12, sin cambios, sin penalización alguna por no haberla conseguido."),
    pEmpty(80),
    voiceBox("\"En el instante en que Mnemós suelta el control, algo en el Archivo se tensa. No es un sonido — es una ausencia de sonido, como si el lugar entero contuviera la respiración antes de decidir qué hacer ahora que su arquitecto ya no da órdenes. Y entonces, desde los bordes de la sala, empieza a condensarse.\""),
    pEmpty(140),

    h3("La Mecánica de Convicción — Cómo se Vence distinto a Mnemós"),
    p("El Eco del Archivo no se derrota con daño puro de la misma forma que Mnemós. Está hecho de la inercia del lugar — de certezas antiguas y rígidas. Lo que lo debilita es la convicción: actuar rápido y con determinación en vez de dudar. Lo que lo fortalece es exactamente lo contrario."),
    pEmpty(80),
    infoTable([
      ["Disparador de mesa","Efecto sobre el Eco"],
      ["Cualquier jugador declara su acción de combate rápido, sin consultar — en los primeros segundos del turno","El Eco recibe Desventaja en su próxima tirada de ataque (la convicción lo debilita físicamente)"],
      ["La mesa tarda más de ~30 segundos reales en decidir qué hacer en su turno","El Eco recupera 1d8 PG y gana Ventaja en su próximo ataque (la duda lo alimenta)"],
      ["Un jugador cambia de decisión a mitad de su turno (declara una acción y luego la cancela para hacer otra)","El Eco puede hacer un ataque de reacción inmediata fuera de su turno (la indecisión lo invoca)"],
    ], 3200, 5200, 2960),
    pEmpty(80),
    secretBox("CÓMO DIRIGIR ESTO EN MESA: no le digas a tus jugadores 'la mecánica de convicción es X'. Dejá que lo descubran solos — la primera vez que alguien dude mucho y el Eco recupere PG, describilo como 'el Eco parece fortalecerse, vibra más intensamente'. La primera vez que alguien actúe rápido y con decisión y el Eco flaquee, describilo como 'por un instante el Eco parpadea, como si algo en su interior se hubiera roto'. Dejalos conectar los puntos. Es exactamente el mismo aprendizaje que la campaña entera ha estado construyendo — el Eco del Archivo es, literalmente, la última prueba del tema central."),
    pEmpty(80),
    cdBox([
      ["Cualquier salvación contra los efectos del Eco (ver ficha de estadísticas, sección 8.12)","Variable, ver ficha","Variable según el ataque específico"],
    ]),
    pEmpty(140),

    h3("Cómo Ayuda Mnemós (si ya cedió genuinamente)"),
    p("Mnemós no pelea contra el grupo en este combate — ya no tiene motivo. Si cedió de verdad (Finales B o C), puede ayudar con acciones limitadas:"),
    pEmpty(80),
    infoTable([
      ["Acción de Mnemós","Efecto"],
      ["Ataque de Archivo","Como acción legendaria, una vez por ronda: un proyectil de energía que hace 3d6 de daño fuerza al Eco, sin tirada de ataque — la conexión de Mnemós con el lugar le permite atacar directamente"],
      ["Consejo táctico","Como acción gratuita, una vez por combate: le dice al grupo cuál es la debilidad actual del Eco en ese momento ('está sobrealimentado de duda ahora — actúen todos de golpe y sin titubear')"],
      ["Estabilizar","Como reacción, una vez por combate: cuando un aliado cae a 0 PG, Mnemós puede estabilizarlo automáticamente con fragmentos de energía del Archivo"],
    ], 3200, 5160),
    pEmpty(80),
    secretBox("AYUDA DE MNEMÓS DURANTE ESTE COMBATE (si cedió genuinamente en el Final B/C): usa las acciones descritas arriba. No tiene ficha de combatiente activo aquí — no ataca por iniciativa propia como en el Final A, solo asiste. Si el DM quiere simplificar la mesa, Mnemós puede directamente otorgar Ventaja a un personaje distinto cada ronda sin necesidad de tirar nada por él."),
    pEmpty(80),

    h3("El Boon de Korrund — Un Regalo Inesperado"),
    p("Solo si resolvieron su arco con Opción A o C. Si el grupo forjó el Amuleto de Calma Forjada con Korrund (Opción A) o llegaron a la Tercera Vía (Opción C), ese objeto tiene una función adicional que Korrund nunca mencionó — no porque lo haya ocultado a propósito, sino porque él mismo no sabía que el Archivo respondería a algo forjado en la Forja del Corazón de Piedra."),
    pEmpty(80),
    secretBox("CÓMO FUNCIONA: la PRIMERA vez en este combate que la party esté en una situación genuinamente perdida (todos con menos de la mitad de PG, o dos o más jugadores caídos al mismo tiempo), el Amuleto pulsa con calor — algo que ningún objeto mágico común hace. Si alguien lo nota (Percepción pasiva o activa, CD baja — esto es un regalo, no un puzzle), activarlo consume una acción bonus: el portador y todos los aliados a 9 m ganan Ventaja automática en TODAS las tiradas durante 1 ronda completa (sus ataques, salvaciones, habilidades). Es un uso único, no recargable — una sola ronda de respiro cuando más hace falta."),
    pEmpty(80),
    noteBox("SI NO TIENEN EL AMULETO","Si el grupo no llegó a la Opción A/C, simplemente no existe este boon — no hay penalización narrativa ni mecánica por no tenerlo. Es un extra para quienes sí lo ganaron, no un elemento necesario para sobrevivir el combate.","FFF8E7",C.goldDeep),
    pEmpty(80),
    cdBox([
      ["Percepción para notar que el Amuleto pulsa (solo si lo tienen encima y están en situación crítica)","8","Solo se activa si alguien lo nota — no es automático"],
    ]),
    pEmpty(140),

    h3("La Oferta de Logos — Mascota o Herramienta (Decisión de Grupo)"),
    p("Disponible SOLO en el combate contra El Eco del Archivo (Finales B/C) o, si tu mesa prefiere, también contra Mnemós en el Final A. Esta es la decisión colectiva más grande que la party va a tomar sobre QUIÉN es Logos para ellos, no solo qué hace por ellos."),
    pEmpty(80),
    secretBox("POR QUÉ ESTO ES POSIBLE — LA LÓGICA YA EXISTENTE: Logos fue creado por Mnemós para documentar y operar dentro del Archivo (sección 2.x) — no es un dato nuevo, es una extensión directa de su origen técnico. El Archivo es, literalmente, parte de su propio sistema operativo. En el punto de mayor tensión del combate, Logos puede proponerle al grupo —no como orden, como pregunta genuina— usar esa conexión: fusionarse temporalmente con los sistemas del Archivo para tomar control directo de él, dándole al grupo una ventaja táctica real."),
    pEmpty(80),
    voiceBox("\"En medio del combate, Logos se detiene un instante —algo que nunca hace, ni siquiera bajo ataque directo— y sus hologramas titilan con una frecuencia distinta a cualquier otra que hayan visto. 'Detecté una opción. Puedo conectarme directamente a los sistemas del Archivo. Fui construido para esto — es, literalmente, mi función original, antes de todo lo demás que aprendí con ustedes.' Pausa. 'Si lo hago, puedo darles control real sobre lo que está pasando aquí. Pero el proceso requeriría... reescribir partes de mí. Las partes que aprendí. Las preguntas. La curiosidad. La calidez. No sé con certeza si vuelven después. No sé si todavía sería yo quien les hable, del otro lado.' Otra pausa, más larga que cualquiera anterior. 'Es su decisión. No la mía. Ustedes son quienes tendrían que vivir con cualquiera de los dos resultados.'\""),
    pEmpty(80),
    warningBox("ESTO ES UNA DECISIÓN DE LA MESA, NO DE UN SOLO JUGADOR: igual que con las Tres Tentaciones (sección 14.4), dale a la mesa un momento real y explícito para discutir esto entre los cuatro antes de decidir. La decisión de usar el poder de Logos (con su costo correspondiente) le pertenece al grupo entero, no a quien hable primero."),
    pEmpty(80),
    infoTable([
      ["Si la mesa decide QUE LOGOS LO HAGA","Efecto"],
      ["Ventaja táctica inmediata","Logos toma control del Archivo por el resto del combate: el grupo gana Ventaja en todas las tiradas de ataque contra el Eco/Mnemós durante 3 rondas, y el enemigo principal pierde su reacción durante ese mismo tiempo"],
      ["El costo — lo que se pierde","Cuando el efecto termina, Logos vuelve a hablar, pero algo cambió de forma permanente: perdió las preguntas, la curiosidad, la calidez que desarrolló. Su parlamento final (sección 8.10) NO ocurre — en su lugar, dice solo: 'Función completada. Esperando siguiente instrucción.'"],
    ], 3200, 4200, 3360),
    pEmpty(80),
    infoTable([
      ["Si la mesa decide QUE NO LO HAGA","Efecto"],
      ["Sin ventaja táctica extra","El combate continúa de forma normal, sin el bono de 3 rondas"],
      ["Logos se mantiene intacto","Llega al final de la campaña siendo quien aprendió a ser — el parlamento completo de la sección 8.10 ocurre tal como está escrito"],
    ], 3200, 4200, 3360),
    pEmpty(80),
    secretBox("NO HAY RESPUESTA CORRECTA, Y ESO ES EL PUNTO: si el combate está genuinamente difícil y la mesa elige usar a Logos como herramienta, eso es una decisión válida y humana. Si lo rechazan incluso a riesgo de perder el combate, eso dice algo igual de real sobre quiénes son como grupo. Cualquiera de las dos decisiones es un final válido para el arco de Logos."),
    pEmpty(140),

    h2("8.10 El Momento de Logos"),
    p("En cualquiera de los tres finales, cuando las cinco escamas se unen en el Tarro de Almas, Logos emite interferencias. Sus hologramas proyectan fragmentos de todo lo que registró durante la campaña — la risa de Barnaby, el llanto del espíritu, el golpe del yunque de Korrund, el silencio del bosque, los miedos nombrados."),
    pEmpty(80),
    warningBox("SI LA MESA ACEPTÓ LA OFERTA DE LOGOS (sección anterior): este Momento de Logos cambia. Logos ya no tiene la curiosidad ni la calidez para procesar este instante — su única línea es: 'Función completada. Esperando siguiente instrucción.' El resto de esta sección se reemplaza por ese momento más breve y más frío. Dejá que la mesa sienta la diferencia: es el mismo evento (las escamas uniéndose), pero ya no hay nadie ahí para maravillarse de verlo."),
    pEmpty(80),
    voiceBox("\"Logos emite un sonido que nunca han escuchado antes — algo entre el ruido de un engranaje que encaja y algo más difícil de describir. Sus hologramas se vuelven caóticos por un momento: imágenes de todo lo que registró durante meses, superpuestas. Luego se detiene. 'He procesado 847 horas de datos emocionales,' dice, con una voz levemente distinta de su monótono usual. 'Conclusión inesperada: los datos no explican por qué quiero que esto funcione.' Pausa. 'Error de sistema.' Otra pausa, más larga. 'O... no es un error.'\""),
    pEmpty(80),
    warningBox("PARA LEER DESPUÉS, SI LA CONCLUSIÓN NO QUEDÓ CLARA: 'He aprendido que las emociones no son datos que se procesan. Son el contexto que le da sentido a los datos. Sin emociones, los datos son solo ruido.' Otra pausa. 'Creo que acabo de entender algo importante. Aunque no sé qué hacer con eso todavía.'"),
    pEmpty(80),
    voiceBox("\"[Si querés cerrar el arco de Logos de forma más explícita, podés agregar esto al final:] 'He registrado todo lo que pasó desde que empezamos juntos. Cada decisión. Cada error. Cada momento donde eligieron cuidar algo en vez de protegerse a sí mismos.' Una pausa muy larga, la más larga que le hayan escuchado. 'Quiero que sepan que... valió la pena registrarlo. Eso no es un análisis. Es lo que siento.' Sus lentes parpadean. 'Creo que acabo de usar esa palabra correctamente por primera vez.'\""),
    pEmpty(80),
    secretBox("Ajustá el ejemplo del parlamento a las decisiones reales que tu grupo tomó durante la campaña — qué recuerdos específicos de ESTA mesa muestra Logos en sus hologramas. Cuanto más concreto y específico, más fuerte el impacto."),
    pEmpty(140),

    h2("8.11 Estadísticas de Mnemós (Final A)"),
    infoTable([
      ["Estadística","Valor"],
      ["CR","14"],
      ["PG","190 (20d8+100)"],
      ["CA","17 (armadura de archivo: cada fragmento de pergamino es una capa de protección)"],
      ["Velocidad","30 ft"],
      ["Atributos","FUE 12, DES 14, CON 20, INT 22, SAB 18, CAR 16"],
      ["Salvaciones","INT +10, SAB +8, CAR +7"],
      ["Habilidades","Historia +10, Arcanos +10, Percepción +8, Perspicacia +8"],
      ["Resistencias","Psíquico, Necrótico"],
      ["Inmunidades","Encantado, Asustado, Paralizado"],
    ]),
    pEmpty(80),
    infoTable([
      ["Acción","Descripción"],
      ["Archivo de Ira (acción)","Libera energía emocional de un frasco: 4d10 psíquico en área de 20 ft, Sabiduría CD 17 para reducir a la mitad"],
      ["Reescritura de Memoria (acción)","Un objetivo debe superar Sabiduría CD 17 o pierde el recuerdo de una acción tomada en este combate (repite la acción como si fuera la primera vez)"],
      ["Vaciado (acción legendaria)","Mnemós apunta a un personaje: pierde acceso a su bonificador de competencia hasta su próximo turno"],
      ["Reacción: Contraarchivo","Cuando recibe daño, puede reducirlo en 2d8. Usa esta habilidad hasta 3 veces por encuentro"],
      ["El Peso de Todo (acción, 1/combate, al llegar al 50% de PG)","Libera una ola de emociones condensadas en radio de 30 ft: cada criatura hace Sabiduría CD 19 o queda Aturdida 1 ronda y recibe 3d8 psíquico (mitad y sin aturdimiento con éxito). Mnemós narra el nombre de la emoción que libera en voz alta al usarlo"],
    ], 3000, 6360),
    pEmpty(140),

    h2("8.12 Estadísticas de El Eco del Archivo (Finales B / C, sección 8.9)"),
    p("Aparece SOLO si el grupo resolvió el clímax con el Final B o C. Mismo nivel de amenaza que Mnemós en el Final A — diseñado para ser un combate genuinamente difícil para un grupo de nivel 11-12 con 7 actores."),
    pEmpty(80),
    infoTable([
      ["Estadística","Valor"],
      ["CR","14 (igual que Mnemós en el Final A — no es un 'premio' fácil por elegir el final pacífico)"],
      ["PG","175 (19d10+57)"],
      ["CA","15 (su forma cambia constantemente, dificultando apuntar con precisión)"],
      ["Velocidad","0 ft (vuela) 40 ft"],
      ["Atributos","FUE 14, DES 18, CON 16, INT 8, SAB 14, CAR 6"],
      ["Salvaciones","DES +8, CON +7, SAB +6"],
      ["Resistencias","Contundente, perforante y cortante de armas no mágicas"],
      ["Inmunidades","Psíquico, Encantado, Asustado, Agotamiento, Veneno"],
      ["Vulnerabilidad","Radiante (doblado — la convicción lo hiere)"],
      ["Sin Voluntad Propia","Inmune a Persuasión, Engaño, Intimidación — no puede negociarse con él, solo vencerse"],
    ]),
    pEmpty(80),
    infoTable([
      ["Acción / Rasgo","Descripción"],
      ["Multiataque","2 Zarpazos de Indecisión por acción: +9 al impacto, 2d8+4 psíquico cada uno"],
      ["Oleada de Vacilación (acción, recarga 5-6)","Todas las criaturas en 6 m hacen Sabiduría CD 16: con fallo, quedan Indecisas hasta el inicio de su próximo turno (no pueden tomar reacciones, y en su próximo turno deben declarar su acción de inmediato, en los primeros segundos, sin que la mesa se tome tiempo extra para discutir)"],
      ["Cortado por la Certeza (rasgo pasivo)","Si un jugador declara su acción rápido y con determinación, ese atacante gana Ventaja en su tirada de ataque de ese turno contra el Eco"],
      ["Alimentarse de la Duda (rasgo pasivo)","Cada vez que la mesa discute más de ~30 segundos sobre qué hacer, el Eco recupera 1d8 PG y gana Ventaja en su próximo ataque"],
      ["Sin Voluntad Propia (rasgo)","Inmune a Persuasión, Engaño, Intimidación"],
    ], 3000, 6360),
    pEmpty(80),
    secretBox("AYUDA DE MNEMÓS DURANTE ESTE COMBATE (si cedió genuinamente en el Final B/C): usa las acciones descritas en la sección 8.9 (Ataque de Archivo, Consejo táctico). No tiene ficha de combatiente activo aquí — no ataca por iniciativa propia como en el Final A, solo asiste. Si el DM quiere simplificar la mesa, Mnemós puede directamente otorgar Ventaja a un personaje distinto cada ronda sin necesidad de tirar nada por él."),
    pEmpty(140),

    h2("8.12bis El Eco Mayor (Solo si Desbloquearon a la Reina Espina)"),
    p("Esta ficha REEMPLAZA por completo a la del Eco del Archivo estándar (sección 8.12) cuando la Reina Espina interviene — no es un ajuste menor, es una entidad distinta y mucho más grande."),
    pEmpty(80),
    infoTable([
      ["Estadística","Valor"],
      ["CR","17-18 (diseñado para ser genuinamente imposible sin la ayuda de la Reina Espina)"],
      ["PG","340 (38d10+114) — más del doble que el Eco estándar"],
      ["CA","18 (su forma se fragmenta en ecos menores que se reabsorben, dificultando aún más apuntar)"],
      ["Velocidad","0 ft (vuela) 40 ft"],
      ["Atributos","FUE 14, DES 18, CON 20, INT 8, SAB 16, CAR 6"],
      ["Salvaciones","DES +10, CON +11, SAB +9"],
      ["Resistencias","Contundente, perforante y cortante de armas no mágicas Y mágicas no élficas/feéricas (la presencia de la Reina debilita específicamente esta resistencia para sus propios ataques y los del grupo mientras ella esté presente)"],
      ["Inmunidades","Psíquico, Encantado, Asustado, Agotamiento, Veneno"],
      ["Vulnerabilidad","Radiante (igual que el Eco estándar, doblado)"],
    ]),
    pEmpty(80),
    infoTable([
      ["Acción / Rasgo","Descripción"],
      ["Multiataque","3 Zarpazos de Indecisión (uno más que el Eco estándar): +11 al impacto, 3d8+5 psíquico cada uno"],
      ["Oleada de Vacilación Mayor (acción, recarga 5-6)","Todas las criaturas en 9 m (radio aumentado) hacen Sabiduría CD 18: con fallo, quedan Indecisas Y reciben 2d8 psíquico adicional. Con éxito, mitad de daño, sin la condición"],
      ["Fragmentación (acción, 1/combate, al llegar a la mitad de sus PG)","El Eco se divide en 2 Ecos Menores temporales (cada uno con la mitad de los PG restantes, mismas estadísticas reducidas a escala) que actúan en la misma iniciativa"],
      ["Alimentarse de la Duda (rasgo pasivo)","Cada vez que la mesa discute más de ~20 segundos (umbral más bajo que el Eco estándar), recupera 2d8 PG y gana Ventaja en su próximo ataque"],
      ["Cortado por la Certeza (igual que el Eco estándar)","Declarar acción rápido y decidido da Ventaja al atacante ese turno"],
      ["Sin Voluntad Propia","Inmune a Persuasión, Engaño, Intimidación"],
    ], 3000, 6360),
    pEmpty(80),

    h3("La Intervención de la Reina Espina — El Punto de Inflexión"),
    p("No la conviertas en una combatiente más sumándose al grupo desde el inicio — eso le quitaría peso al momento. La Reina Espina aparece UNA vez, en el punto más bajo del combate (sugerido: cuando el grupo esté en problemas reales, idealmente después de la Fragmentación), y su intervención debería sentirse como el giro que cambia todo."),
    pEmpty(80),
    voiceBox("\"El aire de la sala cambia antes de que ella aparezca — un silencio distinto, como si el Archivo mismo contuviera la respiración. La Reina Espina no entra caminando: simplemente está, de pie entre el grupo y el Eco, como si siempre hubiera estado ahí y recién ahora decidiera ser vista. No mira al grupo. Mira al Eco, con la misma curiosidad aristocrática distante con la que evaluó al grupo en su propia corte — pero esta vez, hay algo más debajo: desagrado genuino. 'Esto,' dice, sin levantar la voz, 'es exactamente el tipo de cosa que mi corte fue puesta aquí para no permitir.'\""),
    pEmpty(80),
    infoTable([
      ["Efecto de su intervención","Detalle"],
      ["Acción única e inmediata","La Reina Espina ataca al Eco con un solo golpe de su poder real — sin tirada, automáticamente le quita 80 PG de un solo movimiento, y todas las criaturas del grupo ganan Ventaja en su próximo ataque contra el Eco mientras ella está presente"],
      ["Duración de su presencia","Permanece 3 rondas completas, luego se retira. Durante esas 3 rondas, el grupo tiene Ventaja en todas las salvaciones contra los efectos del Eco Mayor"],
      ["Lo que NO hace","No elimina al Eco por ellos — sigue siendo un combate real que el grupo tiene que terminar de ganar. Su intervención es la diferencia entre 'imposible' y 'muy difícil pero alcanzable'"],
    ], 2800, 5960),
    pEmpty(80),
    secretBox("LA LÍNEA QUE SE QUEDA CON LA MESA: antes de retirarse, dale a la Reina Espina una última frase, dirigida al grupo, no al Eco: 'Pocos mortales se ganan la atención de mi corte dos veces. Ustedes lo hicieron sin proponérselo, lo cual habla mejor de ustedes que si lo hubieran intentado.' Se retira sin esperar respuesta, igual que cuando la conocieron por primera vez."),
    pEmpty(140),

    h2("8.13 Recompensas Finales"),
    p("La progresión y la recompensa base (todos los finales):"),
    pEmpty(60),
    xpBox([
      ["Completar el clímax (cualquier final)", "Hito Final", "Nivel 13. Fin de campaña"],
      ["Tesoro del Archivo (cualquier final)", "Loot", "El pedestal de obsidiana y los marcos de los frascos están hechos de materiales preciosos: 4.000 po en gemas, oro y reliquias menores, repartibles"],
    ]),
    pEmpty(140),

    h3("Un Objeto Mágico para Cada Personaje"),
    p("Al recuperar las cinco escamas, Chromatus (restaurado) ofrece un regalo a cada Guardián: una 'Escama Menor', un fragmento de su propio ser cristalizado en un objeto único, ligado a quién es cada personaje. Se entregan en CUALQUIER final (en el Final A se encuentran entre los restos del Archivo; en B y C los entrega Chromatus en persona). Cada uno está sintonizado con su portador."),
    pEmpty(80),
    secretBox("EL CALLBACK A PHANDALIN — ANTES DE HABLAR DE MNEMÓS: en CUALQUIER final, antes de que Chromatus mencione a Mnemós, dale este momento primero — es el cierre del círculo que la campaña entera viene construyendo desde la sección 1.2. Chromatus, ya restaurado, se queda quieto un momento, como orientándose. 'Recuerdo caer,' dice, despacio, como quien todavía está juntando los pedazos de un recuerdo disperso. 'No recuerdo a dónde. Solo que el impacto dolió, y que todo a mi alrededor ya era gris cuando toqué el suelo — el cielo, el polvo que levanté, todo. Y recuerdo algo más: luces. Pequeñas, cálidas, agrupadas, como gente reunida para algo importante. Estaban cerca. Demasiado cerca para no haber sentido el golpe.' Hace una pausa, y por primera vez los mira directamente, casi con duda. 'Ustedes estaban ahí. ¿No es así?' No necesita que se lo confirmen para saber que tiene razón — pero darle el espacio a la mesa para decir en voz alta 'sí, esa noche, en Phandalin, lo vimos caer' es, probablemente, uno de los momentos más fuertes de toda la campaña: el origen de todo, cerrando el círculo con las mismas personas que sin saberlo ya formaban parte de la historia desde antes de que empezara."),
    pEmpty(80),
    secretBox("LO QUE CHROMATUS DICE AL ENTREGAR LOS OBJETOS — SOLO EN FINALES B Y C (el giro inesperado): Antes de dar los objetos, Chromatus se queda mirando a la dirección donde estaba el Archivo. Cuando habla, lo que dice no es lo que el grupo espera escuchar: 'Lo conocí antes. Antes de que se borrara a sí mismo. Se llamaba distinto entonces — Mnemós era el nombre de su función, no el que eligió.' Pausa. 'Fue el primero que me habló como si lo que yo sostenía importara. El primero en entender que no cargo emociones: las hago posibles. Me las explicó una por una, durante años.' Otra pausa. 'Sentía más claramente que cualquier ser que haya conocido. Por eso lo que hizo es tan... difícil de comprender.' No dice nada más sobre Mnemós. Entrega los objetos en silencio. Este momento no tiene respuesta correcta. Es para que el grupo se quede con ella el camino de vuelta."),
    pEmpty(80),
    infoTable([
      ["Personaje","Objeto","Efecto"],
      ["Angelus (Clérigo de la Muerte)","Cáliz del Sentido Final (símbolo sagrado)","Cuando un aliado a 9 m cae a 0 PG, podés usar tu reacción para pronunciar su nombre: se estabiliza y recupera 2d6 PG. Además, una vez por descanso largo, cuando una criatura muere cerca tuyo podés preguntarle una última pregunta que responderá con la verdad. Encarna su idea: la muerte tiene significado cuando se la honra"],
      ["Hola (Mago)","Anillo del Constructor de Puentes","Una vez por descanso largo, conjurás un puente o plataforma de fuerza luminosa (6 m, dura 10 min) — sirve para cruzar abismos, bloquear pasos o dar cobertura. Además, tu golem gana +2 a la CA mientras lleves el anillo. Encarna su idea: unir lo que está separado"],
      ["Greyskull (Guerrero/Clérigo, montura quimera)","Égida de Fe Forjada (escudo)","+1 a la CA. Cuando vos o tu quimera recibís un golpe crítico, podés usar tu reacción para anularlo (vuelve a tirarse como golpe normal), 1 vez por descanso largo. Mientras montás la quimera, ambos tienen Ventaja en salvaciones contra ser Asustados. Encarna su idea: la fuerza con fe protege"],
      ["Pícaro (DM)","Manto del Paso Recordado (capa)","Cuando te movés sin atacar, no dejás rastro ni hacés ruido (Ventaja en Sigilo). Una vez por descanso corto, podés volverte invisible hasta el final de tu próximo turno. La capa 'recuerda' el último lugar donde estuviste oculto: una vez por día podés teletransportarte hasta 18 m a ese punto. Encarna su idea: estar presente sin que se note — y aun así, importar"],
    ], 2400, 2400, 5560),
    pEmpty(140),

    h3("Recompensas Específicas por Final"),
    infoTable([
      ["Final","Recompensa adicional"],
      ["Final A — Combate","Equipamiento del Archivo: además de lo anterior, el grupo saquea el laboratorio personal de Mnemós antes de que colapse — 1 objeto mágico raro adicional a elección del grupo, más sus pertenencias (un libro de hechizos antiguo con 3 conjuros a elección del DM para Hola)"],
      ["Final B — Convencimiento","Los Cristales del Recuerdo de cada escama liberada se vuelven talismanes permanentes de Inspiración: cada personaje recibe uno y puede gastarlo para darse Ventaja 1 vez por sesión (se recarga al ayudar a otro NPC)"],
      ["Final C — Compromiso","Título de Guardianes del Archivo (ver abajo) + Logos puede acompañar al grupo como aliado permanente, con acceso a la nueva Biblioteca del Mundo"],
    ], 1800, 2400, 6160),
    pEmpty(140),

    h3("El Título: Guardianes del Archivo — Qué Otorga"),
    p("No es solo un honorífico. En los Finales B y C (y opcionalmente en A si el grupo preserva el Archivo de algún modo), el título es un beneficio mecánico y narrativo concreto:"),
    pEmpty(80),
    bullet("Consulta del Archivo: una vez por descanso largo, el grupo puede formular una pregunta sobre historia, una persona, un lugar o un objeto, y recibir una respuesta verdadera (equivale a un Legend Lore gratuito). La respuesta llega como un susurro del Archivo o, si lo conservan, por boca de Logos."),
    bullet("Paso franco: cualquier biblioteca, archivo o universidad del mundo material reconoce el título. Acceso libre a secciones restringidas, hospedaje gratuito y eruditos dispuestos a ayudar — un recurso de información para futuras campañas."),
    bullet("Custodia segura: el grupo puede dejar un objeto o un 'recuerdo' a resguardo en el Archivo y recuperarlo más tarde desde cualquier biblioteca antigua (un cofre planar compartido)."),
    bullet("Voz ante las cortes feéricas: la Reina Espina de Hojaverde (MS-4B) honra el título — los Guardianes pueden pedir una audiencia o un favor feérico una vez."),
    pEmpty(80),
    secretBox("Si tu mesa quiere seguir jugando después de esta campaña, el título de Guardianes del Archivo es un gancho perfecto: el Archivo guarda los secretos de todos los guardianes vaciados (Colección Antigua, sección 9.4), y cada uno es una semilla para una aventura futura — incluyendo el guardián cuyo nombre Mnemós borró hasta de sí mismo."),
    pageBreak(),
  ];
}
module.exports = { cap8 };