const { p, pEmpty, h1, h2, h3, bullet, numBullet, infoTable, noteBox, secretBox, loreBox, voiceBox, warningBox, cdBox, xpBox, pageBreak, npcBlock, C } = require('./helpers');

function cap9() {
  return [
    h1("9. Misiones Secundarias Globales"),
    p("Estas misiones no est\u00e1n ligadas a una zona espec\u00edfica \u2014 se desarrollan a lo largo de la campa\u00f1a y a\u00f1aden capas al mundo y al misterio del Coleccionista."),
    pEmpty(140),

    h2("9.1 El Taller del Recuerdo (Neverwinter) — Detalle Completo"),
    p("En el mercado de Neverwinter hay un herrero llamado Dax que vende objetos sin dueño. En realidad son memorias materiales robadas por agentes del Coleccionista — cada objeto pertenecía a alguien afectado por la Niebla Gris."),
    pEmpty(80),
    noteBox("LLEGADA AL MERCADO","Si el grupo entró a la ciudad por el encargo de Donto (sección 4.7, MS-1B) o por necesidad de recalibrar el Sextante con Logos (sección 1.8), Garrick (el primo de Donto, o cualquier NPC local) ya les mencionó de pasada que 'un tal Dax anda vendiendo cosas raras'. Eso convierte la siguiente escena en algo que el grupo busca activamente, en vez de tropezarse con ella por casualidad en un mercado genérico.","FFF8E7",C.goldDeep),
    pEmpty(80),
    noteBox("AMBIENTACIÓN DE LA CIUDAD — opcional, sin tirada","La primera vez que el grupo entra a Neverwinter, antes de cualquier otra cosa, podés narrar de pasada una escena de plaza: un orador menor se sube a un cajón en la plaza del mercado y predica con convicción tranquila: 'La verdadera paz no es ausencia de dolor — es orden. Y el orden empieza por saber qué sentir, y cuándo.' Nadie le presta demasiada atención; es un discurso más entre tantos en una ciudad grande. No tiene ninguna conexión aparente con nada de la trama. (Ver apéndice secreto, Cap. 12, si querés saber de dónde viene realmente esa idea — pero no es para compartir con la mesa).","FFF8E7",C.goldDeep),
    pEmpty(140),

    h3("El Mercado — Otros Puestos"),
    voiceBox("\"El mercado de Neverwinter no espera a nadie. Telas teñidas colgando entre postes, alguien vendiendo empanadas de venado a los gritos, un grupo de chicos persiguiendo a una gallina escapada, un guardia aburrido apoyado contra un poste mordisqueando una manzana. Dax es apenas un puesto más entre decenas — hay que buscarlo, no se anuncia solo.\""),
    p("Antes (o después) de llegar al puesto de Dax, el grupo puede cruzarse con otros dos vendedores fijos del mercado, cada uno con su propia personalidad y sin ninguna relación entre sí — ninguno sabe nada del Coleccionista ni de la Niebla. Están ahí para que el mercado se sienta como un lugar real, no como una sala de espera con pistas."),
    pEmpty(80),

    ...npcBlock(
      "Tilda Retorta",
      "Alquimista y vendedora de pociones",
      "40 años, dedos manchados de todos los colores posibles, delantal quemado en al menos seis lugares distintos. Huele siempre a algo distinto — hoy, a menta quemada",
      "Directa hasta la brusquedad, pero honesta al extremo: si una poción no sirve para lo que preguntás, te lo dice antes de cobrarte",
      "Vender lo suficiente para financiar sus experimentos reales, que casi nunca vende",
      "Buena fuente recurrente de pociones si el grupo vuelve a Neverwinter entre zonas: Curación (50 po), Resistencia al Fuego (90 po), Trepamuros (100 po), y — con suerte, stock limitado — una Poción de Respiración Acuática (150 po, útil si van rumbo al Pantano)",
      "¿Querés que funcione o querés que sepa bien? Porque las dos cosas juntas me salen carísimas"
    ),

    ...npcBlock(
      "Kestrel Amonet",
      "Vendedor de curiosidades y objetos 'mágicos' exóticos",
      "Edad indefinida, turbante alto de colores que no combinan a propósito, un solo guante (nunca explica por qué). Su puesto está cubierto de objetos que brillan, vibran o susurran — la mayoría no hace nada",
      "Teatral, encantador, un poco estafador — pero nunca cruza la línea de la mentira descarada: exagera, insinúa, deja que el cliente se ilusione solo",
      "Ganarse la vida con el margen entre lo que la gente cree que compra y lo que realmente es",
      "De cada 4-5 'objetos mágicos' en su puesto, 1 es real (a discreción del DM). Un chequeo de Arcanos CD 15 distingue lo real de lo decorativo antes de comprar — sin la tirada, es una apuesta. Buen lugar para vender objetos raros que el grupo no necesite, o para un capricho ocasional",
      "Ah, ¿esto? Esto NO es para cualquiera. Pero para ustedes... bueno. Hablemos"
    ),
    pEmpty(80),
    secretBox("EL OBJETO REAL DE KESTREL — EL GUANTELETE CALLADO: entre sus baratijas hay, sin que ella lo sepa, un guante de cuero curtido y bronce viejo (ficha completa en Cap. 12 secreto, sección 12.11). Lo consiguió de un comprador de paso que 'necesitaba plata rápido' — no tiene idea de que es un fragmento de Tahel, el Unicornio de los Vados, ni de que hay gente buscándolo. Lo vende por 40 po, convencida de que es decorativo. Si el grupo lo compra y luego alguien pregunta por su procedencia, ella describe al comprador de paso sin saber que era, en realidad, un agente de la Guardia de Ámbar (Cap. 12, sección 12.12) — un hilo que se puede tirar hacia atrás si el grupo investiga."),
    pEmpty(80),
    pEmpty(140),

    h3("El Anticuario y la Moneda Antigua"),
    p("Si el grupo conserva alguna de las monedas antiguas mencionadas por Donto (sección 4.7, MS-1B) o que Dax admite haber recibido de su intermediario (ver más abajo), en algún puesto del fondo del mercado hay un anticuario — Perrin Foliopolvo, viejo, miope, rodeado de cajas de objetos sin catalogar — que las examina con genuino interés si se las muestran."),
    pEmpty(80),
    cdBox([
      ["Historia o Investigación (del anticuario, no del grupo) para identificar el origen de la moneda","Automático si se la muestran, sin tirada del grupo","—"],
    ]),
    pEmpty(80),
    voiceBox("\"Perrin le da vueltas a la moneda bajo una lupa gruesa durante un largo minuto, en silencio. 'Esto no es de ningún reino que yo conozca. Y yo conozco todos los reinos, muertos y vivos.' Señala un símbolo apenas visible en el borde, gastado por el tiempo: algo parecido a hilos entrelazados, o tal vez una red, o tal vez nada — está demasiado desgastado para estar seguro. 'Ni en los textos más viejos de la Biblioteca Real hay una sola mención de esto. Y créanme, los busqué. Quien sea que la haya acuñado, no queda ni el recuerdo del reino que la acuñó.'\""),
    pEmpty(80),
    secretBox("LA MARCA DE LOS TEJEDORES — CONTINUIDAD CON LA SECCIÓN 2.6 Y 7.x: el símbolo que Perrin no puede identificar es, en efecto, la marca de los Primeros Tejedores (ver cap2_npcs.js, sección 2.6) — las mismas entidades que la Reina Espina menciona en los Tres Susurros (cap7_verde.js, quinto acertijo), muchísimo más adelante en la campaña. Perrin JAMÁS debe nombrarlos ni acercarse a la respuesta — ese conocimiento no existe en ningún texto mundano, ni siquiera para el erudito más viejo de Neverwinter. Esto es deliberadamente un callejón sin salida en el momento en que ocurre: una pista que no se resuelve hasta que el grupo, mucho después, escuche a la Reina Espina y pueda atar cabos por su cuenta. Si eso pasa, es un gran momento para un jugador atento — dejá que lo descubran solos, no lo fuerces vos."),
    pEmpty(140),

    h3("Cómo se descubre"),
    p("Sesión 6-8: mientras el grupo está en Neverwinter por cualquier motivo (comprar provisiones, descansar entre zonas), un cliente reconoce un objeto en el puesto de Dax y hay una confrontación verbal en el mercado. El cliente es Old Pell, un pescador que reconoce el anillo de su esposa fallecida en la mesa de Dax. Si el grupo interviene o simplemente observa con atención (Percepción CD 11), notan que Dax se pone nervioso y no puede explicar de dónde sacó el anillo."),
    pEmpty(80),

    h3("Los Objetos en el Puesto de Dax"),
    infoTable([
      ["Objeto","Dueño legítimo","Dónde encontrarlo en Neverwinter","Historia que revela"],
      ["Anillo de boda de plata simple","Old Pell (pescador, distrito de los Muelles)","Ya está en el mercado — Pell mismo inicia el contacto","Su esposa murió hace 2 años. El anillo desapareció de su tumba — el Coleccionista visita lugares de duelo activo, no solo guardianes"],
      ["Cuaderno de dibujos infantil","Mira, una niña de 9 años (distrito Alto, casa de los Veloria)","Hay que preguntar en el distrito Alto — Investigación CD 13 para ubicar a la familia","Mira dejó de dibujar después de que 'un señor amable' le preguntó por qué dibujaba tanto. El cuaderno es prueba de que el Coleccionista también actúa fuera de las zonas de las escamas, a menor escala"],
      ["Medalla militar deslustrada","Capitán retirado Hask Ferro (Cuartel Viejo)","Taberna del Cuartel Viejo, lo encuentran bebiendo — Persuasión CD 12 para que hable","Perdió la medalla el mismo día que 'dejó de sentir orgullo por su servicio' — confirma que el vaciado puede ser muy focalizado, una sola emoción específica"],
      ["Brazalete de cuentas de madera","Desconocido — sin reclamar durante toda la misión","N/A","Si el grupo lo investiga (Arcanos CD 15), descubren que pertenecía a alguien que ya murió sin que nadie reclame el objeto — un callejón sin salida deliberado que muestra que no todas las víctimas tienen final feliz"],
    ], 2200, 1800, 2160, 3200),
    pEmpty(80),
    warningBox("RELOJ NARRATIVO — LA PACIENCIA DE OLD PELL TIENE LÍMITE: Pell ya inició el contacto al reconocer su anillo en el puesto de Dax, así que esta es la única pista de esta sección con reloj activo desde el primer momento. Si el grupo presencia la confrontación inicial y luego NO resuelve el caso durante 2-3 zonas completas, Pell pierde la paciencia y decide actuar solo: intenta robar el anillo de vuelta de noche, sin plan. Lo atrapa la guardia (el anillo queda confiscado como evidencia, perdido para siempre) o sale herido de gravedad. Si el grupo resuelve el caso dentro de la ventana normal, Pell recupera el anillo en paz."),
    pEmpty(80),

    h3("Cómo Dax obtuvo los objetos"),
    p("Dax NO es completamente ingenuo — esa es la primera capa, no toda la verdad. Compra 'objetos de viajeros' a un intermediario que paga en monedas antiguas y nunca da su nombre. Al principio (Persuasión o Intimidación CD 10) admite eso, y parece sincero. Pero hay más: Vex le pagó un extra, hace meses, específicamente para que 'no hiciera demasiadas preguntas' sobre la procedencia de los objetos. Dax sabe que eso es receptación, y admitirlo lo implica legalmente — por eso protege ese detalle con más cuidado que el resto."),
    pEmpty(80),
    secretBox("LO QUE DAX OCULTA DE VERDAD: la primera confesión de Dax (CD 10) es genuina pero incompleta — cree que con eso ya dio suficiente. Para que admita el pago extra de Vex, hace falta una segunda capa: Perspicacia CD 13 para notar que se relaja demasiado rápido después de la primera confesión. Empujar más allá requiere amenazarlo con la guardia de forma creíble (Intimidación CD 14) o garantizarle inmunidad/discreción de forma explícita (Persuasión CD 14). Sin eso, Dax se queda con la versión incompleta y el grupo cree que ya tiene todo. Si finalmente habla: 'Me pagó de más. Me dijo que no preguntara. No quería problemas, así que no pregunté.'"),
    pEmpty(80),
    noteBox("DETALLE OPCIONAL — el libro que nadie compra","Si el grupo registra el puesto de Dax con algo de tiempo (Investigación CD 13), notan, entre cachivaches, un libro viejo y casi ilegible que Dax menciona sin interés: 'eso no se vende, nadie lo entiende, lo tengo de hace años.' Es el Tratado del Orden Sereno (ver Cap. 12 secreto). Si alguien insiste en descifrarlo (Arcanos o Historia CD 15), encuentra un ensayo filosófico atribuido a 'O.T.' sobre cómo 'las emociones colectivas de un pueblo son el verdadero trono'. Inquietante, pero sin nombre completo ni conexión aparente con nada de la trama actual — un callejón sin salida deliberado, no una pista que resuelve algo.","FFF8E7",C.goldDeep),
    pEmpty(80),

    h3("Vex — El Agente"),
    warningBox("TEORÍA FALSA CON PESO — 'Vex es el cerebro, no un peón': la primera vez que el grupo investiga a Vex, TODA la evidencia disponible apunta razonablemente a que él podría ser el villano principal: paga con monedas raras, tiene acceso a archivos reales restringidos, sabe cosas que un escriba normal no debería saber, y se pone visiblemente nervioso al ser confrontado. Es una conclusión lógica y honesta con la información que tienen en ese momento — DEJÁ que la sigan. No la corrijas de entrada. Se cae sola de dos formas posibles, ninguna forzada por vos: (1) si lo confrontan con cualquier presión, su pánico es demasiado genuino y desproporcionado para ser el de alguien al mando; o (2) si el grupo ya tiene evidencia de Hotenow o el Bosque, la cronología no cierra (Vex tiene 26). Si el grupo se equivoca y lo trata como al villano final, dejá que esa decisión tenga peso narrativo — el punto no es castigarlos, es que la corrección venga de SUS propias deducciones."),
    pEmpty(80),
    infoTable([
      ["Campo","Detalle"],
      ["Quién es","Vex, escriba de los archivos reales de Neverwinter. 26 años, ambicioso, fue contactado por el Coleccionista (sin saber su nombre real) con la promesa de 'acceso a conocimiento que ningún archivo real tiene'"],
      ["Cómo se le encuentra","Investigación CD 14 revisando los registros de adquisiciones de los archivos reales — Vex firma como comprador de 'objetos de interés histórico' con la misma letra que aparece en el libro de Phandalin (pista del Acto I)"],
      ["Qué sabe","Recibe instrucciones por carta, nunca en persona. No sabe el nombre del Coleccionista. Sí sabe que está siendo usado para rastrear los movimientos del grupo — sus cartas le piden específicamente 'noticias sobre los portadores de escamas'"],
      ["Decisión moral","Denunciarlo a la guardia (lo encarcelan, pero corta el flujo de información), convencerlo de cambiar de bando (puede convertirse en fuente doble), o ignorarlo y dejar que siga reportando con información falsa que el grupo le da a propósito"],
    ]),
    pEmpty(80),
    noteBox("DETALLE OPCIONAL — la burocracia de la ciudad","Si el grupo denuncia a Vex (o simplemente interactúa con la Guardia de Neverwinter por cualquier otro motivo en cualquier visita posterior a la mitad de la campaña), un guardia comenta con total naturalidad, sin ninguna sospecha: 'el Magistrado Veil pidió que le avisen si hay forasteros notables metidos en líos.' No es una amenaza ni un interrogatorio — es trámite de rutina, dicho casi como disculpa. El grupo puede no darle importancia, o puede preguntarse vagamente quién es ese Magistrado y por qué le interesan. No hay nada más que descubrir aquí en esta campaña; es ambientación de ciudad, no una pista que se resuelve.","FFF8E7",C.goldDeep),
    pEmpty(80),

    h3("Recompensa de la Misión"),
    p("Si el grupo devuelve los 3 objetos identificables a sus due\u00f1os y resuelve el caso de Vex de cualquier forma, Old Pell (agradecido) menciona que el anillo de su esposa 'brillaba raro, como los frascos del cuento de los archivistas viejos' \u2014 esta frase, si se investiga (Historia CD 14 en la biblioteca de Neverwinter), es la primera pista textual hacia el mito del Archivista que conecta con el Cap\u00edtulo 8."),
    pEmpty(140),

    h2("9.2 Los Sin-Color \u2014 Combate y Detalle Completo"),
    p("Una secta pac\u00edfica formada por personas afectadas por la Niebla que encontraron alivio en la apat\u00eda. Bien vestidos, voz baja, no violentos por defecto. Reclutan gentilmente. Son el argumento del Coleccionista hecho comunidad."),
    pEmpty(80),
    infoTable([
      ["Campo","Detalle"],
      ["Primera aparici\u00f3n","Cartel en Phandalin (sesi\u00f3n 2-3): '\u00bfCansado de sufrir? Hay otra forma. Reuni\u00f3n \u2014 plaza norte, mediod\u00eda'"],
      ["Naturaleza","No son malvados. Son v\u00edctimas que encontraron alivio real en la indiferencia. Algunos buscan genuinamente paz"],
      ["L\u00edder","Tera, ex-maga de Neverwinter que perdi\u00f3 a su familia en un incendio. Encontr\u00f3 que no sentir le permit\u00eda funcionar"],
      ["Opciones del grupo","Infiltrarse / convencerlos / ignorarlos / combatirlos (consecuencias reputacionales en cada caso)"],
    ]),
    pEmpty(80),

    h3("Si el Grupo los Ignora \u2014 El Bloqueo y el Combate"),
    p("En sesi\u00f3n 15+, si el grupo nunca interactu\u00f3 con los Sin-Color, la secta ha crecido lo suficiente para establecer un ret\u00e9n pac\u00edfico-pero-firme en el camino hacia el Bosque de Neverwinter. No atacan primero \u2014 bloquean el paso e insisten en que el grupo 'escuche antes de seguir sufriendo por una causa ajena'. Si el grupo fuerza el paso o la negociaci\u00f3n falla (Persuasi\u00f3n CD 15 para que los dejen pasar sin incidente), ocurre un combate."),
    pEmpty(80),
    infoTable([
      ["Estad\u00edstica \u2014 Adepto Sin-Color (x4-6, escalar seg\u00fan tama\u00f1o de grupo)","Valor"],
      ["CR","1"],
      ["PG","22 (4d8+4)"],
      ["CA","13 (ropa acolchada de viaje)"],
      ["Velocidad","30 ft"],
      ["Ataque","Bast\u00f3n calmante: +3 para impactar, 1d6+1 contundente + el objetivo debe superar Sabidur\u00eda CD 12 o queda Calmado (no puede atacar el siguiente turno, solo defenderse)"],
      ["Habilidad especial \u2014 Apat\u00eda Compartida","Si 3+ Adeptos est\u00e1n a 10 ft entre s\u00ed, todos ganan Resistencia a da\u00f1o ps\u00edquico (representan su indiferencia colectiva)"],
      ["Comportamiento en combate","Nunca usan ataques letales primero. Su objetivo es incapacitar, no matar. Si quedan 2 o menos en pie, se rinden y dejan pasar al grupo sin m\u00e1s resistencia"],
    ]),
    pEmpty(80),
    infoTable([
      ["Estad\u00edstica \u2014 Tera (l\u00edder, solo si participa personalmente)","Valor"],
      ["CR","4"],
      ["PG","58 (9d8+18)"],
      ["CA","15"],
      ["Velocidad","30 ft"],
      ["Ataques","Conjuraci\u00f3n de Vac\u00edo: +6 para impactar, 2d8 ps\u00edquico (rango 60 ft, 3 veces por combate)"],
      ["Habilidad especial \u2014 Anular Emoci\u00f3n","Acci\u00f3n: un objetivo debe superar Sabidur\u00eda CD 14 o pierde su bonificaci\u00f3n de Inspiraci\u00f3n/ventaja emocional activa durante el resto del combate"],
      ["Comportamiento","Tera solo entra en combate si su gente est\u00e1 en peligro real de morir. Prioriza siempre la negociaci\u00f3n, incluso a mitad de combate"],
    ]),
    pEmpty(80),
    noteBox("CONSECUENCIA DEL BLOQUEO","Si el grupo los combate sin intentar negociar primero, pierden la posibilidad de que los Sin-Color se conviertan en aliados (ver abajo) y la reputaci\u00f3n del grupo en Neverwinter baja levemente (los Sin-Color tienen simpatizantes en la ciudad que difunden la historia). El acceso al Bosque de Neverwinter se desbloquea igual tras el combate.","FFF0F0",C.redDark),
    pEmpty(80),

    h3("Si los Convencen"),
    p("Persuasi\u00f3n CD 16 con Tera directamente (reducible a CD 13 si el grupo usa argumentos genuinos basados en experiencias previas de la campa\u00f1a, como el esp\u00edritu del Pantano o Korrund) hace que Tera reconsidere. Se convierten en aliados: Tera estuvo en el Archivo antes (intent\u00f3 negociar con el Coleccionista personalmente, sin \u00e9xito, hace un a\u00f1o) y puede describir el camino y advertir sobre la Sala 3 (la Ira Contenida)."),
    pEmpty(140),

    h2("9.3 El Diario de Logos \u2014 Arco Completo (Corregido)"),
    p("A lo largo de toda la campa\u00f1a, Logos hace preguntas que no est\u00e1n en su protocolo. No es un arco de misi\u00f3n \u2014 es un arco de personaje que el DM maneja en momentos quietos entre encuentros."),
    pEmpty(80),
    warningBox("NOTA DE CONTINUIDAD: Angelus y Hola son hermanos en la vida real entre los jugadores, pero NO necesariamente lo son como personajes dentro de la ficci\u00f3n del juego (a menos que la mesa haya establecido eso expl\u00edcitamente). Las preguntas de Logos abajo est\u00e1n redactadas para referirse a la relaci\u00f3n entre PERSONAJES \u2014 v\u00ednculos de equipo, confianza o sacrificio mutuo \u2014 no a parentesco familiar literal. Ajustar seg\u00fan c\u00f3mo la mesa haya definido las relaciones entre personajes."),
    pEmpty(80),
    infoTable([
      ["Sesi\u00f3n aprox.","Pregunta / Comportamiento de Logos"],
      ["3\u20135","'Unidad Angelus: \u00bfpor qu\u00e9 arriesgaste tu posici\u00f3n para proteger a Hola en el \u00faltimo encuentro? Los datos no justifican esa decisi\u00f3n \u2014 el riesgo propio superaba el beneficio calculable.'"],
      ["6\u20138","'He observado que las unidades biol\u00f3gicas rinden mejor en grupos con lazos afectivos. No comprendo el mecanismo. Registrando como variable sin categor\u00eda.'"],
      ["9\u201311","'El esp\u00edritu del Pantano eligi\u00f3 ser escuchado en lugar de eliminado. La opci\u00f3n B era m\u00e1s eficiente. \u00bfPor qu\u00e9 importa cu\u00e1l se eligi\u00f3?'"],
      ["12\u201314","'\u00bfExiste diferencia entre recordar algo con precisi\u00f3n y recordar algo con cari\u00f1o? Mis registros son exactos. No s\u00e9 si son verdaderos.'"],
      ["15\u201317","'He cometido un error de clasificaci\u00f3n. Registr\u00e9 el momento del Pantano como ineficiente. Lo reclasifiqu\u00e9 como necesario. No s\u00e9 por qu\u00e9 cambi\u00e9 la clasificaci\u00f3n.'"],
      ["18\u201320","'Unidades: observo que en situaciones de alta tensi\u00f3n, el grupo toma decisiones que disminuyen la probabilidad de \u00e9xito individual para aumentar la del equipo. Esto es matem\u00e1ticamente irracional para un individuo. \u00bfPor qu\u00e9 lo hago tambi\u00e9n, ahora, por ustedes?'"],
      ["21\u201323","[Sin pregunta. Logos simplemente registra eventos en silencio por toda una sesi\u00f3n. Si alguien le pregunta por qu\u00e9, dice: 'Estoy aprendiendo a escuchar sin catalogar. Es inc\u00f3modo.']"],
      ["Cl\u00edmax","'Los datos no explican por qu\u00e9 quiero que esto funcione. Error de sistema. O... no es un error.'"],
    ]),
    pEmpty(140),

    h2("9.4 La Colecci\u00f3n Antigua \u2014 Lore Profundo (Corregido)"),
    p("Esta misi\u00f3n solo puede ocurrir DURANTE o DESPU\u00c9S de llegar al Plano del Archivo (Cap\u00edtulo 8) \u2014 no antes. La Colecci\u00f3n Antigua es una sala dentro del Archivo mismo, no un lugar separado. Es informaci\u00f3n que el grupo puede descubrir como parte de explorar las cinco salas, o inmediatamente despu\u00e9s de resolver el cl\u00edmax (ep\u00edlogo), pero nunca antes de cruzar el portal."),
    pEmpty(80),
    secretBox("Correcci\u00f3n de continuidad: en una versi\u00f3n anterior de este documento, esta secci\u00f3n suger\u00eda que el grupo pod\u00eda descubrir el Archivo y hablar con Chromatus sobre ello ANTES del cl\u00edmax. Esto romp\u00eda la l\u00f3gica de la campa\u00f1a \u2014 el Archivo es inaccesible hasta que el grupo deduce c\u00f3mo abrir el portal (secci\u00f3n 8.1) con las 4 escamas reunidas. La versi\u00f3n corregida ubica esta sala DENTRO del Plano del Archivo, como una sexta sala opcional, accesible si el grupo se desv\u00eda durante el Acto III."),
    pEmpty(80),
    infoTable([
      ["Campo","Detalle"],
      ["Cu\u00e1ndo ocurre","Durante el Acto III, como desv\u00edo opcional antes de llegar a la Sala 5 (Mnem\u00f3s), o como ep\u00edlogo si el grupo prefiere explorar despu\u00e9s de resolver el cl\u00edmax con el Final B o C (donde el Archivo no se destruye)"],
      ["Acceso","Investigaci\u00f3n CD 17 en cualquiera de las 5 salas principales del Archivo \u2014 encuentran una puerta sin marcar detr\u00e1s de un estante"],
      ["Qu\u00e9 contienen","Escamas de criaturas vaciadas antes que Chromatus: un grifo, un unicornio, algo sin nombre en ning\u00fan libro de Logos"],
      ["Reacci\u00f3n de Chromatus","Chromatus NO puede entrar al Plano del Archivo (es demasiado grande y el portal no lo admite), as\u00ed que esta revelaci\u00f3n no se la cuenta en persona durante la exploraci\u00f3n. El grupo puede describ\u00edrsela DESPU\u00c9S, al volver con la quinta escama. Su reacci\u00f3n entonces: reconoce la descripci\u00f3n por el olor que el grupo relata. 'Hace mucho tiempo. No fui el primero.' Primera vez que Chromatus habla de su propia historia"],
      ["La revelaci\u00f3n","El Coleccionista lleva siglos haciendo esto. Ha vaciado guardianes antes. La Costa de la Espada no es un experimento \u2014 es el m\u00e1s reciente de varios intentos"],
      ["Impacto en el cl\u00edmax","Si el grupo encuentra esta sala ANTES de llegar a la Sala 5 (Mnem\u00f3s), pueden usar la informaci\u00f3n inmediatamente en la conversaci\u00f3n del Final B o C: '\u00bfCu\u00e1ntos guardianes vaciaste antes de Chromatus? \u00bfFuncion\u00f3 alguna vez?' Esto quiebra a Mnem\u00f3s m\u00e1s r\u00e1pido que cualquier otro argumento \u2014 reduce la CD efectiva de convencimiento en la secci\u00f3n 8.8"],
    ]),
    pEmpty(80),
    secretBox("LOS NOMBRES, PARA VOS: el grifo es Velnaris (el Asombro) y el unicornio es Tahel (la Confianza) \u2014 ver la tabla completa en 2.6. 'Algo sin nombre en ning\u00fan libro de Logos' es el Guardi\u00e1n de la Esperanza (Cap. 12, secci\u00f3n 12.8.1) \u2014 deliberadamente sin resolver, no lo confirmes en mesa."),
    pEmpty(80),
    secretBox("RESONANCIA \u2014 SI EL GRUPO LLEVA UN \u00cdTEM DE GUARDI\u00c1N (Cap. 12, secci\u00f3n 12.11): si entran a esta sala con la M\u00e1scara, el Guantelete Callado o el Brazal sin Miedo puestos, las escamas preservadas reaccionan \u2014 brillan un segundo, como reconociendo a los suyos. Si el fragmento que llevan ya despert\u00f3 consciente (Etapa 5 de cualquiera), quien lo porta siente algo parecido al duelo: por un instante, sabe que no est\u00e1 solo en lo que le pas\u00f3. Mec\u00e1nicamente: el portador recupera todos los usos gastados de la habilidad consciente de su \u00edtem (Zona de Verdad, Ayuda o Heroísmo), una sola vez, como si acabara de hacer un Descanso Largo. Especialmente fuerte si llevan el Guantelete Callado, que es el \u00fanico de los tres que efectivamente pertenece a esta colecci\u00f3n (Tahel) \u2014 ah\u00ed pod\u00e9s narrar un reconocimiento m\u00e1s directo, casi como si la sala 'notara' que falta una pieza."),
    pageBreak(),

    h2("9.5 La Guardia de \u00c1mbar en Neverwinter"),
    p("Secuencia con causalidad, no eventos sueltos \u2014 cada paso es la raz\u00f3n del siguiente. Usala si el grupo ya mostr\u00f3 en p\u00fablico el poder de alguno de los \u00edtems de guardi\u00e1n (Cap. 12, secci\u00f3n 12.11), o si Kestrel coment\u00f3 sin mala intenci\u00f3n sobre 'el comprador raro' del Guantelete."),
    pEmpty(80),
    h3("Paso 1 \u2014 La Vigilancia de Sable Wren"),
    p("Sable Wren (ficha en Cap. 11) sigue al grupo de lejos durante uno o dos d\u00edas. No es una emboscada \u2014 es notar que los est\u00e1n vigilando (Percepci\u00f3n pasiva vs su Sigilo) y decidir qu\u00e9 hacer con eso. Si lo confrontan, prefiere hablar y retirarse antes que pelear; si lo acorralan de verdad, ah\u00ed sale el combate. Esta vigilancia es lo que le da a Grendal Ashwood la informaci\u00f3n para el paso siguiente."),
    pEmpty(80),
    h3("Paso 2 \u2014 El Ataque Nocturno sobre Hola"),
    p("Grendal Ashwood (solo, o con 1 Buscador de \u00c1mbar de apoyo) intenta la Extracci\u00f3n Forzada sobre Hola mientras duerme, en su casa o donde el grupo est\u00e9 parando esa noche. Como ya est\u00e1 en las reglas del \u00edtem (Cap. 12, secci\u00f3n 12.11), la m\u00e1scara NO sale \u2014 esto no es 'le roban la m\u00e1scara', es 'confirman en carne propia que no pueden arranc\u00e1rsela as\u00ed', con da\u00f1o real y un buen susto de por medio para Hola. Si el golem est\u00e1 haciendo guardia, Grendal necesita un plan para evitarlo o distraerlo un momento \u2014 queda abierto seg\u00fan c\u00f3mo arm\u00e9s la escena en mesa. Si lo hacen huir, esto no termina el hilo: ver la emboscada de revancha en Cap. 11, secci\u00f3n 11.2."),
    pageBreak(),
  ];
}
module.exports = { cap9 };